// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_150_1_VITIS_LOOP_151_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_b1_pw_address0,
        buf_b1_pw_ce0,
        buf_b1_pw_q0,
        buf_b1_pw_address1,
        buf_b1_pw_ce1,
        buf_b1_pw_q1,
        buf_b1_pool_address0,
        buf_b1_pool_ce0,
        buf_b1_pool_we0,
        buf_b1_pool_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] buf_b1_pw_address0;
output   buf_b1_pw_ce0;
input  [6:0] buf_b1_pw_q0;
output  [10:0] buf_b1_pw_address1;
output   buf_b1_pw_ce1;
input  [6:0] buf_b1_pw_q1;
output  [9:0] buf_b1_pool_address0;
output   buf_b1_pool_ce0;
output   buf_b1_pool_we0;
output  [6:0] buf_b1_pool_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln150_fu_126_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln150_fu_155_p3;
reg   [4:0] select_ln150_reg_339;
reg   [4:0] select_ln150_reg_339_pp0_iter2_reg;
reg   [4:0] select_ln150_reg_339_pp0_iter3_reg;
wire   [4:0] add_ln15071_fu_171_p2;
reg   [4:0] add_ln15071_reg_345;
reg   [4:0] add_ln15071_reg_345_pp0_iter2_reg;
reg   [4:0] add_ln15071_reg_345_pp0_iter3_reg;
wire   [6:0] select_ln154_fu_268_p3;
reg   [6:0] select_ln154_reg_363;
wire   [63:0] zext_ln152_1_fu_234_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln153_fu_257_p1;
wire   [63:0] zext_ln154_fu_309_p1;
reg   [4:0] t_fu_58;
wire   [4:0] add_ln151_fu_177_p2;
wire    ap_loop_init;
reg   [4:0] c_1_fu_62;
reg   [9:0] indvar_flatten13_fu_66;
wire   [9:0] add_ln150_1_fu_132_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    buf_b1_pw_ce1_local;
reg    buf_b1_pw_ce0_local;
reg    buf_b1_pool_we0_local;
reg    buf_b1_pool_ce0_local;
wire   [0:0] icmp_ln151_fu_149_p2;
wire   [4:0] empty_fu_163_p3;
wire   [6:0] tmp_fu_200_p3;
wire   [10:0] p_shl2_fu_193_p3;
wire   [10:0] zext_ln152_3_fu_207_p1;
wire   [5:0] shl_ln_fu_217_p3;
wire   [10:0] zext_ln152_fu_224_p1;
wire   [10:0] sub_ln152_fu_211_p2;
wire   [10:0] add_ln152_fu_228_p2;
wire   [9:0] tmp_s_fu_239_p4;
wire   [10:0] or_ln2_fu_249_p3;
wire   [0:0] icmp_ln154_fu_262_p2;
wire   [5:0] tmp_1_fu_283_p3;
wire   [9:0] p_shl_fu_276_p3;
wire   [9:0] zext_ln154_3_fu_290_p1;
wire   [9:0] zext_ln151_fu_300_p1;
wire   [9:0] sub_ln154_fu_294_p2;
wire   [9:0] add_ln154_fu_303_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 t_fu_58 = 5'd0;
#0 c_1_fu_62 = 5'd0;
#0 indvar_flatten13_fu_66 = 10'd0;
#0 ap_done_reg = 1'b0;
end

cnn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_1_fu_62 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_1_fu_62 <= add_ln15071_fu_171_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln150_fu_126_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_66 <= add_ln150_1_fu_132_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_66 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_fu_58 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            t_fu_58 <= add_ln151_fu_177_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln15071_reg_345 <= add_ln15071_fu_171_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln150_reg_339 <= select_ln150_fu_155_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln15071_reg_345_pp0_iter2_reg <= add_ln15071_reg_345;
        add_ln15071_reg_345_pp0_iter3_reg <= add_ln15071_reg_345_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        select_ln150_reg_339_pp0_iter2_reg <= select_ln150_reg_339;
        select_ln150_reg_339_pp0_iter3_reg <= select_ln150_reg_339_pp0_iter2_reg;
        select_ln154_reg_363 <= select_ln154_fu_268_p3;
    end
end

always @ (*) begin
    if (((icmp_ln150_fu_126_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buf_b1_pool_ce0_local = 1'b1;
    end else begin
        buf_b1_pool_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buf_b1_pool_we0_local = 1'b1;
    end else begin
        buf_b1_pool_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_b1_pw_ce0_local = 1'b1;
    end else begin
        buf_b1_pw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_b1_pw_ce1_local = 1'b1;
    end else begin
        buf_b1_pw_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15071_fu_171_p2 = (c_1_fu_62 + empty_fu_163_p3);

assign add_ln150_1_fu_132_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 10'd1);

assign add_ln151_fu_177_p2 = (select_ln150_fu_155_p3 + 5'd1);

assign add_ln152_fu_228_p2 = (zext_ln152_fu_224_p1 + sub_ln152_fu_211_p2);

assign add_ln154_fu_303_p2 = (zext_ln151_fu_300_p1 + sub_ln154_fu_294_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_b1_pool_address0 = zext_ln154_fu_309_p1;

assign buf_b1_pool_ce0 = buf_b1_pool_ce0_local;

assign buf_b1_pool_d0 = select_ln154_reg_363;

assign buf_b1_pool_we0 = buf_b1_pool_we0_local;

assign buf_b1_pw_address0 = zext_ln153_fu_257_p1;

assign buf_b1_pw_address1 = zext_ln152_1_fu_234_p1;

assign buf_b1_pw_ce0 = buf_b1_pw_ce0_local;

assign buf_b1_pw_ce1 = buf_b1_pw_ce1_local;

assign empty_fu_163_p3 = ((icmp_ln151_fu_149_p2[0:0] == 1'b1) ? 5'd1 : 5'd0);

assign icmp_ln150_fu_126_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 10'd720) ? 1'b1 : 1'b0);

assign icmp_ln151_fu_149_p2 = ((t_fu_58 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_262_p2 = ((buf_b1_pw_q1 > buf_b1_pw_q0) ? 1'b1 : 1'b0);

assign or_ln2_fu_249_p3 = {{tmp_s_fu_239_p4}, {1'd1}};

assign p_shl2_fu_193_p3 = {{add_ln15071_reg_345}, {6'd0}};

assign p_shl_fu_276_p3 = {{add_ln15071_reg_345_pp0_iter3_reg}, {5'd0}};

assign select_ln150_fu_155_p3 = ((icmp_ln151_fu_149_p2[0:0] == 1'b1) ? 5'd0 : t_fu_58);

assign select_ln154_fu_268_p3 = ((icmp_ln154_fu_262_p2[0:0] == 1'b1) ? buf_b1_pw_q1 : buf_b1_pw_q0);

assign shl_ln_fu_217_p3 = {{select_ln150_reg_339}, {1'd0}};

assign sub_ln152_fu_211_p2 = (p_shl2_fu_193_p3 - zext_ln152_3_fu_207_p1);

assign sub_ln154_fu_294_p2 = (p_shl_fu_276_p3 - zext_ln154_3_fu_290_p1);

assign tmp_1_fu_283_p3 = {{add_ln15071_reg_345_pp0_iter3_reg}, {1'd0}};

assign tmp_fu_200_p3 = {{add_ln15071_reg_345}, {2'd0}};

assign tmp_s_fu_239_p4 = {{add_ln152_fu_228_p2[10:1]}};

assign zext_ln151_fu_300_p1 = select_ln150_reg_339_pp0_iter3_reg;

assign zext_ln152_1_fu_234_p1 = add_ln152_fu_228_p2;

assign zext_ln152_3_fu_207_p1 = tmp_fu_200_p3;

assign zext_ln152_fu_224_p1 = shl_ln_fu_217_p3;

assign zext_ln153_fu_257_p1 = or_ln2_fu_249_p3;

assign zext_ln154_3_fu_290_p1 = tmp_1_fu_283_p3;

assign zext_ln154_fu_309_p1 = add_ln154_fu_303_p2;

endmodule //cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_150_1_VITIS_LOOP_151_2
