// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_b1_dw_address0,
        buf_b1_dw_ce0,
        buf_b1_dw_q0,
        buf_b1_dw_address1,
        buf_b1_dw_ce1,
        buf_b1_dw_q1,
        buf_b1_dw_address2,
        buf_b1_dw_ce2,
        buf_b1_dw_q2,
        buf_b1_dw_address3,
        buf_b1_dw_ce3,
        buf_b1_dw_q3,
        buf_b1_dw_address4,
        buf_b1_dw_ce4,
        buf_b1_dw_q4,
        buf_b1_dw_address5,
        buf_b1_dw_ce5,
        buf_b1_dw_q5,
        buf_b1_dw_address6,
        buf_b1_dw_ce6,
        buf_b1_dw_q6,
        buf_b1_dw_address7,
        buf_b1_dw_ce7,
        buf_b1_dw_q7,
        buf_b1_dw_address8,
        buf_b1_dw_ce8,
        buf_b1_dw_q8,
        buf_b1_dw_address9,
        buf_b1_dw_ce9,
        buf_b1_dw_q9,
        buf_b1_dw_address10,
        buf_b1_dw_ce10,
        buf_b1_dw_q10,
        buf_b1_dw_address11,
        buf_b1_dw_ce11,
        buf_b1_dw_q11,
        buf_b1_pw_address0,
        buf_b1_pw_ce0,
        buf_b1_pw_we0,
        buf_b1_pw_d0,
        grp_requantize_fu_466_p_din1,
        grp_requantize_fu_466_p_din2,
        grp_requantize_fu_466_p_din3,
        grp_requantize_fu_466_p_dout0,
        grp_requantize_fu_466_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] buf_b1_dw_address0;
output   buf_b1_dw_ce0;
input  [7:0] buf_b1_dw_q0;
output  [10:0] buf_b1_dw_address1;
output   buf_b1_dw_ce1;
input  [7:0] buf_b1_dw_q1;
output  [10:0] buf_b1_dw_address2;
output   buf_b1_dw_ce2;
input  [7:0] buf_b1_dw_q2;
output  [10:0] buf_b1_dw_address3;
output   buf_b1_dw_ce3;
input  [7:0] buf_b1_dw_q3;
output  [10:0] buf_b1_dw_address4;
output   buf_b1_dw_ce4;
input  [7:0] buf_b1_dw_q4;
output  [10:0] buf_b1_dw_address5;
output   buf_b1_dw_ce5;
input  [7:0] buf_b1_dw_q5;
output  [10:0] buf_b1_dw_address6;
output   buf_b1_dw_ce6;
input  [7:0] buf_b1_dw_q6;
output  [10:0] buf_b1_dw_address7;
output   buf_b1_dw_ce7;
input  [7:0] buf_b1_dw_q7;
output  [10:0] buf_b1_dw_address8;
output   buf_b1_dw_ce8;
input  [7:0] buf_b1_dw_q8;
output  [10:0] buf_b1_dw_address9;
output   buf_b1_dw_ce9;
input  [7:0] buf_b1_dw_q9;
output  [10:0] buf_b1_dw_address10;
output   buf_b1_dw_ce10;
input  [7:0] buf_b1_dw_q10;
output  [10:0] buf_b1_dw_address11;
output   buf_b1_dw_ce11;
input  [7:0] buf_b1_dw_q11;
output  [10:0] buf_b1_pw_address0;
output   buf_b1_pw_ce0;
output   buf_b1_pw_we0;
output  [6:0] buf_b1_pw_d0;
output  [22:0] grp_requantize_fu_466_p_din1;
output  [30:0] grp_requantize_fu_466_p_din2;
output  [1:0] grp_requantize_fu_466_p_din3;
input  [7:0] grp_requantize_fu_466_p_dout0;
output   grp_requantize_fu_466_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln100_reg_2043;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] b1_pw_bias_address0;
wire   [15:0] b1_pw_bias_q0;
wire  signed [7:0] b1_pw_weight_q0;
wire  signed [7:0] b1_pw_weight_q1;
wire  signed [7:0] b1_pw_weight_q2;
wire  signed [7:0] b1_pw_weight_q3;
wire   [7:0] b1_pw_weight_q4;
wire  signed [7:0] b1_pw_weight_q5;
wire   [7:0] b1_pw_weight_q6;
wire  signed [7:0] b1_pw_weight_q7;
wire  signed [7:0] b1_pw_weight_q8;
wire  signed [7:0] b1_pw_weight_q9;
wire   [7:0] b1_pw_weight_q10;
wire   [7:0] b1_pw_weight_q11;
reg  signed [7:0] reg_707;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
reg  signed [7:0] reg_712;
reg  signed [7:0] reg_717;
reg  signed [7:0] reg_722;
reg  signed [7:0] reg_727;
reg  signed [7:0] reg_732;
reg  signed [7:0] reg_737;
reg  signed [7:0] reg_742;
reg  signed [7:0] reg_747;
reg  signed [7:0] reg_752;
reg  signed [7:0] reg_757;
reg  signed [7:0] reg_762;
wire   [0:0] icmp_ln100_fu_785_p2;
wire   [5:0] select_ln100_fu_809_p3;
reg   [5:0] select_ln100_reg_2047;
wire   [4:0] add_ln100_fu_825_p2;
reg   [4:0] add_ln100_reg_2059;
reg   [4:0] add_ln100_reg_2059_pp0_iter1_reg;
reg   [4:0] add_ln100_reg_2059_pp0_iter2_reg;
wire   [9:0] sub_ln105_fu_859_p2;
reg   [9:0] sub_ln105_reg_2068;
wire   [10:0] zext_ln101_1_fu_1053_p1;
reg   [10:0] zext_ln101_1_reg_2144;
wire   [9:0] zext_ln101_2_fu_1056_p1;
reg   [9:0] zext_ln101_2_reg_2155;
wire   [7:0] zext_ln101_4_fu_1062_p1;
reg   [7:0] zext_ln101_4_reg_2162;
wire   [8:0] zext_ln101_5_fu_1065_p1;
reg   [8:0] zext_ln101_5_reg_2167;
wire   [10:0] add_ln109_fu_1531_p2;
reg   [10:0] add_ln109_reg_2412;
reg   [10:0] add_ln109_reg_2412_pp0_iter2_reg;
reg   [10:0] add_ln109_reg_2412_pp0_iter3_reg;
reg   [10:0] add_ln109_reg_2412_pp0_iter4_reg;
reg   [10:0] add_ln109_reg_2412_pp0_iter5_reg;
reg   [10:0] add_ln109_reg_2412_pp0_iter6_reg;
reg   [10:0] add_ln109_reg_2412_pp0_iter7_reg;
reg  signed [7:0] b1_pw_weight_load_reg_2417;
reg  signed [7:0] b1_pw_weight_load_22_reg_2457;
reg  signed [7:0] val_reg_2467;
reg  signed [7:0] val_102_reg_2507;
wire   [15:0] mul_ln105_21_fu_1616_p2;
reg  signed [15:0] mul_ln105_21_reg_2517;
wire   [15:0] mul_ln105_24_fu_1622_p2;
reg  signed [15:0] mul_ln105_24_reg_2522;
wire  signed [15:0] mul_ln105_3_fu_1676_p2;
wire  signed [15:0] mul_ln105_6_fu_1682_p2;
wire  signed [15:0] mul_ln105_9_fu_1688_p2;
wire  signed [15:0] mul_ln105_12_fu_1694_p2;
wire   [15:0] mul_ln105_14_fu_1700_p2;
reg  signed [15:0] mul_ln105_14_reg_2557;
wire  signed [15:0] mul_ln105_16_fu_1722_p2;
wire  signed [15:0] mul_ln105_18_fu_1728_p2;
wire  signed [15:0] grp_fu_1926_p3;
reg  signed [15:0] add_ln105_32_reg_2602;
wire   [17:0] add_ln105_20_fu_1769_p2;
reg   [17:0] add_ln105_20_reg_2607;
wire   [17:0] add_ln105_25_fu_1781_p2;
reg   [17:0] add_ln105_25_reg_2612;
wire   [17:0] add_ln105_31_fu_1793_p2;
reg   [17:0] add_ln105_31_reg_2617;
wire   [16:0] add_ln105_36_fu_1808_p2;
reg   [16:0] add_ln105_36_reg_2627;
wire   [18:0] add_ln105_26_fu_1820_p2;
reg   [18:0] add_ln105_26_reg_2632;
wire   [18:0] add_ln105_38_fu_1845_p2;
reg   [18:0] add_ln105_38_reg_2637;
wire   [19:0] acc_9_fu_1857_p2;
reg   [19:0] acc_9_reg_2642;
wire  signed [22:0] sext_ln102_fu_1863_p1;
wire   [6:0] select_ln108_fu_1879_p3;
reg   [6:0] select_ln108_reg_2652;
reg    grp_requantize_fu_698_ap_ce;
wire    ap_block_pp0_stage1_11001_ignoreCallOp477;
wire    ap_block_pp0_stage0_11001_ignoreCallOp478;
wire    ap_block_pp0_stage1_ignoreCallOp477;
wire   [63:0] zext_ln105_fu_883_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln105_1_fu_906_p1;
wire   [63:0] zext_ln105_2_fu_919_p1;
wire   [63:0] zext_ln105_3_fu_942_p1;
wire   [63:0] zext_ln105_4_fu_967_p1;
wire   [63:0] zext_ln105_5_fu_980_p1;
wire   [63:0] zext_ln105_6_fu_993_p1;
wire   [63:0] zext_ln105_7_fu_1004_p1;
wire   [63:0] zext_ln105_9_fu_1015_p1;
wire   [63:0] zext_ln105_12_fu_1026_p1;
wire   [63:0] zext_ln105_15_fu_1037_p1;
wire   [63:0] zext_ln105_18_fu_1048_p1;
wire   [63:0] zext_ln104_fu_1074_p1;
wire   [63:0] zext_ln104_1_fu_1085_p1;
wire   [63:0] zext_ln104_2_fu_1096_p1;
wire   [63:0] zext_ln104_3_fu_1107_p1;
wire   [63:0] zext_ln104_4_fu_1118_p1;
wire   [63:0] zext_ln104_5_fu_1129_p1;
wire   [63:0] zext_ln104_46_fu_1144_p1;
wire   [63:0] zext_ln104_7_fu_1155_p1;
wire   [63:0] zext_ln104_9_fu_1166_p1;
wire   [63:0] zext_ln104_47_fu_1181_p1;
wire   [63:0] zext_ln104_50_fu_1197_p1;
wire   [63:0] zext_ln104_18_fu_1208_p1;
wire   [63:0] zext_ln109_fu_1223_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln105_8_fu_1264_p1;
wire   [63:0] zext_ln105_10_fu_1278_p1;
wire   [63:0] zext_ln105_11_fu_1288_p1;
wire   [63:0] zext_ln105_13_fu_1302_p1;
wire   [63:0] zext_ln105_14_fu_1312_p1;
wire   [63:0] zext_ln105_16_fu_1326_p1;
wire   [63:0] zext_ln105_17_fu_1336_p1;
wire   [63:0] zext_ln105_19_fu_1350_p1;
wire   [63:0] zext_ln105_20_fu_1360_p1;
wire   [63:0] zext_ln105_21_fu_1370_p1;
wire   [63:0] zext_ln105_22_fu_1380_p1;
wire   [63:0] zext_ln101_fu_1385_p1;
wire   [63:0] zext_ln104_8_fu_1402_p1;
wire   [63:0] zext_ln104_10_fu_1416_p1;
wire   [63:0] zext_ln104_11_fu_1426_p1;
wire   [63:0] zext_ln104_48_fu_1444_p1;
wire   [63:0] zext_ln104_49_fu_1458_p1;
wire   [63:0] zext_ln104_16_fu_1472_p1;
wire   [63:0] zext_ln104_17_fu_1482_p1;
wire   [63:0] zext_ln104_19_fu_1496_p1;
wire   [63:0] zext_ln104_20_fu_1506_p1;
wire   [63:0] zext_ln104_21_fu_1516_p1;
wire   [63:0] zext_ln104_22_fu_1526_p1;
wire   [63:0] zext_ln100_fu_1706_p1;
wire   [63:0] zext_ln109_1_fu_1887_p1;
reg   [5:0] t_fu_178;
wire   [5:0] add_ln101_fu_1213_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_t_load;
reg   [4:0] oc_fu_182;
reg   [4:0] ap_sig_allocacmp_oc_load;
reg   [10:0] indvar_flatten6_fu_186;
wire   [10:0] add_ln100_1_fu_791_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    b1_pw_weight_ce11_local;
reg   [9:0] b1_pw_weight_address11_local;
reg    b1_pw_weight_ce10_local;
reg   [9:0] b1_pw_weight_address10_local;
reg    b1_pw_weight_ce9_local;
reg   [9:0] b1_pw_weight_address9_local;
reg    b1_pw_weight_ce8_local;
reg   [9:0] b1_pw_weight_address8_local;
reg    b1_pw_weight_ce7_local;
reg   [9:0] b1_pw_weight_address7_local;
reg    b1_pw_weight_ce6_local;
reg   [9:0] b1_pw_weight_address6_local;
reg    b1_pw_weight_ce5_local;
reg   [9:0] b1_pw_weight_address5_local;
reg    b1_pw_weight_ce4_local;
reg   [9:0] b1_pw_weight_address4_local;
reg    b1_pw_weight_ce3_local;
reg   [9:0] b1_pw_weight_address3_local;
reg    b1_pw_weight_ce2_local;
reg   [9:0] b1_pw_weight_address2_local;
reg    b1_pw_weight_ce1_local;
reg   [9:0] b1_pw_weight_address1_local;
reg    b1_pw_weight_ce0_local;
reg   [9:0] b1_pw_weight_address0_local;
reg    buf_b1_dw_ce11_local;
reg   [10:0] buf_b1_dw_address11_local;
reg    buf_b1_dw_ce10_local;
reg   [10:0] buf_b1_dw_address10_local;
reg    buf_b1_dw_ce9_local;
reg   [10:0] buf_b1_dw_address9_local;
reg    buf_b1_dw_ce8_local;
reg   [10:0] buf_b1_dw_address8_local;
reg    buf_b1_dw_ce7_local;
reg   [10:0] buf_b1_dw_address7_local;
reg    buf_b1_dw_ce6_local;
reg   [10:0] buf_b1_dw_address6_local;
reg    buf_b1_dw_ce5_local;
reg   [10:0] buf_b1_dw_address5_local;
reg    buf_b1_dw_ce4_local;
reg   [10:0] buf_b1_dw_address4_local;
reg    buf_b1_dw_ce3_local;
reg   [10:0] buf_b1_dw_address3_local;
reg    buf_b1_dw_ce2_local;
reg   [10:0] buf_b1_dw_address2_local;
reg    buf_b1_dw_ce1_local;
reg   [10:0] buf_b1_dw_address1_local;
reg    buf_b1_dw_ce0_local;
reg   [10:0] buf_b1_dw_address0_local;
reg    b1_pw_bias_ce0_local;
reg    buf_b1_pw_we0_local;
reg    buf_b1_pw_ce0_local;
wire   [0:0] icmp_ln101_fu_803_p2;
wire   [4:0] empty_fu_817_p3;
wire   [7:0] tmp_6_fu_848_p3;
wire   [9:0] p_shl3_fu_841_p3;
wire   [9:0] zext_ln105_47_fu_855_p1;
wire   [8:0] tmp_fu_865_p4;
wire   [9:0] or_ln_fu_875_p3;
wire   [7:0] tmp_1_fu_888_p4;
wire   [9:0] or_ln105_1_fu_898_p3;
wire   [9:0] or_ln105_2_fu_911_p3;
wire   [6:0] tmp_4_fu_924_p4;
wire   [9:0] or_ln105_3_fu_934_p3;
wire   [0:0] tmp_8_fu_947_p3;
wire   [9:0] or_ln105_4_fu_955_p5;
wire   [9:0] or_ln105_5_fu_972_p3;
wire   [9:0] or_ln105_6_fu_985_p3;
wire   [9:0] add_ln105_fu_998_p2;
wire   [9:0] add_ln105_2_fu_1009_p2;
wire   [9:0] add_ln105_5_fu_1020_p2;
wire   [9:0] add_ln105_8_fu_1031_p2;
wire   [9:0] add_ln105_11_fu_1042_p2;
wire   [6:0] zext_ln101_3_fu_1059_p1;
wire   [6:0] add_ln104_fu_1068_p2;
wire   [7:0] add_ln104_1_fu_1079_p2;
wire   [7:0] add_ln104_2_fu_1090_p2;
wire   [8:0] add_ln104_3_fu_1101_p2;
wire   [8:0] add_ln104_4_fu_1112_p2;
wire   [8:0] add_ln104_5_fu_1123_p2;
wire   [7:0] add_ln104_6_fu_1134_p2;
wire  signed [8:0] sext_ln104_56_fu_1140_p1;
wire   [9:0] add_ln104_7_fu_1149_p2;
wire   [9:0] add_ln104_9_fu_1160_p2;
wire   [8:0] add_ln104_12_fu_1171_p2;
wire  signed [9:0] sext_ln104_57_fu_1177_p1;
wire   [6:0] or_ln1_fu_1186_p3;
wire  signed [9:0] sext_ln104_60_fu_1193_p1;
wire   [10:0] add_ln104_17_fu_1202_p2;
wire   [6:0] tmp_7_fu_1234_p3;
wire   [10:0] p_shl_fu_1227_p3;
wire   [10:0] zext_ln109_3_fu_1241_p1;
wire   [9:0] add_ln105_1_fu_1259_p2;
wire   [9:0] add_ln105_3_fu_1273_p2;
wire   [9:0] add_ln105_4_fu_1283_p2;
wire   [9:0] add_ln105_6_fu_1297_p2;
wire   [9:0] add_ln105_7_fu_1307_p2;
wire   [9:0] add_ln105_9_fu_1321_p2;
wire   [9:0] add_ln105_10_fu_1331_p2;
wire   [9:0] add_ln105_12_fu_1345_p2;
wire   [9:0] add_ln105_13_fu_1355_p2;
wire   [9:0] add_ln105_14_fu_1365_p2;
wire   [9:0] add_ln105_15_fu_1375_p2;
wire   [9:0] add_ln104_8_fu_1397_p2;
wire   [9:0] add_ln104_10_fu_1411_p2;
wire   [9:0] add_ln104_11_fu_1421_p2;
wire   [8:0] add_ln104_13_fu_1435_p2;
wire  signed [9:0] sext_ln104_58_fu_1440_p1;
wire   [7:0] add_ln104_14_fu_1449_p2;
wire  signed [9:0] sext_ln104_59_fu_1454_p1;
wire   [10:0] add_ln104_15_fu_1467_p2;
wire   [10:0] add_ln104_16_fu_1477_p2;
wire   [10:0] add_ln104_18_fu_1491_p2;
wire   [10:0] add_ln104_19_fu_1501_p2;
wire   [10:0] add_ln104_20_fu_1511_p2;
wire   [10:0] add_ln104_21_fu_1521_p2;
wire   [10:0] sub_ln109_fu_1245_p2;
wire  signed [15:0] grp_fu_1934_p3;
wire  signed [15:0] grp_fu_1891_p3;
wire  signed [15:0] grp_fu_1899_p3;
wire  signed [15:0] grp_fu_1908_p3;
wire  signed [15:0] grp_fu_1917_p3;
wire  signed [15:0] grp_fu_1986_p3;
wire  signed [16:0] sext_ln105_31_fu_1753_p1;
wire  signed [16:0] sext_ln105_fu_1749_p1;
wire   [16:0] add_ln105_17_fu_1756_p2;
wire  signed [16:0] grp_fu_1995_p3;
wire  signed [17:0] sext_ln105_34_fu_1766_p1;
wire  signed [17:0] sext_ln105_32_fu_1762_p1;
wire  signed [16:0] grp_fu_2004_p3;
wire  signed [16:0] grp_fu_1942_p3;
wire  signed [17:0] sext_ln105_39_fu_1778_p1;
wire  signed [17:0] sext_ln105_37_fu_1775_p1;
wire  signed [16:0] grp_fu_1951_p3;
wire  signed [16:0] grp_fu_1960_p3;
wire  signed [17:0] sext_ln105_45_fu_1790_p1;
wire  signed [17:0] sext_ln105_43_fu_1787_p1;
wire  signed [15:0] grp_fu_1969_p3;
wire  signed [15:0] grp_fu_1977_p3;
wire  signed [16:0] sext_ln105_50_fu_1805_p1;
wire  signed [16:0] sext_ln105_49_fu_1802_p1;
wire  signed [18:0] sext_ln105_40_fu_1817_p1;
wire  signed [18:0] sext_ln105_35_fu_1814_p1;
wire  signed [16:0] grp_fu_2013_p3;
wire  signed [17:0] sext_ln105_51_fu_1832_p1;
wire  signed [17:0] sext_ln105_48_fu_1829_p1;
wire   [17:0] add_ln105_37_fu_1835_p2;
wire  signed [18:0] sext_ln105_52_fu_1841_p1;
wire  signed [18:0] sext_ln105_46_fu_1826_p1;
wire  signed [19:0] sext_ln105_53_fu_1854_p1;
wire  signed [19:0] sext_ln105_41_fu_1851_p1;
wire   [0:0] tmp_9_fu_1871_p3;
wire   [6:0] trunc_ln107_fu_1867_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 t_fu_178 = 6'd0;
#0 oc_fu_182 = 5'd0;
#0 indvar_flatten6_fu_186 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2_b1_pw_bias_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
b1_pw_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b1_pw_bias_address0),
    .ce0(b1_pw_bias_ce0_local),
    .q0(b1_pw_bias_q0)
);

cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2_b1_pw_weight_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 576 ),
    .AddressWidth( 10 ))
b1_pw_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b1_pw_weight_address0_local),
    .ce0(b1_pw_weight_ce0_local),
    .q0(b1_pw_weight_q0),
    .address1(b1_pw_weight_address1_local),
    .ce1(b1_pw_weight_ce1_local),
    .q1(b1_pw_weight_q1),
    .address2(b1_pw_weight_address2_local),
    .ce2(b1_pw_weight_ce2_local),
    .q2(b1_pw_weight_q2),
    .address3(b1_pw_weight_address3_local),
    .ce3(b1_pw_weight_ce3_local),
    .q3(b1_pw_weight_q3),
    .address4(b1_pw_weight_address4_local),
    .ce4(b1_pw_weight_ce4_local),
    .q4(b1_pw_weight_q4),
    .address5(b1_pw_weight_address5_local),
    .ce5(b1_pw_weight_ce5_local),
    .q5(b1_pw_weight_q5),
    .address6(b1_pw_weight_address6_local),
    .ce6(b1_pw_weight_ce6_local),
    .q6(b1_pw_weight_q6),
    .address7(b1_pw_weight_address7_local),
    .ce7(b1_pw_weight_ce7_local),
    .q7(b1_pw_weight_q7),
    .address8(b1_pw_weight_address8_local),
    .ce8(b1_pw_weight_ce8_local),
    .q8(b1_pw_weight_q8),
    .address9(b1_pw_weight_address9_local),
    .ce9(b1_pw_weight_ce9_local),
    .q9(b1_pw_weight_q9),
    .address10(b1_pw_weight_address10_local),
    .ce10(b1_pw_weight_ce10_local),
    .q10(b1_pw_weight_q10),
    .address11(b1_pw_weight_address11_local),
    .ce11(b1_pw_weight_ce11_local),
    .q11(b1_pw_weight_q11)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U15(
    .din0(reg_747),
    .din1(reg_717),
    .dout(mul_ln105_21_fu_1616_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U16(
    .din0(reg_757),
    .din1(reg_727),
    .dout(mul_ln105_24_fu_1622_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U17(
    .din0(reg_737),
    .din1(reg_707),
    .dout(mul_ln105_3_fu_1676_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U18(
    .din0(reg_742),
    .din1(reg_712),
    .dout(mul_ln105_6_fu_1682_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U19(
    .din0(reg_747),
    .din1(reg_717),
    .dout(mul_ln105_9_fu_1688_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U20(
    .din0(reg_757),
    .din1(reg_727),
    .dout(mul_ln105_12_fu_1694_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U21(
    .din0(reg_762),
    .din1(reg_732),
    .dout(mul_ln105_14_fu_1700_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U22(
    .din0(val_102_reg_2507),
    .din1(b1_pw_weight_load_22_reg_2457),
    .dout(mul_ln105_16_fu_1722_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U23(
    .din0(val_reg_2467),
    .din1(b1_pw_weight_load_reg_2417),
    .dout(mul_ln105_18_fu_1728_p2)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q5),
    .din1(b1_pw_weight_q5),
    .din2(mul_ln105_24_reg_2522),
    .ce(1'b1),
    .dout(grp_fu_1891_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q3),
    .din1(b1_pw_weight_q3),
    .din2(mul_ln105_3_fu_1676_p2),
    .ce(1'b1),
    .dout(grp_fu_1899_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q2),
    .din1(b1_pw_weight_q2),
    .din2(mul_ln105_6_fu_1682_p2),
    .ce(1'b1),
    .dout(grp_fu_1908_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q1),
    .din1(b1_pw_weight_q1),
    .din2(mul_ln105_9_fu_1688_p2),
    .ce(1'b1),
    .dout(grp_fu_1917_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q0),
    .din1(b1_pw_weight_q0),
    .din2(mul_ln105_12_fu_1694_p2),
    .ce(1'b1),
    .dout(grp_fu_1926_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q8),
    .din1(b1_pw_weight_q8),
    .din2(mul_ln105_21_reg_2517),
    .ce(1'b1),
    .dout(grp_fu_1934_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_762),
    .din1(reg_732),
    .din2(grp_fu_1899_p3),
    .ce(1'b1),
    .dout(grp_fu_1942_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q9),
    .din1(b1_pw_weight_q9),
    .din2(grp_fu_1908_p3),
    .ce(1'b1),
    .dout(grp_fu_1951_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q7),
    .din1(b1_pw_weight_q7),
    .din2(grp_fu_1917_p3),
    .ce(1'b1),
    .dout(grp_fu_1960_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q2),
    .din1(b1_pw_weight_q2),
    .din2(mul_ln105_14_reg_2557),
    .ce(1'b1),
    .dout(grp_fu_1969_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b1_dw_q0),
    .din1(b1_pw_weight_q0),
    .din2(mul_ln105_16_fu_1722_p2),
    .ce(1'b1),
    .dout(grp_fu_1977_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_737),
    .din1(reg_707),
    .din2(mul_ln105_18_fu_1728_p2),
    .ce(1'b1),
    .dout(grp_fu_1986_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_742),
    .din1(reg_712),
    .din2(grp_fu_1934_p3),
    .ce(1'b1),
    .dout(grp_fu_1995_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_752),
    .din1(reg_722),
    .din2(grp_fu_1891_p3),
    .ce(1'b1),
    .dout(grp_fu_2004_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_752),
    .din1(reg_722),
    .din2(add_ln105_32_reg_2602),
    .ce(1'b1),
    .dout(grp_fu_2013_p3)
);

cnn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln100_fu_785_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_186 <= add_ln100_1_fu_791_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_186 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln100_fu_785_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oc_fu_182 <= add_ln100_fu_825_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_182 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_707 <= b1_pw_weight_q10;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_707 <= b1_pw_weight_q11;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_712 <= b1_pw_weight_q8;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_712 <= b1_pw_weight_q10;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_717 <= b1_pw_weight_q6;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_717 <= b1_pw_weight_q9;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_722 <= b1_pw_weight_q5;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_722 <= b1_pw_weight_q7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_727 <= b1_pw_weight_q4;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_727 <= b1_pw_weight_q6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_732 <= b1_pw_weight_q3;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_732 <= b1_pw_weight_q4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_737 <= buf_b1_dw_q10;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_737 <= buf_b1_dw_q11;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_742 <= buf_b1_dw_q8;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_742 <= buf_b1_dw_q10;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_747 <= buf_b1_dw_q6;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_747 <= buf_b1_dw_q9;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_752 <= buf_b1_dw_q5;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_752 <= buf_b1_dw_q7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_757 <= buf_b1_dw_q4;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_757 <= buf_b1_dw_q6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_762 <= buf_b1_dw_q3;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_762 <= buf_b1_dw_q4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_fu_178 <= 6'd0;
    end else if (((icmp_ln100_reg_2043 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t_fu_178 <= add_ln101_fu_1213_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_9_reg_2642 <= acc_9_fu_1857_p2;
        add_ln100_reg_2059 <= add_ln100_fu_825_p2;
        add_ln100_reg_2059_pp0_iter1_reg <= add_ln100_reg_2059;
        add_ln100_reg_2059_pp0_iter2_reg <= add_ln100_reg_2059_pp0_iter1_reg;
        add_ln105_20_reg_2607 <= add_ln105_20_fu_1769_p2;
        add_ln105_25_reg_2612 <= add_ln105_25_fu_1781_p2;
        add_ln105_31_reg_2617 <= add_ln105_31_fu_1793_p2;
        add_ln105_36_reg_2627 <= add_ln105_36_fu_1808_p2;
        add_ln109_reg_2412 <= add_ln109_fu_1531_p2;
        add_ln109_reg_2412_pp0_iter2_reg <= add_ln109_reg_2412;
        add_ln109_reg_2412_pp0_iter3_reg <= add_ln109_reg_2412_pp0_iter2_reg;
        add_ln109_reg_2412_pp0_iter4_reg <= add_ln109_reg_2412_pp0_iter3_reg;
        add_ln109_reg_2412_pp0_iter5_reg <= add_ln109_reg_2412_pp0_iter4_reg;
        add_ln109_reg_2412_pp0_iter6_reg <= add_ln109_reg_2412_pp0_iter5_reg;
        add_ln109_reg_2412_pp0_iter7_reg <= add_ln109_reg_2412_pp0_iter6_reg;
        icmp_ln100_reg_2043 <= icmp_ln100_fu_785_p2;
        mul_ln105_14_reg_2557 <= mul_ln105_14_fu_1700_p2;
        select_ln100_reg_2047 <= select_ln100_fu_809_p3;
        select_ln108_reg_2652 <= select_ln108_fu_1879_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln105_26_reg_2632 <= add_ln105_26_fu_1820_p2;
        add_ln105_38_reg_2637 <= add_ln105_38_fu_1845_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        mul_ln105_21_reg_2517 <= mul_ln105_21_fu_1616_p2;
        mul_ln105_24_reg_2522 <= mul_ln105_24_fu_1622_p2;
        sub_ln105_reg_2068[9 : 3] <= sub_ln105_fu_859_p2[9 : 3];
        zext_ln101_1_reg_2144[5 : 0] <= zext_ln101_1_fu_1053_p1[5 : 0];
        zext_ln101_2_reg_2155[5 : 0] <= zext_ln101_2_fu_1056_p1[5 : 0];
        zext_ln101_4_reg_2162[5 : 0] <= zext_ln101_4_fu_1062_p1[5 : 0];
        zext_ln101_5_reg_2167[5 : 0] <= zext_ln101_5_fu_1065_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln105_32_reg_2602 <= grp_fu_1926_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_load_22_reg_2457 <= b1_pw_weight_q1;
        b1_pw_weight_load_reg_2417 <= b1_pw_weight_q11;
        val_102_reg_2507 <= buf_b1_dw_q1;
        val_reg_2467 <= buf_b1_dw_q11;
    end
end

always @ (*) begin
    if (((icmp_ln100_reg_2043 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_186;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oc_load = 5'd0;
    end else begin
        ap_sig_allocacmp_oc_load = oc_fu_182;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 6'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_178;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_bias_ce0_local = 1'b1;
    end else begin
        b1_pw_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address0_local = zext_ln105_22_fu_1380_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address0_local = zext_ln105_18_fu_1048_p1;
    end else begin
        b1_pw_weight_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address10_local = zext_ln105_8_fu_1264_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address10_local = zext_ln105_1_fu_906_p1;
    end else begin
        b1_pw_weight_address10_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address11_local = zext_ln109_fu_1223_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address11_local = zext_ln105_fu_883_p1;
    end else begin
        b1_pw_weight_address11_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address1_local = zext_ln105_21_fu_1370_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address1_local = zext_ln105_15_fu_1037_p1;
    end else begin
        b1_pw_weight_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address2_local = zext_ln105_20_fu_1360_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address2_local = zext_ln105_12_fu_1026_p1;
    end else begin
        b1_pw_weight_address2_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address3_local = zext_ln105_19_fu_1350_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address3_local = zext_ln105_9_fu_1015_p1;
    end else begin
        b1_pw_weight_address3_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address4_local = zext_ln105_17_fu_1336_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address4_local = zext_ln105_7_fu_1004_p1;
    end else begin
        b1_pw_weight_address4_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address5_local = zext_ln105_16_fu_1326_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address5_local = zext_ln105_6_fu_993_p1;
    end else begin
        b1_pw_weight_address5_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address6_local = zext_ln105_14_fu_1312_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address6_local = zext_ln105_5_fu_980_p1;
    end else begin
        b1_pw_weight_address6_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address7_local = zext_ln105_13_fu_1302_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address7_local = zext_ln105_4_fu_967_p1;
    end else begin
        b1_pw_weight_address7_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address8_local = zext_ln105_11_fu_1288_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address8_local = zext_ln105_3_fu_942_p1;
    end else begin
        b1_pw_weight_address8_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_weight_address9_local = zext_ln105_10_fu_1278_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b1_pw_weight_address9_local = zext_ln105_2_fu_919_p1;
    end else begin
        b1_pw_weight_address9_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce0_local = 1'b1;
    end else begin
        b1_pw_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce10_local = 1'b1;
    end else begin
        b1_pw_weight_ce10_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce11_local = 1'b1;
    end else begin
        b1_pw_weight_ce11_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce1_local = 1'b1;
    end else begin
        b1_pw_weight_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce2_local = 1'b1;
    end else begin
        b1_pw_weight_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce3_local = 1'b1;
    end else begin
        b1_pw_weight_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce4_local = 1'b1;
    end else begin
        b1_pw_weight_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce5_local = 1'b1;
    end else begin
        b1_pw_weight_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce6_local = 1'b1;
    end else begin
        b1_pw_weight_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce7_local = 1'b1;
    end else begin
        b1_pw_weight_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce8_local = 1'b1;
    end else begin
        b1_pw_weight_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b1_pw_weight_ce9_local = 1'b1;
    end else begin
        b1_pw_weight_ce9_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address0_local = zext_ln104_22_fu_1526_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address0_local = zext_ln104_18_fu_1208_p1;
    end else begin
        buf_b1_dw_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address10_local = zext_ln104_8_fu_1402_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address10_local = zext_ln104_1_fu_1085_p1;
    end else begin
        buf_b1_dw_address10_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address11_local = zext_ln101_fu_1385_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address11_local = zext_ln104_fu_1074_p1;
    end else begin
        buf_b1_dw_address11_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address1_local = zext_ln104_21_fu_1516_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address1_local = zext_ln104_50_fu_1197_p1;
    end else begin
        buf_b1_dw_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address2_local = zext_ln104_20_fu_1506_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address2_local = zext_ln104_47_fu_1181_p1;
    end else begin
        buf_b1_dw_address2_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address3_local = zext_ln104_19_fu_1496_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address3_local = zext_ln104_9_fu_1166_p1;
    end else begin
        buf_b1_dw_address3_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address4_local = zext_ln104_17_fu_1482_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address4_local = zext_ln104_7_fu_1155_p1;
    end else begin
        buf_b1_dw_address4_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address5_local = zext_ln104_16_fu_1472_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address5_local = zext_ln104_46_fu_1144_p1;
    end else begin
        buf_b1_dw_address5_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address6_local = zext_ln104_49_fu_1458_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address6_local = zext_ln104_5_fu_1129_p1;
    end else begin
        buf_b1_dw_address6_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address7_local = zext_ln104_48_fu_1444_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address7_local = zext_ln104_4_fu_1118_p1;
    end else begin
        buf_b1_dw_address7_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address8_local = zext_ln104_11_fu_1426_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address8_local = zext_ln104_3_fu_1107_p1;
    end else begin
        buf_b1_dw_address8_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b1_dw_address9_local = zext_ln104_10_fu_1416_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_dw_address9_local = zext_ln104_2_fu_1096_p1;
    end else begin
        buf_b1_dw_address9_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce0_local = 1'b1;
    end else begin
        buf_b1_dw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce10_local = 1'b1;
    end else begin
        buf_b1_dw_ce10_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce11_local = 1'b1;
    end else begin
        buf_b1_dw_ce11_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce1_local = 1'b1;
    end else begin
        buf_b1_dw_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce2_local = 1'b1;
    end else begin
        buf_b1_dw_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce3_local = 1'b1;
    end else begin
        buf_b1_dw_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce4_local = 1'b1;
    end else begin
        buf_b1_dw_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce5_local = 1'b1;
    end else begin
        buf_b1_dw_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce6_local = 1'b1;
    end else begin
        buf_b1_dw_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce7_local = 1'b1;
    end else begin
        buf_b1_dw_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce8_local = 1'b1;
    end else begin
        buf_b1_dw_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b1_dw_ce9_local = 1'b1;
    end else begin
        buf_b1_dw_ce9_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_pw_ce0_local = 1'b1;
    end else begin
        buf_b1_pw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b1_pw_we0_local = 1'b1;
    end else begin
        buf_b1_pw_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp478) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp477) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_requantize_fu_698_ap_ce = 1'b1;
    end else begin
        grp_requantize_fu_698_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_9_fu_1857_p2 = ($signed(sext_ln105_53_fu_1854_p1) + $signed(sext_ln105_41_fu_1851_p1));

assign add_ln100_1_fu_791_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 11'd1);

assign add_ln100_fu_825_p2 = (ap_sig_allocacmp_oc_load + empty_fu_817_p3);

assign add_ln101_fu_1213_p2 = (select_ln100_reg_2047 + 6'd1);

assign add_ln104_10_fu_1411_p2 = ($signed(zext_ln101_2_reg_2155) + $signed(10'd660));

assign add_ln104_11_fu_1421_p2 = ($signed(zext_ln101_2_reg_2155) + $signed(10'd720));

assign add_ln104_12_fu_1171_p2 = ($signed(zext_ln101_5_fu_1065_p1) + $signed(9'd268));

assign add_ln104_13_fu_1435_p2 = ($signed(zext_ln101_5_reg_2167) + $signed(9'd328));

assign add_ln104_14_fu_1449_p2 = ($signed(zext_ln101_4_reg_2162) + $signed(8'd132));

assign add_ln104_15_fu_1467_p2 = (zext_ln101_1_reg_2144 + 11'd1020);

assign add_ln104_16_fu_1477_p2 = ($signed(zext_ln101_1_reg_2144) + $signed(11'd1080));

assign add_ln104_17_fu_1202_p2 = ($signed(zext_ln101_1_fu_1053_p1) + $signed(11'd1140));

assign add_ln104_18_fu_1491_p2 = ($signed(zext_ln101_1_reg_2144) + $signed(11'd1200));

assign add_ln104_19_fu_1501_p2 = ($signed(zext_ln101_1_reg_2144) + $signed(11'd1260));

assign add_ln104_1_fu_1079_p2 = (zext_ln101_4_fu_1062_p1 + 8'd120);

assign add_ln104_20_fu_1511_p2 = ($signed(zext_ln101_1_reg_2144) + $signed(11'd1320));

assign add_ln104_21_fu_1521_p2 = ($signed(zext_ln101_1_reg_2144) + $signed(11'd1380));

assign add_ln104_2_fu_1090_p2 = ($signed(zext_ln101_4_fu_1062_p1) + $signed(8'd180));

assign add_ln104_3_fu_1101_p2 = (zext_ln101_5_fu_1065_p1 + 9'd240);

assign add_ln104_4_fu_1112_p2 = ($signed(zext_ln101_5_fu_1065_p1) + $signed(9'd300));

assign add_ln104_5_fu_1123_p2 = ($signed(zext_ln101_5_fu_1065_p1) + $signed(9'd360));

assign add_ln104_6_fu_1134_p2 = ($signed(zext_ln101_4_fu_1062_p1) + $signed(8'd164));

assign add_ln104_7_fu_1149_p2 = (zext_ln101_2_fu_1056_p1 + 10'd480);

assign add_ln104_8_fu_1397_p2 = ($signed(zext_ln101_2_reg_2155) + $signed(10'd540));

assign add_ln104_9_fu_1160_p2 = ($signed(zext_ln101_2_fu_1056_p1) + $signed(10'd600));

assign add_ln104_fu_1068_p2 = (zext_ln101_3_fu_1059_p1 + 7'd60);

assign add_ln105_10_fu_1331_p2 = (sub_ln105_reg_2068 + 10'd18);

assign add_ln105_11_fu_1042_p2 = (sub_ln105_fu_859_p2 + 10'd19);

assign add_ln105_12_fu_1345_p2 = (sub_ln105_reg_2068 + 10'd20);

assign add_ln105_13_fu_1355_p2 = (sub_ln105_reg_2068 + 10'd21);

assign add_ln105_14_fu_1365_p2 = (sub_ln105_reg_2068 + 10'd22);

assign add_ln105_15_fu_1375_p2 = (sub_ln105_reg_2068 + 10'd23);

assign add_ln105_17_fu_1756_p2 = ($signed(sext_ln105_31_fu_1753_p1) + $signed(sext_ln105_fu_1749_p1));

assign add_ln105_1_fu_1259_p2 = (sub_ln105_reg_2068 + 10'd9);

assign add_ln105_20_fu_1769_p2 = ($signed(sext_ln105_34_fu_1766_p1) + $signed(sext_ln105_32_fu_1762_p1));

assign add_ln105_25_fu_1781_p2 = ($signed(sext_ln105_39_fu_1778_p1) + $signed(sext_ln105_37_fu_1775_p1));

assign add_ln105_26_fu_1820_p2 = ($signed(sext_ln105_40_fu_1817_p1) + $signed(sext_ln105_35_fu_1814_p1));

assign add_ln105_2_fu_1009_p2 = (sub_ln105_fu_859_p2 + 10'd10);

assign add_ln105_31_fu_1793_p2 = ($signed(sext_ln105_45_fu_1790_p1) + $signed(sext_ln105_43_fu_1787_p1));

assign add_ln105_36_fu_1808_p2 = ($signed(sext_ln105_50_fu_1805_p1) + $signed(sext_ln105_49_fu_1802_p1));

assign add_ln105_37_fu_1835_p2 = ($signed(sext_ln105_51_fu_1832_p1) + $signed(sext_ln105_48_fu_1829_p1));

assign add_ln105_38_fu_1845_p2 = ($signed(sext_ln105_52_fu_1841_p1) + $signed(sext_ln105_46_fu_1826_p1));

assign add_ln105_3_fu_1273_p2 = (sub_ln105_reg_2068 + 10'd11);

assign add_ln105_4_fu_1283_p2 = (sub_ln105_reg_2068 + 10'd12);

assign add_ln105_5_fu_1020_p2 = (sub_ln105_fu_859_p2 + 10'd13);

assign add_ln105_6_fu_1297_p2 = (sub_ln105_reg_2068 + 10'd14);

assign add_ln105_7_fu_1307_p2 = (sub_ln105_reg_2068 + 10'd15);

assign add_ln105_8_fu_1031_p2 = (sub_ln105_fu_859_p2 + 10'd16);

assign add_ln105_9_fu_1321_p2 = (sub_ln105_reg_2068 + 10'd17);

assign add_ln105_fu_998_p2 = (sub_ln105_fu_859_p2 + 10'd8);

assign add_ln109_fu_1531_p2 = (zext_ln101_1_reg_2144 + sub_ln109_fu_1245_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp478 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp477 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp477 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign b1_pw_bias_address0 = zext_ln100_fu_1706_p1;

assign buf_b1_dw_address0 = buf_b1_dw_address0_local;

assign buf_b1_dw_address1 = buf_b1_dw_address1_local;

assign buf_b1_dw_address10 = buf_b1_dw_address10_local;

assign buf_b1_dw_address11 = buf_b1_dw_address11_local;

assign buf_b1_dw_address2 = buf_b1_dw_address2_local;

assign buf_b1_dw_address3 = buf_b1_dw_address3_local;

assign buf_b1_dw_address4 = buf_b1_dw_address4_local;

assign buf_b1_dw_address5 = buf_b1_dw_address5_local;

assign buf_b1_dw_address6 = buf_b1_dw_address6_local;

assign buf_b1_dw_address7 = buf_b1_dw_address7_local;

assign buf_b1_dw_address8 = buf_b1_dw_address8_local;

assign buf_b1_dw_address9 = buf_b1_dw_address9_local;

assign buf_b1_dw_ce0 = buf_b1_dw_ce0_local;

assign buf_b1_dw_ce1 = buf_b1_dw_ce1_local;

assign buf_b1_dw_ce10 = buf_b1_dw_ce10_local;

assign buf_b1_dw_ce11 = buf_b1_dw_ce11_local;

assign buf_b1_dw_ce2 = buf_b1_dw_ce2_local;

assign buf_b1_dw_ce3 = buf_b1_dw_ce3_local;

assign buf_b1_dw_ce4 = buf_b1_dw_ce4_local;

assign buf_b1_dw_ce5 = buf_b1_dw_ce5_local;

assign buf_b1_dw_ce6 = buf_b1_dw_ce6_local;

assign buf_b1_dw_ce7 = buf_b1_dw_ce7_local;

assign buf_b1_dw_ce8 = buf_b1_dw_ce8_local;

assign buf_b1_dw_ce9 = buf_b1_dw_ce9_local;

assign buf_b1_pw_address0 = zext_ln109_1_fu_1887_p1;

assign buf_b1_pw_ce0 = buf_b1_pw_ce0_local;

assign buf_b1_pw_d0 = select_ln108_reg_2652;

assign buf_b1_pw_we0 = buf_b1_pw_we0_local;

assign empty_fu_817_p3 = ((icmp_ln101_fu_803_p2[0:0] == 1'b1) ? 5'd1 : 5'd0);

assign grp_requantize_fu_466_p_ce = grp_requantize_fu_698_ap_ce;

assign grp_requantize_fu_466_p_din1 = sext_ln102_fu_1863_p1;

assign grp_requantize_fu_466_p_din2 = 31'd22309670;

assign grp_requantize_fu_466_p_din3 = 2'd3;

assign icmp_ln100_fu_785_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 11'd1440) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_803_p2 = ((ap_sig_allocacmp_t_load == 6'd60) ? 1'b1 : 1'b0);

assign or_ln105_1_fu_898_p3 = {{tmp_1_fu_888_p4}, {2'd2}};

assign or_ln105_2_fu_911_p3 = {{tmp_1_fu_888_p4}, {2'd3}};

assign or_ln105_3_fu_934_p3 = {{tmp_4_fu_924_p4}, {3'd4}};

assign or_ln105_4_fu_955_p5 = {{{{tmp_4_fu_924_p4}, {1'd1}}, {tmp_8_fu_947_p3}}, {1'd1}};

assign or_ln105_5_fu_972_p3 = {{tmp_4_fu_924_p4}, {3'd6}};

assign or_ln105_6_fu_985_p3 = {{tmp_4_fu_924_p4}, {3'd7}};

assign or_ln1_fu_1186_p3 = {{1'd1}, {select_ln100_reg_2047}};

assign or_ln_fu_875_p3 = {{tmp_fu_865_p4}, {1'd1}};

assign p_shl3_fu_841_p3 = {{add_ln100_reg_2059}, {5'd0}};

assign p_shl_fu_1227_p3 = {{add_ln100_reg_2059}, {6'd0}};

assign select_ln100_fu_809_p3 = ((icmp_ln101_fu_803_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_t_load);

assign select_ln108_fu_1879_p3 = ((tmp_9_fu_1871_p3[0:0] == 1'b1) ? 7'd0 : trunc_ln107_fu_1867_p1);

assign sext_ln102_fu_1863_p1 = $signed(acc_9_reg_2642);

assign sext_ln104_56_fu_1140_p1 = $signed(add_ln104_6_fu_1134_p2);

assign sext_ln104_57_fu_1177_p1 = $signed(add_ln104_12_fu_1171_p2);

assign sext_ln104_58_fu_1440_p1 = $signed(add_ln104_13_fu_1435_p2);

assign sext_ln104_59_fu_1454_p1 = $signed(add_ln104_14_fu_1449_p2);

assign sext_ln104_60_fu_1193_p1 = $signed(or_ln1_fu_1186_p3);

assign sext_ln105_31_fu_1753_p1 = grp_fu_1986_p3;

assign sext_ln105_32_fu_1762_p1 = $signed(add_ln105_17_fu_1756_p2);

assign sext_ln105_34_fu_1766_p1 = grp_fu_1995_p3;

assign sext_ln105_35_fu_1814_p1 = $signed(add_ln105_20_reg_2607);

assign sext_ln105_37_fu_1775_p1 = grp_fu_2004_p3;

assign sext_ln105_39_fu_1778_p1 = grp_fu_1942_p3;

assign sext_ln105_40_fu_1817_p1 = $signed(add_ln105_25_reg_2612);

assign sext_ln105_41_fu_1851_p1 = $signed(add_ln105_26_reg_2632);

assign sext_ln105_43_fu_1787_p1 = grp_fu_1951_p3;

assign sext_ln105_45_fu_1790_p1 = grp_fu_1960_p3;

assign sext_ln105_46_fu_1826_p1 = $signed(add_ln105_31_reg_2617);

assign sext_ln105_48_fu_1829_p1 = grp_fu_2013_p3;

assign sext_ln105_49_fu_1802_p1 = grp_fu_1969_p3;

assign sext_ln105_50_fu_1805_p1 = grp_fu_1977_p3;

assign sext_ln105_51_fu_1832_p1 = $signed(add_ln105_36_reg_2627);

assign sext_ln105_52_fu_1841_p1 = $signed(add_ln105_37_fu_1835_p2);

assign sext_ln105_53_fu_1854_p1 = $signed(add_ln105_38_reg_2637);

assign sext_ln105_fu_1749_p1 = $signed(b1_pw_bias_q0);

assign sub_ln105_fu_859_p2 = (p_shl3_fu_841_p3 - zext_ln105_47_fu_855_p1);

assign sub_ln109_fu_1245_p2 = (p_shl_fu_1227_p3 - zext_ln109_3_fu_1241_p1);

assign tmp_1_fu_888_p4 = {{sub_ln105_fu_859_p2[9:2]}};

assign tmp_4_fu_924_p4 = {{sub_ln105_fu_859_p2[9:3]}};

assign tmp_6_fu_848_p3 = {{add_ln100_reg_2059}, {3'd0}};

assign tmp_7_fu_1234_p3 = {{add_ln100_reg_2059}, {2'd0}};

assign tmp_8_fu_947_p3 = sub_ln105_fu_859_p2[32'd1];

assign tmp_9_fu_1871_p3 = grp_requantize_fu_466_p_dout0[32'd7];

assign tmp_fu_865_p4 = {{sub_ln105_fu_859_p2[9:1]}};

assign trunc_ln107_fu_1867_p1 = grp_requantize_fu_466_p_dout0[6:0];

assign zext_ln100_fu_1706_p1 = add_ln100_reg_2059_pp0_iter2_reg;

assign zext_ln101_1_fu_1053_p1 = select_ln100_reg_2047;

assign zext_ln101_2_fu_1056_p1 = select_ln100_reg_2047;

assign zext_ln101_3_fu_1059_p1 = select_ln100_reg_2047;

assign zext_ln101_4_fu_1062_p1 = select_ln100_reg_2047;

assign zext_ln101_5_fu_1065_p1 = select_ln100_reg_2047;

assign zext_ln101_fu_1385_p1 = select_ln100_reg_2047;

assign zext_ln104_10_fu_1416_p1 = add_ln104_10_fu_1411_p2;

assign zext_ln104_11_fu_1426_p1 = add_ln104_11_fu_1421_p2;

assign zext_ln104_16_fu_1472_p1 = add_ln104_15_fu_1467_p2;

assign zext_ln104_17_fu_1482_p1 = add_ln104_16_fu_1477_p2;

assign zext_ln104_18_fu_1208_p1 = add_ln104_17_fu_1202_p2;

assign zext_ln104_19_fu_1496_p1 = add_ln104_18_fu_1491_p2;

assign zext_ln104_1_fu_1085_p1 = add_ln104_1_fu_1079_p2;

assign zext_ln104_20_fu_1506_p1 = add_ln104_19_fu_1501_p2;

assign zext_ln104_21_fu_1516_p1 = add_ln104_20_fu_1511_p2;

assign zext_ln104_22_fu_1526_p1 = add_ln104_21_fu_1521_p2;

assign zext_ln104_2_fu_1096_p1 = add_ln104_2_fu_1090_p2;

assign zext_ln104_3_fu_1107_p1 = add_ln104_3_fu_1101_p2;

assign zext_ln104_46_fu_1144_p1 = $unsigned(sext_ln104_56_fu_1140_p1);

assign zext_ln104_47_fu_1181_p1 = $unsigned(sext_ln104_57_fu_1177_p1);

assign zext_ln104_48_fu_1444_p1 = $unsigned(sext_ln104_58_fu_1440_p1);

assign zext_ln104_49_fu_1458_p1 = $unsigned(sext_ln104_59_fu_1454_p1);

assign zext_ln104_4_fu_1118_p1 = add_ln104_4_fu_1112_p2;

assign zext_ln104_50_fu_1197_p1 = $unsigned(sext_ln104_60_fu_1193_p1);

assign zext_ln104_5_fu_1129_p1 = add_ln104_5_fu_1123_p2;

assign zext_ln104_7_fu_1155_p1 = add_ln104_7_fu_1149_p2;

assign zext_ln104_8_fu_1402_p1 = add_ln104_8_fu_1397_p2;

assign zext_ln104_9_fu_1166_p1 = add_ln104_9_fu_1160_p2;

assign zext_ln104_fu_1074_p1 = add_ln104_fu_1068_p2;

assign zext_ln105_10_fu_1278_p1 = add_ln105_3_fu_1273_p2;

assign zext_ln105_11_fu_1288_p1 = add_ln105_4_fu_1283_p2;

assign zext_ln105_12_fu_1026_p1 = add_ln105_5_fu_1020_p2;

assign zext_ln105_13_fu_1302_p1 = add_ln105_6_fu_1297_p2;

assign zext_ln105_14_fu_1312_p1 = add_ln105_7_fu_1307_p2;

assign zext_ln105_15_fu_1037_p1 = add_ln105_8_fu_1031_p2;

assign zext_ln105_16_fu_1326_p1 = add_ln105_9_fu_1321_p2;

assign zext_ln105_17_fu_1336_p1 = add_ln105_10_fu_1331_p2;

assign zext_ln105_18_fu_1048_p1 = add_ln105_11_fu_1042_p2;

assign zext_ln105_19_fu_1350_p1 = add_ln105_12_fu_1345_p2;

assign zext_ln105_1_fu_906_p1 = or_ln105_1_fu_898_p3;

assign zext_ln105_20_fu_1360_p1 = add_ln105_13_fu_1355_p2;

assign zext_ln105_21_fu_1370_p1 = add_ln105_14_fu_1365_p2;

assign zext_ln105_22_fu_1380_p1 = add_ln105_15_fu_1375_p2;

assign zext_ln105_2_fu_919_p1 = or_ln105_2_fu_911_p3;

assign zext_ln105_3_fu_942_p1 = or_ln105_3_fu_934_p3;

assign zext_ln105_47_fu_855_p1 = tmp_6_fu_848_p3;

assign zext_ln105_4_fu_967_p1 = or_ln105_4_fu_955_p5;

assign zext_ln105_5_fu_980_p1 = or_ln105_5_fu_972_p3;

assign zext_ln105_6_fu_993_p1 = or_ln105_6_fu_985_p3;

assign zext_ln105_7_fu_1004_p1 = add_ln105_fu_998_p2;

assign zext_ln105_8_fu_1264_p1 = add_ln105_1_fu_1259_p2;

assign zext_ln105_9_fu_1015_p1 = add_ln105_2_fu_1009_p2;

assign zext_ln105_fu_883_p1 = or_ln_fu_875_p3;

assign zext_ln109_1_fu_1887_p1 = add_ln109_reg_2412_pp0_iter7_reg;

assign zext_ln109_3_fu_1241_p1 = tmp_7_fu_1234_p3;

assign zext_ln109_fu_1223_p1 = sub_ln105_reg_2068;

always @ (posedge ap_clk) begin
    sub_ln105_reg_2068[2:0] <= 3'b000;
    zext_ln101_1_reg_2144[10:6] <= 5'b00000;
    zext_ln101_2_reg_2155[9:6] <= 4'b0000;
    zext_ln101_4_reg_2162[7:6] <= 2'b00;
    zext_ln101_5_reg_2167[8:6] <= 3'b000;
end

endmodule //cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2
