// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_25 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_b3_dw_address0,
        buf_b3_dw_ce0,
        buf_b3_dw_q0,
        buf_b3_dw_address1,
        buf_b3_dw_ce1,
        buf_b3_dw_q1,
        buf_b3_dw_address2,
        buf_b3_dw_ce2,
        buf_b3_dw_q2,
        buf_b3_dw_address3,
        buf_b3_dw_ce3,
        buf_b3_dw_q3,
        buf_b3_dw_address4,
        buf_b3_dw_ce4,
        buf_b3_dw_q4,
        buf_b3_dw_address5,
        buf_b3_dw_ce5,
        buf_b3_dw_q5,
        buf_b3_dw_address6,
        buf_b3_dw_ce6,
        buf_b3_dw_q6,
        buf_b3_dw_address7,
        buf_b3_dw_ce7,
        buf_b3_dw_q7,
        buf_b3_dw_address8,
        buf_b3_dw_ce8,
        buf_b3_dw_q8,
        buf_b3_dw_address9,
        buf_b3_dw_ce9,
        buf_b3_dw_q9,
        buf_b3_dw_address10,
        buf_b3_dw_ce10,
        buf_b3_dw_q10,
        buf_b3_dw_address11,
        buf_b3_dw_ce11,
        buf_b3_dw_q11,
        buf_b3_dw_address12,
        buf_b3_dw_ce12,
        buf_b3_dw_q12,
        buf_b3_dw_address13,
        buf_b3_dw_ce13,
        buf_b3_dw_q13,
        buf_b3_dw_address14,
        buf_b3_dw_ce14,
        buf_b3_dw_q14,
        buf_b3_dw_address15,
        buf_b3_dw_ce15,
        buf_b3_dw_q15,
        buf_b3_pw_address0,
        buf_b3_pw_ce0,
        buf_b3_pw_we0,
        buf_b3_pw_d0,
        grp_requantize_fu_466_p_din1,
        grp_requantize_fu_466_p_din2,
        grp_requantize_fu_466_p_din3,
        grp_requantize_fu_466_p_dout0,
        grp_requantize_fu_466_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] buf_b3_dw_address0;
output   buf_b3_dw_ce0;
input  [7:0] buf_b3_dw_q0;
output  [8:0] buf_b3_dw_address1;
output   buf_b3_dw_ce1;
input  [7:0] buf_b3_dw_q1;
output  [8:0] buf_b3_dw_address2;
output   buf_b3_dw_ce2;
input  [7:0] buf_b3_dw_q2;
output  [8:0] buf_b3_dw_address3;
output   buf_b3_dw_ce3;
input  [7:0] buf_b3_dw_q3;
output  [8:0] buf_b3_dw_address4;
output   buf_b3_dw_ce4;
input  [7:0] buf_b3_dw_q4;
output  [8:0] buf_b3_dw_address5;
output   buf_b3_dw_ce5;
input  [7:0] buf_b3_dw_q5;
output  [8:0] buf_b3_dw_address6;
output   buf_b3_dw_ce6;
input  [7:0] buf_b3_dw_q6;
output  [8:0] buf_b3_dw_address7;
output   buf_b3_dw_ce7;
input  [7:0] buf_b3_dw_q7;
output  [8:0] buf_b3_dw_address8;
output   buf_b3_dw_ce8;
input  [7:0] buf_b3_dw_q8;
output  [8:0] buf_b3_dw_address9;
output   buf_b3_dw_ce9;
input  [7:0] buf_b3_dw_q9;
output  [8:0] buf_b3_dw_address10;
output   buf_b3_dw_ce10;
input  [7:0] buf_b3_dw_q10;
output  [8:0] buf_b3_dw_address11;
output   buf_b3_dw_ce11;
input  [7:0] buf_b3_dw_q11;
output  [8:0] buf_b3_dw_address12;
output   buf_b3_dw_ce12;
input  [7:0] buf_b3_dw_q12;
output  [8:0] buf_b3_dw_address13;
output   buf_b3_dw_ce13;
input  [7:0] buf_b3_dw_q13;
output  [8:0] buf_b3_dw_address14;
output   buf_b3_dw_ce14;
input  [7:0] buf_b3_dw_q14;
output  [8:0] buf_b3_dw_address15;
output   buf_b3_dw_ce15;
input  [7:0] buf_b3_dw_q15;
output  [9:0] buf_b3_pw_address0;
output   buf_b3_pw_ce0;
output   buf_b3_pw_we0;
output  [6:0] buf_b3_pw_d0;
output  [22:0] grp_requantize_fu_466_p_din1;
output  [30:0] grp_requantize_fu_466_p_din2;
output  [1:0] grp_requantize_fu_466_p_din3;
input  [7:0] grp_requantize_fu_466_p_dout0;
output   grp_requantize_fu_466_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln100_reg_2578;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] b3_pw_bias_address0;
wire  signed [12:0] b3_pw_bias_q0;
wire  signed [7:0] b3_pw_weight_q0;
wire  signed [7:0] b3_pw_weight_q1;
wire   [7:0] b3_pw_weight_q2;
wire   [7:0] b3_pw_weight_q3;
wire   [7:0] b3_pw_weight_q4;
wire   [7:0] b3_pw_weight_q5;
wire   [7:0] b3_pw_weight_q6;
wire   [7:0] b3_pw_weight_q7;
wire  signed [7:0] b3_pw_weight_q8;
wire  signed [7:0] b3_pw_weight_q9;
wire  signed [7:0] b3_pw_weight_q10;
wire  signed [7:0] b3_pw_weight_q11;
wire  signed [7:0] b3_pw_weight_q12;
wire  signed [7:0] b3_pw_weight_q13;
wire  signed [7:0] b3_pw_weight_q14;
wire  signed [7:0] b3_pw_weight_q15;
reg  signed [7:0] reg_873;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
reg  signed [7:0] reg_878;
reg  signed [7:0] reg_883;
reg  signed [7:0] reg_888;
reg  signed [7:0] reg_893;
reg  signed [7:0] reg_898;
reg  signed [7:0] reg_903;
reg  signed [7:0] reg_908;
reg  signed [7:0] reg_913;
reg  signed [7:0] reg_918;
reg  signed [7:0] reg_923;
reg  signed [7:0] reg_928;
reg  signed [7:0] reg_933;
reg  signed [7:0] reg_938;
wire   [0:0] icmp_ln100_fu_961_p2;
reg   [3:0] t_load_reg_2582;
wire   [0:0] icmp_ln101_fu_976_p2;
reg   [0:0] icmp_ln101_reg_2587;
wire   [3:0] select_ln100_fu_990_p3;
reg   [3:0] select_ln100_reg_2593;
wire   [6:0] add_ln100_1_fu_1003_p2;
reg   [6:0] add_ln100_1_reg_2599;
wire   [5:0] trunc_ln105_fu_1009_p1;
reg   [5:0] trunc_ln105_reg_2605;
wire   [8:0] zext_ln101_2_fu_1226_p1;
reg   [8:0] zext_ln101_2_reg_2706;
wire   [6:0] zext_ln101_3_fu_1230_p1;
reg   [6:0] zext_ln101_3_reg_2715;
wire   [7:0] zext_ln101_4_fu_1234_p1;
reg   [7:0] zext_ln101_4_reg_2722;
wire   [5:0] zext_ln101_6_fu_1238_p1;
reg   [5:0] zext_ln101_6_reg_2730;
wire   [9:0] add_ln109_fu_1916_p2;
reg   [9:0] add_ln109_reg_3067;
reg   [9:0] add_ln109_reg_3067_pp0_iter2_reg;
reg   [9:0] add_ln109_reg_3067_pp0_iter3_reg;
reg   [9:0] add_ln109_reg_3067_pp0_iter4_reg;
reg   [9:0] add_ln109_reg_3067_pp0_iter5_reg;
reg   [9:0] add_ln109_reg_3067_pp0_iter6_reg;
reg  signed [7:0] b3_pw_weight_load_15_reg_3077;
reg  signed [7:0] b3_pw_weight_load_17_reg_3087;
reg  signed [7:0] b3_pw_weight_load_19_reg_3097;
reg  signed [7:0] b3_pw_weight_load_21_reg_3107;
reg  signed [7:0] b3_pw_weight_load_23_reg_3117;
reg  signed [7:0] b3_pw_weight_load_25_reg_3127;
reg  signed [7:0] b3_pw_weight_load_27_reg_3137;
reg  signed [7:0] b3_pw_weight_load_30_reg_3152;
reg  signed [7:0] val_36_reg_3157;
reg  signed [7:0] val_38_reg_3167;
reg  signed [7:0] val_40_reg_3177;
reg  signed [7:0] val_42_reg_3187;
reg  signed [7:0] val_44_reg_3197;
reg  signed [7:0] val_46_reg_3207;
reg  signed [7:0] val_48_reg_3217;
reg  signed [7:0] val_51_reg_3232;
wire  signed [15:0] mul_ln105_2_fu_2056_p2;
wire  signed [15:0] mul_ln105_4_fu_2062_p2;
wire  signed [15:0] mul_ln105_6_fu_2068_p2;
wire  signed [15:0] mul_ln105_8_fu_2074_p2;
wire  signed [15:0] mul_ln105_10_fu_2080_p2;
wire  signed [15:0] mul_ln105_12_fu_2086_p2;
wire  signed [15:0] mul_ln105_14_fu_2092_p2;
wire  signed [15:0] mul_ln105_31_fu_2098_p2;
wire  signed [15:0] mul_ln105_16_fu_2146_p2;
wire  signed [15:0] mul_ln105_18_fu_2152_p2;
wire  signed [15:0] mul_ln105_20_fu_2158_p2;
wire  signed [15:0] mul_ln105_22_fu_2164_p2;
wire  signed [15:0] mul_ln105_24_fu_2170_p2;
wire  signed [15:0] mul_ln105_26_fu_2176_p2;
wire  signed [15:0] mul_ln105_28_fu_2182_p2;
wire   [17:0] add_ln105_6_fu_2220_p2;
reg   [17:0] add_ln105_6_reg_3317;
wire   [17:0] add_ln105_13_fu_2258_p2;
reg   [17:0] add_ln105_13_reg_3322;
wire   [18:0] add_ln105_14_fu_2273_p2;
reg   [18:0] add_ln105_14_reg_3332;
wire   [17:0] add_ln105_21_fu_2311_p2;
reg   [17:0] add_ln105_21_reg_3337;
wire   [18:0] add_ln105_29_fu_2349_p2;
reg   [18:0] add_ln105_29_reg_3342;
wire   [19:0] acc_7_fu_2370_p2;
reg   [19:0] acc_7_reg_3347;
wire  signed [22:0] sext_ln102_fu_2376_p1;
wire   [6:0] select_ln108_fu_2392_p3;
reg   [6:0] select_ln108_reg_3357;
wire    ap_block_pp0_stage0_subdone;
reg    grp_requantize_fu_864_ap_ce;
wire    ap_block_pp0_stage1_11001_ignoreCallOp597;
wire    ap_block_pp0_stage0_11001_ignoreCallOp596;
wire    ap_block_pp0_stage0_ignoreCallOp596;
wire   [63:0] zext_ln109_fu_1021_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln105_1_fu_1034_p1;
wire   [63:0] zext_ln105_3_fu_1047_p1;
wire   [63:0] zext_ln105_5_fu_1060_p1;
wire   [63:0] zext_ln105_7_fu_1073_p1;
wire   [63:0] zext_ln105_9_fu_1086_p1;
wire   [63:0] zext_ln105_11_fu_1099_p1;
wire   [63:0] zext_ln105_13_fu_1112_p1;
wire   [63:0] zext_ln105_15_fu_1125_p1;
wire   [63:0] zext_ln105_17_fu_1138_p1;
wire   [63:0] zext_ln105_19_fu_1151_p1;
wire   [63:0] zext_ln105_21_fu_1164_p1;
wire   [63:0] zext_ln105_23_fu_1177_p1;
wire   [63:0] zext_ln105_25_fu_1190_p1;
wire   [63:0] zext_ln105_27_fu_1203_p1;
wire   [63:0] zext_ln105_30_fu_1216_p1;
wire   [63:0] zext_ln101_fu_1221_p1;
wire   [63:0] zext_ln104_1_fu_1248_p1;
wire   [63:0] zext_ln104_3_fu_1259_p1;
wire   [63:0] zext_ln104_5_fu_1270_p1;
wire   [63:0] zext_ln104_7_fu_1281_p1;
wire   [63:0] zext_ln104_9_fu_1292_p1;
wire   [63:0] zext_ln104_11_fu_1303_p1;
wire   [63:0] zext_ln104_13_fu_1318_p1;
wire   [63:0] zext_ln104_15_fu_1335_p1;
wire   [63:0] zext_ln104_17_fu_1346_p1;
wire   [63:0] zext_ln104_19_fu_1357_p1;
wire   [63:0] zext_ln104_21_fu_1368_p1;
wire   [63:0] zext_ln104_23_fu_1379_p1;
wire   [63:0] zext_ln104_25_fu_1394_p1;
wire   [63:0] zext_ln104_27_fu_1409_p1;
wire   [63:0] zext_ln104_30_fu_1424_p1;
wire   [63:0] zext_ln105_fu_1472_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln105_2_fu_1488_p1;
wire   [63:0] zext_ln105_4_fu_1504_p1;
wire   [63:0] zext_ln105_6_fu_1520_p1;
wire   [63:0] zext_ln105_8_fu_1536_p1;
wire   [63:0] zext_ln105_10_fu_1552_p1;
wire   [63:0] zext_ln105_12_fu_1568_p1;
wire   [63:0] zext_ln105_14_fu_1584_p1;
wire   [63:0] zext_ln105_16_fu_1596_p1;
wire   [63:0] zext_ln105_18_fu_1608_p1;
wire   [63:0] zext_ln105_20_fu_1620_p1;
wire   [63:0] zext_ln105_22_fu_1632_p1;
wire   [63:0] zext_ln105_24_fu_1644_p1;
wire   [63:0] zext_ln105_26_fu_1656_p1;
wire   [63:0] zext_ln105_28_fu_1668_p1;
wire   [63:0] zext_ln105_29_fu_1680_p1;
wire   [63:0] zext_ln104_fu_1705_p1;
wire   [63:0] zext_ln104_2_fu_1719_p1;
wire   [63:0] zext_ln104_4_fu_1733_p1;
wire   [63:0] zext_ln104_6_fu_1751_p1;
wire   [63:0] zext_ln104_8_fu_1765_p1;
wire   [63:0] zext_ln104_10_fu_1779_p1;
wire   [63:0] zext_ln104_12_fu_1797_p1;
wire   [63:0] zext_ln104_14_fu_1815_p1;
wire   [63:0] zext_ln104_16_fu_1825_p1;
wire   [63:0] zext_ln104_18_fu_1835_p1;
wire   [63:0] zext_ln104_20_fu_1845_p1;
wire   [63:0] zext_ln104_22_fu_1855_p1;
wire   [63:0] zext_ln104_24_fu_1865_p1;
wire   [63:0] zext_ln104_26_fu_1879_p1;
wire   [63:0] zext_ln104_28_fu_1893_p1;
wire   [63:0] zext_ln104_29_fu_1907_p1;
wire   [63:0] zext_ln100_fu_1922_p1;
wire   [63:0] zext_ln109_2_fu_2400_p1;
reg   [3:0] t_fu_184;
wire   [3:0] add_ln101_fu_1429_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_t_load;
reg   [6:0] oc_fu_188;
reg   [9:0] indvar_flatten48_fu_192;
wire   [9:0] add_ln100_fu_967_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten48_load;
reg    b3_pw_weight_ce15_local;
reg   [10:0] b3_pw_weight_address15_local;
reg    b3_pw_weight_ce14_local;
reg   [10:0] b3_pw_weight_address14_local;
reg    b3_pw_weight_ce13_local;
reg   [10:0] b3_pw_weight_address13_local;
reg    b3_pw_weight_ce12_local;
reg   [10:0] b3_pw_weight_address12_local;
reg    b3_pw_weight_ce11_local;
reg   [10:0] b3_pw_weight_address11_local;
reg    b3_pw_weight_ce10_local;
reg   [10:0] b3_pw_weight_address10_local;
reg    b3_pw_weight_ce9_local;
reg   [10:0] b3_pw_weight_address9_local;
reg    b3_pw_weight_ce8_local;
reg   [10:0] b3_pw_weight_address8_local;
reg    b3_pw_weight_ce7_local;
reg   [10:0] b3_pw_weight_address7_local;
reg    b3_pw_weight_ce6_local;
reg   [10:0] b3_pw_weight_address6_local;
reg    b3_pw_weight_ce5_local;
reg   [10:0] b3_pw_weight_address5_local;
reg    b3_pw_weight_ce4_local;
reg   [10:0] b3_pw_weight_address4_local;
reg    b3_pw_weight_ce3_local;
reg   [10:0] b3_pw_weight_address3_local;
reg    b3_pw_weight_ce2_local;
reg   [10:0] b3_pw_weight_address2_local;
reg    b3_pw_weight_ce1_local;
reg   [10:0] b3_pw_weight_address1_local;
reg    b3_pw_weight_ce0_local;
reg   [10:0] b3_pw_weight_address0_local;
reg    buf_b3_dw_ce15_local;
reg   [8:0] buf_b3_dw_address15_local;
reg    buf_b3_dw_ce14_local;
reg   [8:0] buf_b3_dw_address14_local;
reg    buf_b3_dw_ce13_local;
reg   [8:0] buf_b3_dw_address13_local;
reg    buf_b3_dw_ce12_local;
reg   [8:0] buf_b3_dw_address12_local;
reg    buf_b3_dw_ce11_local;
reg   [8:0] buf_b3_dw_address11_local;
reg    buf_b3_dw_ce10_local;
reg   [8:0] buf_b3_dw_address10_local;
reg    buf_b3_dw_ce9_local;
reg   [8:0] buf_b3_dw_address9_local;
reg    buf_b3_dw_ce8_local;
reg   [8:0] buf_b3_dw_address8_local;
reg    buf_b3_dw_ce7_local;
reg   [8:0] buf_b3_dw_address7_local;
reg    buf_b3_dw_ce6_local;
reg   [8:0] buf_b3_dw_address6_local;
reg    buf_b3_dw_ce5_local;
reg   [8:0] buf_b3_dw_address5_local;
reg    buf_b3_dw_ce4_local;
reg   [8:0] buf_b3_dw_address4_local;
reg    buf_b3_dw_ce3_local;
reg   [8:0] buf_b3_dw_address3_local;
reg    buf_b3_dw_ce2_local;
reg   [8:0] buf_b3_dw_address2_local;
reg    buf_b3_dw_ce1_local;
reg   [8:0] buf_b3_dw_address1_local;
reg    buf_b3_dw_ce0_local;
reg   [8:0] buf_b3_dw_address0_local;
reg    b3_pw_bias_ce0_local;
reg    buf_b3_pw_we0_local;
reg    buf_b3_pw_ce0_local;
wire   [6:0] empty_fu_996_p3;
wire   [10:0] shl_ln1_fu_1013_p3;
wire   [10:0] or_ln105_1_fu_1026_p3;
wire   [10:0] or_ln105_3_fu_1039_p3;
wire   [10:0] or_ln105_5_fu_1052_p3;
wire   [10:0] or_ln105_7_fu_1065_p3;
wire   [10:0] or_ln105_9_fu_1078_p3;
wire   [10:0] or_ln105_11_fu_1091_p3;
wire   [10:0] or_ln105_13_fu_1104_p3;
wire   [10:0] or_ln105_15_fu_1117_p3;
wire   [10:0] or_ln105_17_fu_1130_p3;
wire   [10:0] or_ln105_19_fu_1143_p3;
wire   [10:0] or_ln105_21_fu_1156_p3;
wire   [10:0] or_ln105_23_fu_1169_p3;
wire   [10:0] or_ln105_25_fu_1182_p3;
wire   [10:0] or_ln105_27_fu_1195_p3;
wire   [10:0] or_ln105_30_fu_1208_p3;
wire   [5:0] add_ln104_1_fu_1242_p2;
wire   [6:0] add_ln104_3_fu_1253_p2;
wire   [6:0] add_ln104_5_fu_1264_p2;
wire   [7:0] add_ln104_7_fu_1275_p2;
wire   [7:0] add_ln104_9_fu_1286_p2;
wire   [7:0] add_ln104_11_fu_1297_p2;
wire   [6:0] add_ln104_13_fu_1308_p2;
wire  signed [7:0] sext_ln104_16_fu_1314_p1;
wire   [4:0] or_ln104_2_fu_1323_p3;
wire  signed [7:0] sext_ln104_20_fu_1331_p1;
wire   [8:0] add_ln104_16_fu_1340_p2;
wire   [8:0] add_ln104_18_fu_1351_p2;
wire   [8:0] add_ln104_20_fu_1362_p2;
wire   [8:0] add_ln104_22_fu_1373_p2;
wire   [7:0] add_ln104_24_fu_1384_p2;
wire  signed [8:0] sext_ln104_31_fu_1390_p1;
wire   [7:0] add_ln104_26_fu_1399_p2;
wire  signed [8:0] sext_ln104_35_fu_1405_p1;
wire   [6:0] add_ln104_29_fu_1414_p2;
wire  signed [8:0] sext_ln104_41_fu_1420_p1;
wire   [9:0] p_shl_fu_1448_p3;
wire   [9:0] zext_ln109_1_fu_1445_p1;
wire   [10:0] or_ln105_s_fu_1465_p3;
wire   [10:0] or_ln105_2_fu_1481_p3;
wire   [10:0] or_ln105_4_fu_1497_p3;
wire   [10:0] or_ln105_6_fu_1513_p3;
wire   [10:0] or_ln105_8_fu_1529_p3;
wire   [10:0] or_ln105_10_fu_1545_p3;
wire   [10:0] or_ln105_12_fu_1561_p3;
wire   [10:0] or_ln105_14_fu_1577_p3;
wire   [10:0] or_ln105_16_fu_1589_p3;
wire   [10:0] or_ln105_18_fu_1601_p3;
wire   [10:0] or_ln105_20_fu_1613_p3;
wire   [10:0] or_ln105_22_fu_1625_p3;
wire   [10:0] or_ln105_24_fu_1637_p3;
wire   [10:0] or_ln105_26_fu_1649_p3;
wire   [10:0] or_ln105_28_fu_1661_p3;
wire   [10:0] or_ln105_29_fu_1673_p3;
wire   [4:0] zext_ln101_5_fu_1692_p1;
wire   [4:0] add_ln104_fu_1699_p2;
wire   [5:0] add_ln104_2_fu_1714_p2;
wire   [6:0] add_ln104_4_fu_1728_p2;
wire   [5:0] add_ln104_6_fu_1742_p2;
wire  signed [6:0] sext_ln104_7_fu_1747_p1;
wire   [7:0] add_ln104_8_fu_1760_p2;
wire   [7:0] add_ln104_10_fu_1774_p2;
wire   [6:0] add_ln104_12_fu_1788_p2;
wire  signed [7:0] sext_ln104_14_fu_1793_p1;
wire   [5:0] add_ln104_14_fu_1806_p2;
wire  signed [7:0] sext_ln104_18_fu_1811_p1;
wire   [8:0] add_ln104_15_fu_1820_p2;
wire   [8:0] add_ln104_17_fu_1830_p2;
wire   [8:0] add_ln104_19_fu_1840_p2;
wire   [8:0] add_ln104_21_fu_1850_p2;
wire   [8:0] add_ln104_23_fu_1860_p2;
wire   [7:0] add_ln104_25_fu_1870_p2;
wire  signed [8:0] sext_ln104_33_fu_1875_p1;
wire   [7:0] add_ln104_27_fu_1884_p2;
wire  signed [8:0] sext_ln104_37_fu_1889_p1;
wire   [6:0] add_ln104_28_fu_1898_p2;
wire  signed [8:0] sext_ln104_39_fu_1903_p1;
wire   [9:0] zext_ln101_1_fu_1689_p1;
wire   [9:0] sub_ln105_fu_1455_p2;
wire  signed [15:0] grp_fu_2413_p3;
wire  signed [15:0] grp_fu_2422_p3;
wire  signed [16:0] sext_ln105_35_fu_2191_p1;
wire  signed [16:0] sext_ln105_34_fu_2188_p1;
wire   [16:0] add_ln105_2_fu_2194_p2;
wire  signed [15:0] grp_fu_2431_p3;
wire  signed [15:0] grp_fu_2440_p3;
wire  signed [16:0] sext_ln105_38_fu_2207_p1;
wire  signed [16:0] sext_ln105_37_fu_2204_p1;
wire   [16:0] add_ln105_5_fu_2210_p2;
wire  signed [17:0] sext_ln105_39_fu_2216_p1;
wire  signed [17:0] sext_ln105_36_fu_2200_p1;
wire  signed [15:0] grp_fu_2449_p3;
wire  signed [15:0] grp_fu_2458_p3;
wire  signed [16:0] sext_ln105_42_fu_2229_p1;
wire  signed [16:0] sext_ln105_41_fu_2226_p1;
wire   [16:0] add_ln105_9_fu_2232_p2;
wire  signed [15:0] grp_fu_2467_p3;
wire  signed [15:0] grp_fu_2476_p3;
wire  signed [16:0] sext_ln105_45_fu_2245_p1;
wire  signed [16:0] sext_ln105_44_fu_2242_p1;
wire   [16:0] add_ln105_12_fu_2248_p2;
wire  signed [17:0] sext_ln105_46_fu_2254_p1;
wire  signed [17:0] sext_ln105_43_fu_2238_p1;
wire  signed [15:0] grp_fu_2404_p3;
wire  signed [18:0] sext_ln105_47_fu_2270_p1;
wire  signed [18:0] sext_ln105_40_fu_2267_p1;
wire  signed [15:0] grp_fu_2485_p3;
wire  signed [15:0] grp_fu_2494_p3;
wire  signed [16:0] sext_ln105_50_fu_2282_p1;
wire  signed [16:0] sext_ln105_49_fu_2279_p1;
wire   [16:0] add_ln105_17_fu_2285_p2;
wire  signed [15:0] grp_fu_2503_p3;
wire  signed [15:0] grp_fu_2512_p3;
wire  signed [16:0] sext_ln105_53_fu_2298_p1;
wire  signed [16:0] sext_ln105_52_fu_2295_p1;
wire   [16:0] add_ln105_20_fu_2301_p2;
wire  signed [17:0] sext_ln105_54_fu_2307_p1;
wire  signed [17:0] sext_ln105_51_fu_2291_p1;
wire  signed [15:0] grp_fu_2521_p3;
wire  signed [15:0] grp_fu_2530_p3;
wire  signed [16:0] sext_ln105_57_fu_2320_p1;
wire  signed [16:0] sext_ln105_56_fu_2317_p1;
wire   [16:0] add_ln105_24_fu_2323_p2;
wire  signed [15:0] grp_fu_2539_p3;
wire  signed [16:0] grp_fu_2548_p3;
wire  signed [17:0] sext_ln105_61_fu_2336_p1;
wire  signed [17:0] sext_ln105_59_fu_2333_p1;
wire   [17:0] add_ln105_28_fu_2339_p2;
wire  signed [18:0] sext_ln105_62_fu_2345_p1;
wire  signed [18:0] sext_ln105_58_fu_2329_p1;
wire  signed [19:0] sext_ln105_63_fu_2361_p1;
wire  signed [19:0] sext_ln105_55_fu_2358_p1;
wire   [19:0] add_ln105_30_fu_2364_p2;
wire  signed [19:0] sext_ln105_48_fu_2355_p1;
wire   [0:0] tmp_fu_2384_p3;
wire   [6:0] trunc_ln107_fu_2380_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_idle_pp0_0to5;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 t_fu_184 = 4'd0;
#0 oc_fu_188 = 7'd0;
#0 indvar_flatten48_fu_192 = 10'd0;
#0 ap_done_reg = 1'b0;
end

cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_25_b3_pw_bias_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
b3_pw_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b3_pw_bias_address0),
    .ce0(b3_pw_bias_ce0_local),
    .q0(b3_pw_bias_q0)
);

cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_25_b3_pw_weight_ROM_AUTOcud #(
    .DataWidth( 8 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
b3_pw_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b3_pw_weight_address0_local),
    .ce0(b3_pw_weight_ce0_local),
    .q0(b3_pw_weight_q0),
    .address1(b3_pw_weight_address1_local),
    .ce1(b3_pw_weight_ce1_local),
    .q1(b3_pw_weight_q1),
    .address2(b3_pw_weight_address2_local),
    .ce2(b3_pw_weight_ce2_local),
    .q2(b3_pw_weight_q2),
    .address3(b3_pw_weight_address3_local),
    .ce3(b3_pw_weight_ce3_local),
    .q3(b3_pw_weight_q3),
    .address4(b3_pw_weight_address4_local),
    .ce4(b3_pw_weight_ce4_local),
    .q4(b3_pw_weight_q4),
    .address5(b3_pw_weight_address5_local),
    .ce5(b3_pw_weight_ce5_local),
    .q5(b3_pw_weight_q5),
    .address6(b3_pw_weight_address6_local),
    .ce6(b3_pw_weight_ce6_local),
    .q6(b3_pw_weight_q6),
    .address7(b3_pw_weight_address7_local),
    .ce7(b3_pw_weight_ce7_local),
    .q7(b3_pw_weight_q7),
    .address8(b3_pw_weight_address8_local),
    .ce8(b3_pw_weight_ce8_local),
    .q8(b3_pw_weight_q8),
    .address9(b3_pw_weight_address9_local),
    .ce9(b3_pw_weight_ce9_local),
    .q9(b3_pw_weight_q9),
    .address10(b3_pw_weight_address10_local),
    .ce10(b3_pw_weight_ce10_local),
    .q10(b3_pw_weight_q10),
    .address11(b3_pw_weight_address11_local),
    .ce11(b3_pw_weight_ce11_local),
    .q11(b3_pw_weight_q11),
    .address12(b3_pw_weight_address12_local),
    .ce12(b3_pw_weight_ce12_local),
    .q12(b3_pw_weight_q12),
    .address13(b3_pw_weight_address13_local),
    .ce13(b3_pw_weight_ce13_local),
    .q13(b3_pw_weight_q13),
    .address14(b3_pw_weight_address14_local),
    .ce14(b3_pw_weight_ce14_local),
    .q14(b3_pw_weight_q14),
    .address15(b3_pw_weight_address15_local),
    .ce15(b3_pw_weight_ce15_local),
    .q15(b3_pw_weight_q15)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U91(
    .din0(reg_908),
    .din1(reg_873),
    .dout(mul_ln105_2_fu_2056_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U92(
    .din0(reg_913),
    .din1(reg_878),
    .dout(mul_ln105_4_fu_2062_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U93(
    .din0(reg_918),
    .din1(reg_883),
    .dout(mul_ln105_6_fu_2068_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U94(
    .din0(reg_923),
    .din1(reg_888),
    .dout(mul_ln105_8_fu_2074_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U95(
    .din0(reg_928),
    .din1(reg_893),
    .dout(mul_ln105_10_fu_2080_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U96(
    .din0(reg_933),
    .din1(reg_898),
    .dout(mul_ln105_12_fu_2086_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U97(
    .din0(reg_938),
    .din1(reg_903),
    .dout(mul_ln105_14_fu_2092_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U98(
    .din0(val_51_reg_3232),
    .din1(b3_pw_weight_load_30_reg_3152),
    .dout(mul_ln105_31_fu_2098_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U99(
    .din0(val_36_reg_3157),
    .din1(b3_pw_weight_load_15_reg_3077),
    .dout(mul_ln105_16_fu_2146_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U100(
    .din0(val_38_reg_3167),
    .din1(b3_pw_weight_load_17_reg_3087),
    .dout(mul_ln105_18_fu_2152_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U101(
    .din0(val_40_reg_3177),
    .din1(b3_pw_weight_load_19_reg_3097),
    .dout(mul_ln105_20_fu_2158_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U102(
    .din0(val_42_reg_3187),
    .din1(b3_pw_weight_load_21_reg_3107),
    .dout(mul_ln105_22_fu_2164_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U103(
    .din0(val_44_reg_3197),
    .din1(b3_pw_weight_load_23_reg_3117),
    .dout(mul_ln105_24_fu_2170_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U104(
    .din0(val_46_reg_3207),
    .din1(b3_pw_weight_load_25_reg_3127),
    .dout(mul_ln105_26_fu_2176_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U105(
    .din0(val_48_reg_3217),
    .din1(b3_pw_weight_load_27_reg_3137),
    .dout(mul_ln105_28_fu_2182_p2)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U106(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q0),
    .din1(b3_pw_weight_q0),
    .din2(mul_ln105_31_fu_2098_p2),
    .ce(1'b1),
    .dout(grp_fu_2404_p3)
);

cnn_forward_mac_muladd_8s_8s_13s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_13s_16_4_1_U107(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q15),
    .din1(b3_pw_weight_q15),
    .din2(b3_pw_bias_q0),
    .ce(1'b1),
    .dout(grp_fu_2413_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U108(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q14),
    .din1(b3_pw_weight_q14),
    .din2(mul_ln105_2_fu_2056_p2),
    .ce(1'b1),
    .dout(grp_fu_2422_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U109(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q13),
    .din1(b3_pw_weight_q13),
    .din2(mul_ln105_4_fu_2062_p2),
    .ce(1'b1),
    .dout(grp_fu_2431_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U110(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q12),
    .din1(b3_pw_weight_q12),
    .din2(mul_ln105_6_fu_2068_p2),
    .ce(1'b1),
    .dout(grp_fu_2440_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U111(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q11),
    .din1(b3_pw_weight_q11),
    .din2(mul_ln105_8_fu_2074_p2),
    .ce(1'b1),
    .dout(grp_fu_2449_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U112(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q10),
    .din1(b3_pw_weight_q10),
    .din2(mul_ln105_10_fu_2080_p2),
    .ce(1'b1),
    .dout(grp_fu_2458_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U113(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q9),
    .din1(b3_pw_weight_q9),
    .din2(mul_ln105_12_fu_2086_p2),
    .ce(1'b1),
    .dout(grp_fu_2467_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U114(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q8),
    .din1(b3_pw_weight_q8),
    .din2(mul_ln105_14_fu_2092_p2),
    .ce(1'b1),
    .dout(grp_fu_2476_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U115(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_908),
    .din1(reg_873),
    .din2(mul_ln105_16_fu_2146_p2),
    .ce(1'b1),
    .dout(grp_fu_2485_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U116(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_913),
    .din1(reg_878),
    .din2(mul_ln105_18_fu_2152_p2),
    .ce(1'b1),
    .dout(grp_fu_2494_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U117(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_918),
    .din1(reg_883),
    .din2(mul_ln105_20_fu_2158_p2),
    .ce(1'b1),
    .dout(grp_fu_2503_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U118(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_923),
    .din1(reg_888),
    .din2(mul_ln105_22_fu_2164_p2),
    .ce(1'b1),
    .dout(grp_fu_2512_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U119(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_928),
    .din1(reg_893),
    .din2(mul_ln105_24_fu_2170_p2),
    .ce(1'b1),
    .dout(grp_fu_2521_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U120(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_933),
    .din1(reg_898),
    .din2(mul_ln105_26_fu_2176_p2),
    .ce(1'b1),
    .dout(grp_fu_2530_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U121(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_938),
    .din1(reg_903),
    .din2(mul_ln105_28_fu_2182_p2),
    .ce(1'b1),
    .dout(grp_fu_2539_p3)
);

cnn_forward_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U122(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_b3_dw_q1),
    .din1(b3_pw_weight_q1),
    .din2(grp_fu_2404_p3),
    .ce(1'b1),
    .dout(grp_fu_2548_p3)
);

cnn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln100_fu_961_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten48_fu_192 <= add_ln100_fu_967_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten48_fu_192 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oc_fu_188 <= 7'd0;
    end else if (((icmp_ln100_reg_2578 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        oc_fu_188 <= add_ln100_1_fu_1003_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_873 <= b3_pw_weight_q15;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_873 <= b3_pw_weight_q7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_878 <= b3_pw_weight_q14;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_878 <= b3_pw_weight_q6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_883 <= b3_pw_weight_q13;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_883 <= b3_pw_weight_q5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_888 <= b3_pw_weight_q12;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_888 <= b3_pw_weight_q4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_893 <= b3_pw_weight_q11;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_893 <= b3_pw_weight_q3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_898 <= b3_pw_weight_q10;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_898 <= b3_pw_weight_q2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_903 <= b3_pw_weight_q9;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_903 <= b3_pw_weight_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_908 <= buf_b3_dw_q15;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_908 <= buf_b3_dw_q7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_913 <= buf_b3_dw_q14;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_913 <= buf_b3_dw_q6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_918 <= buf_b3_dw_q13;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_918 <= buf_b3_dw_q5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_923 <= buf_b3_dw_q12;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_923 <= buf_b3_dw_q4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_928 <= buf_b3_dw_q11;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_928 <= buf_b3_dw_q3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_933 <= buf_b3_dw_q10;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_933 <= buf_b3_dw_q2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_938 <= buf_b3_dw_q9;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reg_938 <= buf_b3_dw_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_fu_184 <= 4'd0;
    end else if (((icmp_ln100_reg_2578 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t_fu_184 <= add_ln101_fu_1429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_7_reg_3347 <= acc_7_fu_2370_p2;
        add_ln100_1_reg_2599 <= add_ln100_1_fu_1003_p2;
        add_ln105_13_reg_3322 <= add_ln105_13_fu_2258_p2;
        add_ln105_6_reg_3317 <= add_ln105_6_fu_2220_p2;
        select_ln100_reg_2593 <= select_ln100_fu_990_p3;
        select_ln108_reg_3357 <= select_ln108_fu_2392_p3;
        trunc_ln105_reg_2605 <= trunc_ln105_fu_1009_p1;
        zext_ln101_2_reg_2706[3 : 0] <= zext_ln101_2_fu_1226_p1[3 : 0];
        zext_ln101_3_reg_2715[3 : 0] <= zext_ln101_3_fu_1230_p1[3 : 0];
        zext_ln101_4_reg_2722[3 : 0] <= zext_ln101_4_fu_1234_p1[3 : 0];
        zext_ln101_6_reg_2730[3 : 0] <= zext_ln101_6_fu_1238_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln105_14_reg_3332 <= add_ln105_14_fu_2273_p2;
        add_ln105_21_reg_3337 <= add_ln105_21_fu_2311_p2;
        add_ln105_29_reg_3342 <= add_ln105_29_fu_2349_p2;
        add_ln109_reg_3067 <= add_ln109_fu_1916_p2;
        add_ln109_reg_3067_pp0_iter2_reg <= add_ln109_reg_3067;
        add_ln109_reg_3067_pp0_iter3_reg <= add_ln109_reg_3067_pp0_iter2_reg;
        add_ln109_reg_3067_pp0_iter4_reg <= add_ln109_reg_3067_pp0_iter3_reg;
        add_ln109_reg_3067_pp0_iter5_reg <= add_ln109_reg_3067_pp0_iter4_reg;
        add_ln109_reg_3067_pp0_iter6_reg <= add_ln109_reg_3067_pp0_iter5_reg;
        icmp_ln100_reg_2578 <= icmp_ln100_fu_961_p2;
        icmp_ln101_reg_2587 <= icmp_ln101_fu_976_p2;
        t_load_reg_2582 <= ap_sig_allocacmp_t_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_load_15_reg_3077 <= b3_pw_weight_q8;
        b3_pw_weight_load_17_reg_3087 <= b3_pw_weight_q7;
        b3_pw_weight_load_19_reg_3097 <= b3_pw_weight_q6;
        b3_pw_weight_load_21_reg_3107 <= b3_pw_weight_q5;
        b3_pw_weight_load_23_reg_3117 <= b3_pw_weight_q4;
        b3_pw_weight_load_25_reg_3127 <= b3_pw_weight_q3;
        b3_pw_weight_load_27_reg_3137 <= b3_pw_weight_q2;
        b3_pw_weight_load_30_reg_3152 <= b3_pw_weight_q0;
        val_36_reg_3157 <= buf_b3_dw_q8;
        val_38_reg_3167 <= buf_b3_dw_q7;
        val_40_reg_3177 <= buf_b3_dw_q6;
        val_42_reg_3187 <= buf_b3_dw_q5;
        val_44_reg_3197 <= buf_b3_dw_q4;
        val_46_reg_3207 <= buf_b3_dw_q3;
        val_48_reg_3217 <= buf_b3_dw_q2;
        val_51_reg_3232 <= buf_b3_dw_q0;
    end
end

always @ (*) begin
    if (((icmp_ln100_reg_2578 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten48_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten48_load = indvar_flatten48_fu_192;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 4'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_184;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_bias_ce0_local = 1'b1;
    end else begin
        b3_pw_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address0_local = zext_ln105_29_fu_1680_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address0_local = zext_ln105_30_fu_1216_p1;
    end else begin
        b3_pw_weight_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address10_local = zext_ln105_10_fu_1552_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address10_local = zext_ln105_9_fu_1086_p1;
    end else begin
        b3_pw_weight_address10_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address11_local = zext_ln105_8_fu_1536_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address11_local = zext_ln105_7_fu_1073_p1;
    end else begin
        b3_pw_weight_address11_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address12_local = zext_ln105_6_fu_1520_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address12_local = zext_ln105_5_fu_1060_p1;
    end else begin
        b3_pw_weight_address12_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address13_local = zext_ln105_4_fu_1504_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address13_local = zext_ln105_3_fu_1047_p1;
    end else begin
        b3_pw_weight_address13_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address14_local = zext_ln105_2_fu_1488_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address14_local = zext_ln105_1_fu_1034_p1;
    end else begin
        b3_pw_weight_address14_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address15_local = zext_ln105_fu_1472_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address15_local = zext_ln109_fu_1021_p1;
    end else begin
        b3_pw_weight_address15_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address1_local = zext_ln105_28_fu_1668_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address1_local = zext_ln105_27_fu_1203_p1;
    end else begin
        b3_pw_weight_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address2_local = zext_ln105_26_fu_1656_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address2_local = zext_ln105_25_fu_1190_p1;
    end else begin
        b3_pw_weight_address2_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address3_local = zext_ln105_24_fu_1644_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address3_local = zext_ln105_23_fu_1177_p1;
    end else begin
        b3_pw_weight_address3_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address4_local = zext_ln105_22_fu_1632_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address4_local = zext_ln105_21_fu_1164_p1;
    end else begin
        b3_pw_weight_address4_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address5_local = zext_ln105_20_fu_1620_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address5_local = zext_ln105_19_fu_1151_p1;
    end else begin
        b3_pw_weight_address5_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address6_local = zext_ln105_18_fu_1608_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address6_local = zext_ln105_17_fu_1138_p1;
    end else begin
        b3_pw_weight_address6_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address7_local = zext_ln105_16_fu_1596_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address7_local = zext_ln105_15_fu_1125_p1;
    end else begin
        b3_pw_weight_address7_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address8_local = zext_ln105_14_fu_1584_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address8_local = zext_ln105_13_fu_1112_p1;
    end else begin
        b3_pw_weight_address8_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_pw_weight_address9_local = zext_ln105_12_fu_1568_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_pw_weight_address9_local = zext_ln105_11_fu_1099_p1;
    end else begin
        b3_pw_weight_address9_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce0_local = 1'b1;
    end else begin
        b3_pw_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce10_local = 1'b1;
    end else begin
        b3_pw_weight_ce10_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce11_local = 1'b1;
    end else begin
        b3_pw_weight_ce11_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce12_local = 1'b1;
    end else begin
        b3_pw_weight_ce12_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce13_local = 1'b1;
    end else begin
        b3_pw_weight_ce13_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce14_local = 1'b1;
    end else begin
        b3_pw_weight_ce14_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce15_local = 1'b1;
    end else begin
        b3_pw_weight_ce15_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce1_local = 1'b1;
    end else begin
        b3_pw_weight_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce2_local = 1'b1;
    end else begin
        b3_pw_weight_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce3_local = 1'b1;
    end else begin
        b3_pw_weight_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce4_local = 1'b1;
    end else begin
        b3_pw_weight_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce5_local = 1'b1;
    end else begin
        b3_pw_weight_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce6_local = 1'b1;
    end else begin
        b3_pw_weight_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce7_local = 1'b1;
    end else begin
        b3_pw_weight_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce8_local = 1'b1;
    end else begin
        b3_pw_weight_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b3_pw_weight_ce9_local = 1'b1;
    end else begin
        b3_pw_weight_ce9_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address0_local = zext_ln104_29_fu_1907_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address0_local = zext_ln104_30_fu_1424_p1;
    end else begin
        buf_b3_dw_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address10_local = zext_ln104_10_fu_1779_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address10_local = zext_ln104_9_fu_1292_p1;
    end else begin
        buf_b3_dw_address10_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address11_local = zext_ln104_8_fu_1765_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address11_local = zext_ln104_7_fu_1281_p1;
    end else begin
        buf_b3_dw_address11_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address12_local = zext_ln104_6_fu_1751_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address12_local = zext_ln104_5_fu_1270_p1;
    end else begin
        buf_b3_dw_address12_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address13_local = zext_ln104_4_fu_1733_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address13_local = zext_ln104_3_fu_1259_p1;
    end else begin
        buf_b3_dw_address13_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address14_local = zext_ln104_2_fu_1719_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address14_local = zext_ln104_1_fu_1248_p1;
    end else begin
        buf_b3_dw_address14_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address15_local = zext_ln104_fu_1705_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address15_local = zext_ln101_fu_1221_p1;
    end else begin
        buf_b3_dw_address15_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address1_local = zext_ln104_28_fu_1893_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address1_local = zext_ln104_27_fu_1409_p1;
    end else begin
        buf_b3_dw_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address2_local = zext_ln104_26_fu_1879_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address2_local = zext_ln104_25_fu_1394_p1;
    end else begin
        buf_b3_dw_address2_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address3_local = zext_ln104_24_fu_1865_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address3_local = zext_ln104_23_fu_1379_p1;
    end else begin
        buf_b3_dw_address3_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address4_local = zext_ln104_22_fu_1855_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address4_local = zext_ln104_21_fu_1368_p1;
    end else begin
        buf_b3_dw_address4_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address5_local = zext_ln104_20_fu_1845_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address5_local = zext_ln104_19_fu_1357_p1;
    end else begin
        buf_b3_dw_address5_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address6_local = zext_ln104_18_fu_1835_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address6_local = zext_ln104_17_fu_1346_p1;
    end else begin
        buf_b3_dw_address6_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address7_local = zext_ln104_16_fu_1825_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address7_local = zext_ln104_15_fu_1335_p1;
    end else begin
        buf_b3_dw_address7_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address8_local = zext_ln104_14_fu_1815_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address8_local = zext_ln104_13_fu_1318_p1;
    end else begin
        buf_b3_dw_address8_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_dw_address9_local = zext_ln104_12_fu_1797_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        buf_b3_dw_address9_local = zext_ln104_11_fu_1303_p1;
    end else begin
        buf_b3_dw_address9_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce0_local = 1'b1;
    end else begin
        buf_b3_dw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce10_local = 1'b1;
    end else begin
        buf_b3_dw_ce10_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce11_local = 1'b1;
    end else begin
        buf_b3_dw_ce11_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce12_local = 1'b1;
    end else begin
        buf_b3_dw_ce12_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce13_local = 1'b1;
    end else begin
        buf_b3_dw_ce13_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce14_local = 1'b1;
    end else begin
        buf_b3_dw_ce14_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce15_local = 1'b1;
    end else begin
        buf_b3_dw_ce15_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce1_local = 1'b1;
    end else begin
        buf_b3_dw_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce2_local = 1'b1;
    end else begin
        buf_b3_dw_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce3_local = 1'b1;
    end else begin
        buf_b3_dw_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce4_local = 1'b1;
    end else begin
        buf_b3_dw_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce5_local = 1'b1;
    end else begin
        buf_b3_dw_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce6_local = 1'b1;
    end else begin
        buf_b3_dw_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce7_local = 1'b1;
    end else begin
        buf_b3_dw_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce8_local = 1'b1;
    end else begin
        buf_b3_dw_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_b3_dw_ce9_local = 1'b1;
    end else begin
        buf_b3_dw_ce9_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_pw_ce0_local = 1'b1;
    end else begin
        buf_b3_pw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b3_pw_we0_local = 1'b1;
    end else begin
        buf_b3_pw_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp597) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp596) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_requantize_fu_864_ap_ce = 1'b1;
    end else begin
        grp_requantize_fu_864_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0_0to5 == 1'b1) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_7_fu_2370_p2 = ($signed(add_ln105_30_fu_2364_p2) + $signed(sext_ln105_48_fu_2355_p1));

assign add_ln100_1_fu_1003_p2 = (oc_fu_188 + empty_fu_996_p3);

assign add_ln100_fu_967_p2 = (ap_sig_allocacmp_indvar_flatten48_load + 10'd1);

assign add_ln101_fu_1429_p2 = (select_ln100_fu_990_p3 + 4'd1);

assign add_ln104_10_fu_1774_p2 = ($signed(zext_ln101_4_reg_2722) + $signed(8'd165));

assign add_ln104_11_fu_1297_p2 = ($signed(zext_ln101_4_fu_1234_p1) + $signed(8'd180));

assign add_ln104_12_fu_1788_p2 = ($signed(zext_ln101_3_reg_2715) + $signed(7'd67));

assign add_ln104_13_fu_1308_p2 = ($signed(zext_ln101_3_fu_1230_p1) + $signed(7'd82));

assign add_ln104_14_fu_1806_p2 = ($signed(zext_ln101_6_reg_2730) + $signed(6'd33));

assign add_ln104_15_fu_1820_p2 = (zext_ln101_2_reg_2706 + 9'd255);

assign add_ln104_16_fu_1340_p2 = ($signed(zext_ln101_2_fu_1226_p1) + $signed(9'd270));

assign add_ln104_17_fu_1830_p2 = ($signed(zext_ln101_2_reg_2706) + $signed(9'd285));

assign add_ln104_18_fu_1351_p2 = ($signed(zext_ln101_2_fu_1226_p1) + $signed(9'd300));

assign add_ln104_19_fu_1840_p2 = ($signed(zext_ln101_2_reg_2706) + $signed(9'd315));

assign add_ln104_1_fu_1242_p2 = (zext_ln101_6_fu_1238_p1 + 6'd30);

assign add_ln104_20_fu_1362_p2 = ($signed(zext_ln101_2_fu_1226_p1) + $signed(9'd330));

assign add_ln104_21_fu_1850_p2 = ($signed(zext_ln101_2_reg_2706) + $signed(9'd345));

assign add_ln104_22_fu_1373_p2 = ($signed(zext_ln101_2_fu_1226_p1) + $signed(9'd360));

assign add_ln104_23_fu_1860_p2 = ($signed(zext_ln101_2_reg_2706) + $signed(9'd375));

assign add_ln104_24_fu_1384_p2 = ($signed(zext_ln101_4_fu_1234_p1) + $signed(8'd134));

assign add_ln104_25_fu_1870_p2 = ($signed(zext_ln101_4_reg_2722) + $signed(8'd149));

assign add_ln104_26_fu_1399_p2 = ($signed(zext_ln101_4_fu_1234_p1) + $signed(8'd164));

assign add_ln104_27_fu_1884_p2 = ($signed(zext_ln101_4_reg_2722) + $signed(8'd179));

assign add_ln104_28_fu_1898_p2 = ($signed(zext_ln101_3_reg_2715) + $signed(7'd66));

assign add_ln104_29_fu_1414_p2 = ($signed(zext_ln101_3_fu_1230_p1) + $signed(7'd81));

assign add_ln104_2_fu_1714_p2 = ($signed(zext_ln101_6_reg_2730) + $signed(6'd45));

assign add_ln104_3_fu_1253_p2 = (zext_ln101_3_fu_1230_p1 + 7'd60);

assign add_ln104_4_fu_1728_p2 = ($signed(zext_ln101_3_reg_2715) + $signed(7'd75));

assign add_ln104_5_fu_1264_p2 = ($signed(zext_ln101_3_fu_1230_p1) + $signed(7'd90));

assign add_ln104_6_fu_1742_p2 = ($signed(zext_ln101_6_reg_2730) + $signed(6'd41));

assign add_ln104_7_fu_1275_p2 = (zext_ln101_4_fu_1234_p1 + 8'd120);

assign add_ln104_8_fu_1760_p2 = ($signed(zext_ln101_4_reg_2722) + $signed(8'd135));

assign add_ln104_9_fu_1286_p2 = ($signed(zext_ln101_4_fu_1234_p1) + $signed(8'd150));

assign add_ln104_fu_1699_p2 = (zext_ln101_5_fu_1692_p1 + 5'd15);

assign add_ln105_12_fu_2248_p2 = ($signed(sext_ln105_45_fu_2245_p1) + $signed(sext_ln105_44_fu_2242_p1));

assign add_ln105_13_fu_2258_p2 = ($signed(sext_ln105_46_fu_2254_p1) + $signed(sext_ln105_43_fu_2238_p1));

assign add_ln105_14_fu_2273_p2 = ($signed(sext_ln105_47_fu_2270_p1) + $signed(sext_ln105_40_fu_2267_p1));

assign add_ln105_17_fu_2285_p2 = ($signed(sext_ln105_50_fu_2282_p1) + $signed(sext_ln105_49_fu_2279_p1));

assign add_ln105_20_fu_2301_p2 = ($signed(sext_ln105_53_fu_2298_p1) + $signed(sext_ln105_52_fu_2295_p1));

assign add_ln105_21_fu_2311_p2 = ($signed(sext_ln105_54_fu_2307_p1) + $signed(sext_ln105_51_fu_2291_p1));

assign add_ln105_24_fu_2323_p2 = ($signed(sext_ln105_57_fu_2320_p1) + $signed(sext_ln105_56_fu_2317_p1));

assign add_ln105_28_fu_2339_p2 = ($signed(sext_ln105_61_fu_2336_p1) + $signed(sext_ln105_59_fu_2333_p1));

assign add_ln105_29_fu_2349_p2 = ($signed(sext_ln105_62_fu_2345_p1) + $signed(sext_ln105_58_fu_2329_p1));

assign add_ln105_2_fu_2194_p2 = ($signed(sext_ln105_35_fu_2191_p1) + $signed(sext_ln105_34_fu_2188_p1));

assign add_ln105_30_fu_2364_p2 = ($signed(sext_ln105_63_fu_2361_p1) + $signed(sext_ln105_55_fu_2358_p1));

assign add_ln105_5_fu_2210_p2 = ($signed(sext_ln105_38_fu_2207_p1) + $signed(sext_ln105_37_fu_2204_p1));

assign add_ln105_6_fu_2220_p2 = ($signed(sext_ln105_39_fu_2216_p1) + $signed(sext_ln105_36_fu_2200_p1));

assign add_ln105_9_fu_2232_p2 = ($signed(sext_ln105_42_fu_2229_p1) + $signed(sext_ln105_41_fu_2226_p1));

assign add_ln109_fu_1916_p2 = (zext_ln101_1_fu_1689_p1 + sub_ln105_fu_1455_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp596 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp596 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp597 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign b3_pw_bias_address0 = zext_ln100_fu_1922_p1;

assign buf_b3_dw_address0 = buf_b3_dw_address0_local;

assign buf_b3_dw_address1 = buf_b3_dw_address1_local;

assign buf_b3_dw_address10 = buf_b3_dw_address10_local;

assign buf_b3_dw_address11 = buf_b3_dw_address11_local;

assign buf_b3_dw_address12 = buf_b3_dw_address12_local;

assign buf_b3_dw_address13 = buf_b3_dw_address13_local;

assign buf_b3_dw_address14 = buf_b3_dw_address14_local;

assign buf_b3_dw_address15 = buf_b3_dw_address15_local;

assign buf_b3_dw_address2 = buf_b3_dw_address2_local;

assign buf_b3_dw_address3 = buf_b3_dw_address3_local;

assign buf_b3_dw_address4 = buf_b3_dw_address4_local;

assign buf_b3_dw_address5 = buf_b3_dw_address5_local;

assign buf_b3_dw_address6 = buf_b3_dw_address6_local;

assign buf_b3_dw_address7 = buf_b3_dw_address7_local;

assign buf_b3_dw_address8 = buf_b3_dw_address8_local;

assign buf_b3_dw_address9 = buf_b3_dw_address9_local;

assign buf_b3_dw_ce0 = buf_b3_dw_ce0_local;

assign buf_b3_dw_ce1 = buf_b3_dw_ce1_local;

assign buf_b3_dw_ce10 = buf_b3_dw_ce10_local;

assign buf_b3_dw_ce11 = buf_b3_dw_ce11_local;

assign buf_b3_dw_ce12 = buf_b3_dw_ce12_local;

assign buf_b3_dw_ce13 = buf_b3_dw_ce13_local;

assign buf_b3_dw_ce14 = buf_b3_dw_ce14_local;

assign buf_b3_dw_ce15 = buf_b3_dw_ce15_local;

assign buf_b3_dw_ce2 = buf_b3_dw_ce2_local;

assign buf_b3_dw_ce3 = buf_b3_dw_ce3_local;

assign buf_b3_dw_ce4 = buf_b3_dw_ce4_local;

assign buf_b3_dw_ce5 = buf_b3_dw_ce5_local;

assign buf_b3_dw_ce6 = buf_b3_dw_ce6_local;

assign buf_b3_dw_ce7 = buf_b3_dw_ce7_local;

assign buf_b3_dw_ce8 = buf_b3_dw_ce8_local;

assign buf_b3_dw_ce9 = buf_b3_dw_ce9_local;

assign buf_b3_pw_address0 = zext_ln109_2_fu_2400_p1;

assign buf_b3_pw_ce0 = buf_b3_pw_ce0_local;

assign buf_b3_pw_d0 = select_ln108_reg_3357;

assign buf_b3_pw_we0 = buf_b3_pw_we0_local;

assign empty_fu_996_p3 = ((icmp_ln101_reg_2587[0:0] == 1'b1) ? 7'd1 : 7'd0);

assign grp_requantize_fu_466_p_ce = grp_requantize_fu_864_ap_ce;

assign grp_requantize_fu_466_p_din1 = sext_ln102_fu_2376_p1;

assign grp_requantize_fu_466_p_din2 = 31'd20112260;

assign grp_requantize_fu_466_p_din3 = 2'd3;

assign icmp_ln100_fu_961_p2 = ((ap_sig_allocacmp_indvar_flatten48_load == 10'd960) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_976_p2 = ((ap_sig_allocacmp_t_load == 4'd15) ? 1'b1 : 1'b0);

assign or_ln104_2_fu_1323_p3 = {{1'd1}, {select_ln100_fu_990_p3}};

assign or_ln105_10_fu_1545_p3 = {{trunc_ln105_reg_2605}, {5'd11}};

assign or_ln105_11_fu_1091_p3 = {{trunc_ln105_fu_1009_p1}, {5'd12}};

assign or_ln105_12_fu_1561_p3 = {{trunc_ln105_reg_2605}, {5'd13}};

assign or_ln105_13_fu_1104_p3 = {{trunc_ln105_fu_1009_p1}, {5'd14}};

assign or_ln105_14_fu_1577_p3 = {{trunc_ln105_reg_2605}, {5'd15}};

assign or_ln105_15_fu_1117_p3 = {{trunc_ln105_fu_1009_p1}, {5'd16}};

assign or_ln105_16_fu_1589_p3 = {{trunc_ln105_reg_2605}, {5'd17}};

assign or_ln105_17_fu_1130_p3 = {{trunc_ln105_fu_1009_p1}, {5'd18}};

assign or_ln105_18_fu_1601_p3 = {{trunc_ln105_reg_2605}, {5'd19}};

assign or_ln105_19_fu_1143_p3 = {{trunc_ln105_fu_1009_p1}, {5'd20}};

assign or_ln105_1_fu_1026_p3 = {{trunc_ln105_fu_1009_p1}, {5'd2}};

assign or_ln105_20_fu_1613_p3 = {{trunc_ln105_reg_2605}, {5'd21}};

assign or_ln105_21_fu_1156_p3 = {{trunc_ln105_fu_1009_p1}, {5'd22}};

assign or_ln105_22_fu_1625_p3 = {{trunc_ln105_reg_2605}, {5'd23}};

assign or_ln105_23_fu_1169_p3 = {{trunc_ln105_fu_1009_p1}, {5'd24}};

assign or_ln105_24_fu_1637_p3 = {{trunc_ln105_reg_2605}, {5'd25}};

assign or_ln105_25_fu_1182_p3 = {{trunc_ln105_fu_1009_p1}, {5'd26}};

assign or_ln105_26_fu_1649_p3 = {{trunc_ln105_reg_2605}, {5'd27}};

assign or_ln105_27_fu_1195_p3 = {{trunc_ln105_fu_1009_p1}, {5'd28}};

assign or_ln105_28_fu_1661_p3 = {{trunc_ln105_reg_2605}, {5'd29}};

assign or_ln105_29_fu_1673_p3 = {{trunc_ln105_reg_2605}, {5'd30}};

assign or_ln105_2_fu_1481_p3 = {{trunc_ln105_reg_2605}, {5'd3}};

assign or_ln105_30_fu_1208_p3 = {{trunc_ln105_fu_1009_p1}, {5'd31}};

assign or_ln105_3_fu_1039_p3 = {{trunc_ln105_fu_1009_p1}, {5'd4}};

assign or_ln105_4_fu_1497_p3 = {{trunc_ln105_reg_2605}, {5'd5}};

assign or_ln105_5_fu_1052_p3 = {{trunc_ln105_fu_1009_p1}, {5'd6}};

assign or_ln105_6_fu_1513_p3 = {{trunc_ln105_reg_2605}, {5'd7}};

assign or_ln105_7_fu_1065_p3 = {{trunc_ln105_fu_1009_p1}, {5'd8}};

assign or_ln105_8_fu_1529_p3 = {{trunc_ln105_reg_2605}, {5'd9}};

assign or_ln105_9_fu_1078_p3 = {{trunc_ln105_fu_1009_p1}, {5'd10}};

assign or_ln105_s_fu_1465_p3 = {{trunc_ln105_reg_2605}, {5'd1}};

assign p_shl_fu_1448_p3 = {{trunc_ln105_reg_2605}, {4'd0}};

assign select_ln100_fu_990_p3 = ((icmp_ln101_reg_2587[0:0] == 1'b1) ? 4'd0 : t_load_reg_2582);

assign select_ln108_fu_2392_p3 = ((tmp_fu_2384_p3[0:0] == 1'b1) ? 7'd0 : trunc_ln107_fu_2380_p1);

assign sext_ln102_fu_2376_p1 = $signed(acc_7_reg_3347);

assign sext_ln104_14_fu_1793_p1 = $signed(add_ln104_12_fu_1788_p2);

assign sext_ln104_16_fu_1314_p1 = $signed(add_ln104_13_fu_1308_p2);

assign sext_ln104_18_fu_1811_p1 = $signed(add_ln104_14_fu_1806_p2);

assign sext_ln104_20_fu_1331_p1 = $signed(or_ln104_2_fu_1323_p3);

assign sext_ln104_31_fu_1390_p1 = $signed(add_ln104_24_fu_1384_p2);

assign sext_ln104_33_fu_1875_p1 = $signed(add_ln104_25_fu_1870_p2);

assign sext_ln104_35_fu_1405_p1 = $signed(add_ln104_26_fu_1399_p2);

assign sext_ln104_37_fu_1889_p1 = $signed(add_ln104_27_fu_1884_p2);

assign sext_ln104_39_fu_1903_p1 = $signed(add_ln104_28_fu_1898_p2);

assign sext_ln104_41_fu_1420_p1 = $signed(add_ln104_29_fu_1414_p2);

assign sext_ln104_7_fu_1747_p1 = $signed(add_ln104_6_fu_1742_p2);

assign sext_ln105_34_fu_2188_p1 = grp_fu_2413_p3;

assign sext_ln105_35_fu_2191_p1 = grp_fu_2422_p3;

assign sext_ln105_36_fu_2200_p1 = $signed(add_ln105_2_fu_2194_p2);

assign sext_ln105_37_fu_2204_p1 = grp_fu_2431_p3;

assign sext_ln105_38_fu_2207_p1 = grp_fu_2440_p3;

assign sext_ln105_39_fu_2216_p1 = $signed(add_ln105_5_fu_2210_p2);

assign sext_ln105_40_fu_2267_p1 = $signed(add_ln105_6_reg_3317);

assign sext_ln105_41_fu_2226_p1 = grp_fu_2449_p3;

assign sext_ln105_42_fu_2229_p1 = grp_fu_2458_p3;

assign sext_ln105_43_fu_2238_p1 = $signed(add_ln105_9_fu_2232_p2);

assign sext_ln105_44_fu_2242_p1 = grp_fu_2467_p3;

assign sext_ln105_45_fu_2245_p1 = grp_fu_2476_p3;

assign sext_ln105_46_fu_2254_p1 = $signed(add_ln105_12_fu_2248_p2);

assign sext_ln105_47_fu_2270_p1 = $signed(add_ln105_13_reg_3322);

assign sext_ln105_48_fu_2355_p1 = $signed(add_ln105_14_reg_3332);

assign sext_ln105_49_fu_2279_p1 = grp_fu_2485_p3;

assign sext_ln105_50_fu_2282_p1 = grp_fu_2494_p3;

assign sext_ln105_51_fu_2291_p1 = $signed(add_ln105_17_fu_2285_p2);

assign sext_ln105_52_fu_2295_p1 = grp_fu_2503_p3;

assign sext_ln105_53_fu_2298_p1 = grp_fu_2512_p3;

assign sext_ln105_54_fu_2307_p1 = $signed(add_ln105_20_fu_2301_p2);

assign sext_ln105_55_fu_2358_p1 = $signed(add_ln105_21_reg_3337);

assign sext_ln105_56_fu_2317_p1 = grp_fu_2521_p3;

assign sext_ln105_57_fu_2320_p1 = grp_fu_2530_p3;

assign sext_ln105_58_fu_2329_p1 = $signed(add_ln105_24_fu_2323_p2);

assign sext_ln105_59_fu_2333_p1 = grp_fu_2539_p3;

assign sext_ln105_61_fu_2336_p1 = grp_fu_2548_p3;

assign sext_ln105_62_fu_2345_p1 = $signed(add_ln105_28_fu_2339_p2);

assign sext_ln105_63_fu_2361_p1 = $signed(add_ln105_29_reg_3342);

assign shl_ln1_fu_1013_p3 = {{trunc_ln105_fu_1009_p1}, {5'd0}};

assign sub_ln105_fu_1455_p2 = (p_shl_fu_1448_p3 - zext_ln109_1_fu_1445_p1);

assign tmp_fu_2384_p3 = grp_requantize_fu_466_p_dout0[32'd7];

assign trunc_ln105_fu_1009_p1 = add_ln100_1_fu_1003_p2[5:0];

assign trunc_ln107_fu_2380_p1 = grp_requantize_fu_466_p_dout0[6:0];

assign zext_ln100_fu_1922_p1 = add_ln100_1_reg_2599;

assign zext_ln101_1_fu_1689_p1 = select_ln100_reg_2593;

assign zext_ln101_2_fu_1226_p1 = select_ln100_fu_990_p3;

assign zext_ln101_3_fu_1230_p1 = select_ln100_fu_990_p3;

assign zext_ln101_4_fu_1234_p1 = select_ln100_fu_990_p3;

assign zext_ln101_5_fu_1692_p1 = select_ln100_reg_2593;

assign zext_ln101_6_fu_1238_p1 = select_ln100_fu_990_p3;

assign zext_ln101_fu_1221_p1 = select_ln100_fu_990_p3;

assign zext_ln104_10_fu_1779_p1 = add_ln104_10_fu_1774_p2;

assign zext_ln104_11_fu_1303_p1 = add_ln104_11_fu_1297_p2;

assign zext_ln104_12_fu_1797_p1 = $unsigned(sext_ln104_14_fu_1793_p1);

assign zext_ln104_13_fu_1318_p1 = $unsigned(sext_ln104_16_fu_1314_p1);

assign zext_ln104_14_fu_1815_p1 = $unsigned(sext_ln104_18_fu_1811_p1);

assign zext_ln104_15_fu_1335_p1 = $unsigned(sext_ln104_20_fu_1331_p1);

assign zext_ln104_16_fu_1825_p1 = add_ln104_15_fu_1820_p2;

assign zext_ln104_17_fu_1346_p1 = add_ln104_16_fu_1340_p2;

assign zext_ln104_18_fu_1835_p1 = add_ln104_17_fu_1830_p2;

assign zext_ln104_19_fu_1357_p1 = add_ln104_18_fu_1351_p2;

assign zext_ln104_1_fu_1248_p1 = add_ln104_1_fu_1242_p2;

assign zext_ln104_20_fu_1845_p1 = add_ln104_19_fu_1840_p2;

assign zext_ln104_21_fu_1368_p1 = add_ln104_20_fu_1362_p2;

assign zext_ln104_22_fu_1855_p1 = add_ln104_21_fu_1850_p2;

assign zext_ln104_23_fu_1379_p1 = add_ln104_22_fu_1373_p2;

assign zext_ln104_24_fu_1865_p1 = add_ln104_23_fu_1860_p2;

assign zext_ln104_25_fu_1394_p1 = $unsigned(sext_ln104_31_fu_1390_p1);

assign zext_ln104_26_fu_1879_p1 = $unsigned(sext_ln104_33_fu_1875_p1);

assign zext_ln104_27_fu_1409_p1 = $unsigned(sext_ln104_35_fu_1405_p1);

assign zext_ln104_28_fu_1893_p1 = $unsigned(sext_ln104_37_fu_1889_p1);

assign zext_ln104_29_fu_1907_p1 = $unsigned(sext_ln104_39_fu_1903_p1);

assign zext_ln104_2_fu_1719_p1 = add_ln104_2_fu_1714_p2;

assign zext_ln104_30_fu_1424_p1 = $unsigned(sext_ln104_41_fu_1420_p1);

assign zext_ln104_3_fu_1259_p1 = add_ln104_3_fu_1253_p2;

assign zext_ln104_4_fu_1733_p1 = add_ln104_4_fu_1728_p2;

assign zext_ln104_5_fu_1270_p1 = add_ln104_5_fu_1264_p2;

assign zext_ln104_6_fu_1751_p1 = $unsigned(sext_ln104_7_fu_1747_p1);

assign zext_ln104_7_fu_1281_p1 = add_ln104_7_fu_1275_p2;

assign zext_ln104_8_fu_1765_p1 = add_ln104_8_fu_1760_p2;

assign zext_ln104_9_fu_1292_p1 = add_ln104_9_fu_1286_p2;

assign zext_ln104_fu_1705_p1 = add_ln104_fu_1699_p2;

assign zext_ln105_10_fu_1552_p1 = or_ln105_10_fu_1545_p3;

assign zext_ln105_11_fu_1099_p1 = or_ln105_11_fu_1091_p3;

assign zext_ln105_12_fu_1568_p1 = or_ln105_12_fu_1561_p3;

assign zext_ln105_13_fu_1112_p1 = or_ln105_13_fu_1104_p3;

assign zext_ln105_14_fu_1584_p1 = or_ln105_14_fu_1577_p3;

assign zext_ln105_15_fu_1125_p1 = or_ln105_15_fu_1117_p3;

assign zext_ln105_16_fu_1596_p1 = or_ln105_16_fu_1589_p3;

assign zext_ln105_17_fu_1138_p1 = or_ln105_17_fu_1130_p3;

assign zext_ln105_18_fu_1608_p1 = or_ln105_18_fu_1601_p3;

assign zext_ln105_19_fu_1151_p1 = or_ln105_19_fu_1143_p3;

assign zext_ln105_1_fu_1034_p1 = or_ln105_1_fu_1026_p3;

assign zext_ln105_20_fu_1620_p1 = or_ln105_20_fu_1613_p3;

assign zext_ln105_21_fu_1164_p1 = or_ln105_21_fu_1156_p3;

assign zext_ln105_22_fu_1632_p1 = or_ln105_22_fu_1625_p3;

assign zext_ln105_23_fu_1177_p1 = or_ln105_23_fu_1169_p3;

assign zext_ln105_24_fu_1644_p1 = or_ln105_24_fu_1637_p3;

assign zext_ln105_25_fu_1190_p1 = or_ln105_25_fu_1182_p3;

assign zext_ln105_26_fu_1656_p1 = or_ln105_26_fu_1649_p3;

assign zext_ln105_27_fu_1203_p1 = or_ln105_27_fu_1195_p3;

assign zext_ln105_28_fu_1668_p1 = or_ln105_28_fu_1661_p3;

assign zext_ln105_29_fu_1680_p1 = or_ln105_29_fu_1673_p3;

assign zext_ln105_2_fu_1488_p1 = or_ln105_2_fu_1481_p3;

assign zext_ln105_30_fu_1216_p1 = or_ln105_30_fu_1208_p3;

assign zext_ln105_3_fu_1047_p1 = or_ln105_3_fu_1039_p3;

assign zext_ln105_4_fu_1504_p1 = or_ln105_4_fu_1497_p3;

assign zext_ln105_5_fu_1060_p1 = or_ln105_5_fu_1052_p3;

assign zext_ln105_6_fu_1520_p1 = or_ln105_6_fu_1513_p3;

assign zext_ln105_7_fu_1073_p1 = or_ln105_7_fu_1065_p3;

assign zext_ln105_8_fu_1536_p1 = or_ln105_8_fu_1529_p3;

assign zext_ln105_9_fu_1086_p1 = or_ln105_9_fu_1078_p3;

assign zext_ln105_fu_1472_p1 = or_ln105_s_fu_1465_p3;

assign zext_ln109_1_fu_1445_p1 = add_ln100_1_reg_2599;

assign zext_ln109_2_fu_2400_p1 = add_ln109_reg_3067_pp0_iter6_reg;

assign zext_ln109_fu_1021_p1 = shl_ln1_fu_1013_p3;

always @ (posedge ap_clk) begin
    zext_ln101_2_reg_2706[8:4] <= 5'b00000;
    zext_ln101_3_reg_2715[6:4] <= 3'b000;
    zext_ln101_4_reg_2722[7:4] <= 4'b0000;
    zext_ln101_6_reg_2730[5:4] <= 2'b00;
end

endmodule //cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_25
