// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_64_24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_b2_pool_address0,
        buf_b2_pool_ce0,
        buf_b2_pool_q0,
        buf_b2_pool_address1,
        buf_b2_pool_ce1,
        buf_b2_pool_q1,
        buf_b2_pool_address2,
        buf_b2_pool_ce2,
        buf_b2_pool_q2,
        buf_b3_dw_address0,
        buf_b3_dw_ce0,
        buf_b3_dw_we0,
        buf_b3_dw_d0,
        grp_requantize_fu_466_p_din1,
        grp_requantize_fu_466_p_din2,
        grp_requantize_fu_466_p_din3,
        grp_requantize_fu_466_p_dout0,
        grp_requantize_fu_466_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] buf_b2_pool_address0;
output   buf_b2_pool_ce0;
input  [6:0] buf_b2_pool_q0;
output  [8:0] buf_b2_pool_address1;
output   buf_b2_pool_ce1;
input  [6:0] buf_b2_pool_q1;
output  [8:0] buf_b2_pool_address2;
output   buf_b2_pool_ce2;
input  [6:0] buf_b2_pool_q2;
output  [8:0] buf_b3_dw_address0;
output   buf_b3_dw_ce0;
output   buf_b3_dw_we0;
output  [7:0] buf_b3_dw_d0;
output  [22:0] grp_requantize_fu_466_p_din1;
output  [30:0] grp_requantize_fu_466_p_din2;
output  [1:0] grp_requantize_fu_466_p_din3;
input  [7:0] grp_requantize_fu_466_p_dout0;
output   grp_requantize_fu_466_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln63_fu_190_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] b3_dw_weight_address0;
wire  signed [7:0] b3_dw_weight_q0;
wire   [6:0] b3_dw_weight_address1;
wire   [7:0] b3_dw_weight_q1;
wire   [6:0] b3_dw_weight_address2;
wire  signed [7:0] b3_dw_weight_q2;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln63_fu_219_p3;
reg   [3:0] select_ln63_reg_479;
wire   [5:0] add_ln63_2_fu_235_p2;
reg   [5:0] add_ln63_2_reg_485;
wire   [4:0] trunc_ln72_fu_241_p1;
reg   [4:0] trunc_ln72_reg_492;
wire   [3:0] add_ln67_2_fu_245_p2;
reg   [3:0] add_ln67_2_reg_497;
wire   [7:0] sub_ln72_fu_274_p2;
reg   [7:0] sub_ln72_reg_503;
wire   [6:0] trunc_ln70_fu_280_p1;
reg   [6:0] trunc_ln70_reg_508;
wire   [0:0] icmp_ln69_fu_324_p2;
reg   [0:0] icmp_ln69_reg_518;
wire   [63:0] zext_ln70_5_fu_347_p1;
reg   [63:0] zext_ln70_5_reg_528;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter3_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter4_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter5_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter6_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter7_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter8_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter9_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter10_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter11_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter12_reg;
reg   [63:0] zext_ln70_5_reg_528_pp0_iter13_reg;
wire   [0:0] icmp_ln69_2_fu_355_p2;
reg   [0:0] icmp_ln69_2_reg_538;
wire   [6:0] val_5_fu_389_p3;
reg   [6:0] val_5_reg_563;
reg   [6:0] val_5_reg_563_pp0_iter4_reg;
reg   [6:0] val_6_reg_568;
reg  signed [7:0] b3_dw_weight_load_reg_578;
wire  signed [16:0] grp_fu_446_p3;
reg  signed [16:0] acc_2_reg_603;
wire  signed [22:0] sext_ln65_2_fu_433_p1;
reg   [7:0] ref_tmp19_i2_reg_613;
wire    ap_block_pp0_stage0_11001_ignoreCallOp112;
reg    grp_requantize_fu_163_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp107;
wire    ap_block_pp0_stage0_ignoreCallOp107;
wire   [63:0] zext_ln72_7_fu_303_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln70_4_fu_336_p1;
wire   [63:0] zext_ln70_6_fu_366_p1;
wire   [63:0] zext_ln70_fu_371_p1;
wire   [63:0] zext_ln72_6_fu_380_p1;
reg   [3:0] t_fu_64;
wire    ap_loop_init;
reg   [5:0] c_fu_68;
reg   [8:0] indvar_flatten41_fu_72;
wire   [8:0] add_ln63_fu_196_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten41_load;
reg    b3_dw_weight_ce2_local;
reg    b3_dw_weight_ce1_local;
reg    b3_dw_weight_ce0_local;
reg    buf_b2_pool_ce2_local;
reg    buf_b2_pool_ce1_local;
reg    buf_b2_pool_ce0_local;
reg    buf_b3_dw_we0_local;
reg    buf_b3_dw_ce0_local;
wire   [0:0] icmp_ln64_fu_213_p2;
wire   [5:0] empty_fu_227_p3;
wire   [7:0] p_shl4_fu_267_p3;
wire   [7:0] zext_ln63_fu_264_p1;
wire   [8:0] p_shl_fu_284_p3;
wire   [8:0] zext_ln72_fu_261_p1;
wire   [6:0] add_ln72_4_fu_297_p2;
wire   [4:0] zext_ln64_2_fu_311_p1;
wire  signed [4:0] add_ln67_fu_314_p2;
wire  signed [8:0] sext_ln69_fu_320_p1;
wire   [8:0] sub_ln72_2_fu_291_p2;
wire   [8:0] add_ln70_fu_330_p2;
wire   [8:0] zext_ln64_fu_308_p1;
wire   [8:0] add_ln70_3_fu_341_p2;
wire   [8:0] zext_ln69_fu_352_p1;
wire   [8:0] add_ln70_4_fu_360_p2;
wire   [6:0] add_ln72_fu_375_p2;
wire   [6:0] val_8_fu_396_p3;
wire   [6:0] acc_fu_420_p0;
wire  signed [14:0] acc_fu_420_p2;
wire  signed [15:0] grp_fu_437_p3;
wire   [6:0] grp_fu_437_p1;
wire   [6:0] grp_fu_446_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] acc_fu_420_p00;
wire   [14:0] grp_fu_437_p10;
wire   [14:0] grp_fu_446_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 t_fu_64 = 4'd0;
#0 c_fu_68 = 6'd0;
#0 indvar_flatten41_fu_72 = 9'd0;
#0 ap_done_reg = 1'b0;
end

cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_64_24_b3_dw_weight_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
b3_dw_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b3_dw_weight_address0),
    .ce0(b3_dw_weight_ce0_local),
    .q0(b3_dw_weight_q0),
    .address1(b3_dw_weight_address1),
    .ce1(b3_dw_weight_ce1_local),
    .q1(b3_dw_weight_q1),
    .address2(b3_dw_weight_address2),
    .ce2(b3_dw_weight_ce2_local),
    .q2(b3_dw_weight_q2)
);

cnn_forward_mul_7ns_8s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_7ns_8s_15_1_1_U85(
    .din0(acc_fu_420_p0),
    .din1(b3_dw_weight_load_reg_578),
    .dout(acc_fu_420_p2)
);

cnn_forward_mac_muladd_8s_7ns_15s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_7ns_15s_16_4_1_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b3_dw_weight_q2),
    .din1(grp_fu_437_p1),
    .din2(acc_fu_420_p2),
    .ce(1'b1),
    .dout(grp_fu_437_p3)
);

cnn_forward_mac_muladd_8s_7ns_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_7ns_16s_17_4_1_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b3_dw_weight_q0),
    .din1(grp_fu_446_p1),
    .din2(grp_fu_437_p3),
    .ce(1'b1),
    .dout(grp_fu_446_p3)
);

cnn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_68 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_fu_68 <= add_ln63_2_fu_235_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln63_fu_190_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten41_fu_72 <= add_ln63_fu_196_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten41_fu_72 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_fu_64 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            t_fu_64 <= add_ln67_2_fu_245_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        acc_2_reg_603 <= grp_fu_446_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln63_2_reg_485 <= add_ln63_2_fu_235_p2;
        add_ln67_2_reg_497 <= add_ln67_2_fu_245_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln63_reg_479 <= select_ln63_fu_219_p3;
        trunc_ln72_reg_492 <= trunc_ln72_fu_241_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln69_2_reg_538 <= icmp_ln69_2_fu_355_p2;
        icmp_ln69_reg_518 <= icmp_ln69_fu_324_p2;
        sub_ln72_reg_503 <= sub_ln72_fu_274_p2;
        trunc_ln70_reg_508 <= trunc_ln70_fu_280_p1;
        val_5_reg_563 <= val_5_fu_389_p3;
        val_5_reg_563_pp0_iter4_reg <= val_5_reg_563;
        zext_ln70_5_reg_528[8 : 0] <= zext_ln70_5_fu_347_p1[8 : 0];
        zext_ln70_5_reg_528_pp0_iter10_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter9_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter11_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter10_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter12_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter11_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter13_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter12_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter3_reg[8 : 0] <= zext_ln70_5_reg_528[8 : 0];
        zext_ln70_5_reg_528_pp0_iter4_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter3_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter5_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter4_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter6_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter5_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter7_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter6_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter8_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter7_reg[8 : 0];
        zext_ln70_5_reg_528_pp0_iter9_reg[8 : 0] <= zext_ln70_5_reg_528_pp0_iter8_reg[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        b3_dw_weight_load_reg_578 <= b3_dw_weight_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp112)) begin
        ref_tmp19_i2_reg_613 <= grp_requantize_fu_466_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        val_6_reg_568 <= buf_b2_pool_q1;
    end
end

always @ (*) begin
    if (((icmp_ln63_fu_190_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten41_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten41_load = indvar_flatten41_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b3_dw_weight_ce0_local = 1'b1;
    end else begin
        b3_dw_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b3_dw_weight_ce1_local = 1'b1;
    end else begin
        b3_dw_weight_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b3_dw_weight_ce2_local = 1'b1;
    end else begin
        b3_dw_weight_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_b2_pool_ce0_local = 1'b1;
    end else begin
        buf_b2_pool_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_b2_pool_ce1_local = 1'b1;
    end else begin
        buf_b2_pool_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_b2_pool_ce2_local = 1'b1;
    end else begin
        buf_b2_pool_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        buf_b3_dw_ce0_local = 1'b1;
    end else begin
        buf_b3_dw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        buf_b3_dw_we0_local = 1'b1;
    end else begin
        buf_b3_dw_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp107)) begin
        grp_requantize_fu_163_ap_ce = 1'b1;
    end else begin
        grp_requantize_fu_163_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_420_p0 = acc_fu_420_p00;

assign acc_fu_420_p00 = val_5_reg_563_pp0_iter4_reg;

assign add_ln63_2_fu_235_p2 = (c_fu_68 + empty_fu_227_p3);

assign add_ln63_fu_196_p2 = (ap_sig_allocacmp_indvar_flatten41_load + 9'd1);

assign add_ln67_2_fu_245_p2 = (select_ln63_fu_219_p3 + 4'd1);

assign add_ln67_fu_314_p2 = ($signed(zext_ln64_2_fu_311_p1) + $signed(5'd31));

assign add_ln70_3_fu_341_p2 = (zext_ln64_fu_308_p1 + sub_ln72_2_fu_291_p2);

assign add_ln70_4_fu_360_p2 = (zext_ln69_fu_352_p1 + sub_ln72_2_fu_291_p2);

assign add_ln70_fu_330_p2 = ($signed(sext_ln69_fu_320_p1) + $signed(sub_ln72_2_fu_291_p2));

assign add_ln72_4_fu_297_p2 = (trunc_ln70_fu_280_p1 + 7'd2);

assign add_ln72_fu_375_p2 = (trunc_ln70_reg_508 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp107 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp112 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp107 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b3_dw_weight_address0 = zext_ln72_6_fu_380_p1;

assign b3_dw_weight_address1 = zext_ln70_fu_371_p1;

assign b3_dw_weight_address2 = zext_ln72_7_fu_303_p1;

assign buf_b2_pool_address0 = zext_ln70_6_fu_366_p1;

assign buf_b2_pool_address1 = zext_ln70_5_fu_347_p1;

assign buf_b2_pool_address2 = zext_ln70_4_fu_336_p1;

assign buf_b2_pool_ce0 = buf_b2_pool_ce0_local;

assign buf_b2_pool_ce1 = buf_b2_pool_ce1_local;

assign buf_b2_pool_ce2 = buf_b2_pool_ce2_local;

assign buf_b3_dw_address0 = zext_ln70_5_reg_528_pp0_iter13_reg;

assign buf_b3_dw_ce0 = buf_b3_dw_ce0_local;

assign buf_b3_dw_d0 = ref_tmp19_i2_reg_613;

assign buf_b3_dw_we0 = buf_b3_dw_we0_local;

assign empty_fu_227_p3 = ((icmp_ln64_fu_213_p2[0:0] == 1'b1) ? 6'd1 : 6'd0);

assign grp_fu_437_p1 = grp_fu_437_p10;

assign grp_fu_437_p10 = val_8_fu_396_p3;

assign grp_fu_446_p1 = grp_fu_446_p10;

assign grp_fu_446_p10 = val_6_reg_568;

assign grp_requantize_fu_466_p_ce = grp_requantize_fu_163_ap_ce;

assign grp_requantize_fu_466_p_din1 = sext_ln65_2_fu_433_p1;

assign grp_requantize_fu_466_p_din2 = 31'd25696904;

assign grp_requantize_fu_466_p_din3 = 2'd3;

assign icmp_ln63_fu_190_p2 = ((ap_sig_allocacmp_indvar_flatten41_load == 9'd480) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_213_p2 = ((t_fu_64 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln69_2_fu_355_p2 = ((add_ln67_2_reg_497 != 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_324_p2 = ((add_ln67_fu_314_p2 < 5'd15) ? 1'b1 : 1'b0);

assign p_shl4_fu_267_p3 = {{add_ln63_2_reg_485}, {2'd0}};

assign p_shl_fu_284_p3 = {{trunc_ln72_reg_492}, {4'd0}};

assign select_ln63_fu_219_p3 = ((icmp_ln64_fu_213_p2[0:0] == 1'b1) ? 4'd0 : t_fu_64);

assign sext_ln65_2_fu_433_p1 = acc_2_reg_603;

assign sext_ln69_fu_320_p1 = add_ln67_fu_314_p2;

assign sub_ln72_2_fu_291_p2 = (p_shl_fu_284_p3 - zext_ln72_fu_261_p1);

assign sub_ln72_fu_274_p2 = (p_shl4_fu_267_p3 - zext_ln63_fu_264_p1);

assign trunc_ln70_fu_280_p1 = sub_ln72_fu_274_p2[6:0];

assign trunc_ln72_fu_241_p1 = add_ln63_2_fu_235_p2[4:0];

assign val_5_fu_389_p3 = ((icmp_ln69_reg_518[0:0] == 1'b1) ? buf_b2_pool_q2 : 7'd0);

assign val_8_fu_396_p3 = ((icmp_ln69_2_reg_538[0:0] == 1'b1) ? buf_b2_pool_q0 : 7'd0);

assign zext_ln63_fu_264_p1 = add_ln63_2_reg_485;

assign zext_ln64_2_fu_311_p1 = select_ln63_reg_479;

assign zext_ln64_fu_308_p1 = select_ln63_reg_479;

assign zext_ln69_fu_352_p1 = add_ln67_2_reg_497;

assign zext_ln70_4_fu_336_p1 = add_ln70_fu_330_p2;

assign zext_ln70_5_fu_347_p1 = add_ln70_3_fu_341_p2;

assign zext_ln70_6_fu_366_p1 = add_ln70_4_fu_360_p2;

assign zext_ln70_fu_371_p1 = sub_ln72_reg_503;

assign zext_ln72_6_fu_380_p1 = add_ln72_fu_375_p2;

assign zext_ln72_7_fu_303_p1 = add_ln72_4_fu_297_p2;

assign zext_ln72_fu_261_p1 = add_ln63_2_reg_485;

always @ (posedge ap_clk) begin
    zext_ln70_5_reg_528[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter3_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter4_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter5_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter6_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter7_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter8_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter9_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter10_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter11_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter12_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln70_5_reg_528_pp0_iter13_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_64_24
