// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_201_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_b4_pw_address0,
        buf_b4_pw_ce0,
        buf_b4_pw_q0,
        buf_b4_pw_address1,
        buf_b4_pw_ce1,
        buf_b4_pw_q1,
        buf_b4_pw_address2,
        buf_b4_pw_ce2,
        buf_b4_pw_q2,
        buf_b4_pw_address3,
        buf_b4_pw_ce3,
        buf_b4_pw_q3,
        buf_b4_pw_address4,
        buf_b4_pw_ce4,
        buf_b4_pw_q4,
        buf_b4_pw_address5,
        buf_b4_pw_ce5,
        buf_b4_pw_q5,
        buf_b4_pw_address6,
        buf_b4_pw_ce6,
        buf_b4_pw_q6,
        buf_max_pool_address0,
        buf_max_pool_ce0,
        buf_max_pool_we0,
        buf_max_pool_d0,
        grp_requantize_fu_466_p_din1,
        grp_requantize_fu_466_p_din2,
        grp_requantize_fu_466_p_din3,
        grp_requantize_fu_466_p_dout0,
        grp_requantize_fu_466_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] buf_b4_pw_address0;
output   buf_b4_pw_ce0;
input  [6:0] buf_b4_pw_q0;
output  [9:0] buf_b4_pw_address1;
output   buf_b4_pw_ce1;
input  [6:0] buf_b4_pw_q1;
output  [9:0] buf_b4_pw_address2;
output   buf_b4_pw_ce2;
input  [6:0] buf_b4_pw_q2;
output  [9:0] buf_b4_pw_address3;
output   buf_b4_pw_ce3;
input  [6:0] buf_b4_pw_q3;
output  [9:0] buf_b4_pw_address4;
output   buf_b4_pw_ce4;
input  [6:0] buf_b4_pw_q4;
output  [9:0] buf_b4_pw_address5;
output   buf_b4_pw_ce5;
input  [6:0] buf_b4_pw_q5;
output  [9:0] buf_b4_pw_address6;
output   buf_b4_pw_ce6;
input  [6:0] buf_b4_pw_q6;
output  [6:0] buf_max_pool_address0;
output   buf_max_pool_ce0;
output   buf_max_pool_we0;
output  [7:0] buf_max_pool_d0;
output  [22:0] grp_requantize_fu_466_p_din1;
output  [30:0] grp_requantize_fu_466_p_din2;
output  [1:0] grp_requantize_fu_466_p_din3;
input  [7:0] grp_requantize_fu_466_p_dout0;
output   grp_requantize_fu_466_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln201_fu_171_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] c_1_reg_356;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] c_1_reg_356_pp0_iter1_reg;
reg   [7:0] c_1_reg_356_pp0_iter2_reg;
reg   [7:0] c_1_reg_356_pp0_iter3_reg;
reg   [7:0] c_1_reg_356_pp0_iter4_reg;
reg   [7:0] c_1_reg_356_pp0_iter5_reg;
reg   [7:0] c_1_reg_356_pp0_iter6_reg;
reg   [7:0] c_1_reg_356_pp0_iter7_reg;
reg   [7:0] c_1_reg_356_pp0_iter8_reg;
reg   [7:0] c_1_reg_356_pp0_iter9_reg;
reg   [7:0] c_1_reg_356_pp0_iter10_reg;
reg   [7:0] c_1_reg_356_pp0_iter11_reg;
wire   [9:0] sub_ln204_fu_199_p2;
reg   [9:0] sub_ln204_reg_365;
reg   [6:0] val_21_reg_380;
wire   [6:0] max_val_1_fu_280_p3;
reg   [6:0] max_val_1_reg_416;
reg   [6:0] val_16_reg_422;
reg   [6:0] val_17_reg_428;
reg   [6:0] val_18_reg_434;
reg   [6:0] val_18_reg_434_pp0_iter3_reg;
reg   [6:0] val_19_reg_440;
reg   [6:0] val_19_reg_440_pp0_iter3_reg;
reg   [6:0] val_20_reg_446;
reg   [6:0] val_20_reg_446_pp0_iter3_reg;
reg   [6:0] val_20_reg_446_pp0_iter4_reg;
wire   [6:0] max_val_3_fu_302_p3;
reg   [6:0] max_val_3_reg_452;
wire   [6:0] max_val_5_fu_324_p3;
reg   [6:0] max_val_5_reg_458;
wire   [6:0] max_val_6_fu_335_p3;
reg   [6:0] max_val_6_reg_464;
wire   [22:0] zext_ln209_fu_341_p1;
reg   [7:0] ref_tmp_i_reg_474;
wire    ap_block_pp0_stage0_11001_ignoreCallOp80;
reg    grp_requantize_fu_154_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp75;
wire    ap_block_pp0_stage0_ignoreCallOp75;
wire   [63:0] zext_ln204_fu_205_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln204_1_fu_220_p1;
wire   [63:0] zext_ln204_2_fu_230_p1;
wire   [63:0] zext_ln204_3_fu_240_p1;
wire   [63:0] zext_ln204_4_fu_250_p1;
wire   [63:0] zext_ln204_5_fu_260_p1;
wire   [63:0] zext_ln204_6_fu_270_p1;
wire   [63:0] zext_ln201_fu_345_p1;
reg   [7:0] c_fu_52;
wire   [7:0] add_ln201_fu_177_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_c_1;
reg    buf_b4_pw_ce6_local;
reg    buf_b4_pw_ce5_local;
reg    buf_b4_pw_ce4_local;
reg    buf_b4_pw_ce3_local;
reg    buf_b4_pw_ce2_local;
reg    buf_b4_pw_ce1_local;
reg    buf_b4_pw_ce0_local;
reg    buf_max_pool_we0_local;
reg    buf_max_pool_ce0_local;
wire   [6:0] trunc_ln204_fu_187_p1;
wire   [9:0] p_shl_fu_191_p3;
wire   [9:0] zext_ln201_1_fu_183_p1;
wire   [9:0] add_ln204_fu_215_p2;
wire   [9:0] add_ln204_1_fu_225_p2;
wire   [9:0] add_ln204_2_fu_235_p2;
wire   [9:0] add_ln204_3_fu_245_p2;
wire   [9:0] add_ln204_4_fu_255_p2;
wire   [9:0] add_ln204_5_fu_265_p2;
wire   [0:0] icmp_ln205_fu_275_p2;
wire   [0:0] icmp_ln205_1_fu_287_p2;
wire   [6:0] max_val_2_fu_291_p3;
wire   [0:0] icmp_ln205_2_fu_297_p2;
wire   [0:0] icmp_ln205_3_fu_309_p2;
wire   [6:0] max_val_4_fu_313_p3;
wire   [0:0] icmp_ln205_4_fu_319_p2;
wire   [0:0] icmp_ln205_5_fu_331_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 c_fu_52 = 8'd0;
#0 ap_done_reg = 1'b0;
end

cnn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln201_fu_171_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_52 <= add_ln201_fu_177_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_52 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        c_1_reg_356_pp0_iter10_reg <= c_1_reg_356_pp0_iter9_reg;
        c_1_reg_356_pp0_iter11_reg <= c_1_reg_356_pp0_iter10_reg;
        c_1_reg_356_pp0_iter2_reg <= c_1_reg_356_pp0_iter1_reg;
        c_1_reg_356_pp0_iter3_reg <= c_1_reg_356_pp0_iter2_reg;
        c_1_reg_356_pp0_iter4_reg <= c_1_reg_356_pp0_iter3_reg;
        c_1_reg_356_pp0_iter5_reg <= c_1_reg_356_pp0_iter4_reg;
        c_1_reg_356_pp0_iter6_reg <= c_1_reg_356_pp0_iter5_reg;
        c_1_reg_356_pp0_iter7_reg <= c_1_reg_356_pp0_iter6_reg;
        c_1_reg_356_pp0_iter8_reg <= c_1_reg_356_pp0_iter7_reg;
        c_1_reg_356_pp0_iter9_reg <= c_1_reg_356_pp0_iter8_reg;
        max_val_1_reg_416 <= max_val_1_fu_280_p3;
        max_val_3_reg_452 <= max_val_3_fu_302_p3;
        max_val_5_reg_458 <= max_val_5_fu_324_p3;
        max_val_6_reg_464 <= max_val_6_fu_335_p3;
        val_18_reg_434_pp0_iter3_reg <= val_18_reg_434;
        val_19_reg_440_pp0_iter3_reg <= val_19_reg_440;
        val_20_reg_446_pp0_iter3_reg <= val_20_reg_446;
        val_20_reg_446_pp0_iter4_reg <= val_20_reg_446_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        c_1_reg_356 <= ap_sig_allocacmp_c_1;
        c_1_reg_356_pp0_iter1_reg <= c_1_reg_356;
        sub_ln204_reg_365 <= sub_ln204_fu_199_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp80)) begin
        ref_tmp_i_reg_474 <= grp_requantize_fu_466_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        val_16_reg_422 <= buf_b4_pw_q4;
        val_17_reg_428 <= buf_b4_pw_q3;
        val_18_reg_434 <= buf_b4_pw_q2;
        val_19_reg_440 <= buf_b4_pw_q1;
        val_20_reg_446 <= buf_b4_pw_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        val_21_reg_380 <= buf_b4_pw_q6;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_171_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_c_1 = c_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce0_local = 1'b1;
    end else begin
        buf_b4_pw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce1_local = 1'b1;
    end else begin
        buf_b4_pw_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce2_local = 1'b1;
    end else begin
        buf_b4_pw_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce3_local = 1'b1;
    end else begin
        buf_b4_pw_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce4_local = 1'b1;
    end else begin
        buf_b4_pw_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce5_local = 1'b1;
    end else begin
        buf_b4_pw_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_b4_pw_ce6_local = 1'b1;
    end else begin
        buf_b4_pw_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        buf_max_pool_ce0_local = 1'b1;
    end else begin
        buf_max_pool_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        buf_max_pool_we0_local = 1'b1;
    end else begin
        buf_max_pool_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp75)) begin
        grp_requantize_fu_154_ap_ce = 1'b1;
    end else begin
        grp_requantize_fu_154_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln201_fu_177_p2 = (ap_sig_allocacmp_c_1 + 8'd1);

assign add_ln204_1_fu_225_p2 = (sub_ln204_reg_365 + 10'd2);

assign add_ln204_2_fu_235_p2 = (sub_ln204_reg_365 + 10'd3);

assign add_ln204_3_fu_245_p2 = (sub_ln204_reg_365 + 10'd4);

assign add_ln204_4_fu_255_p2 = (sub_ln204_reg_365 + 10'd5);

assign add_ln204_5_fu_265_p2 = (sub_ln204_reg_365 + 10'd6);

assign add_ln204_fu_215_p2 = (sub_ln204_reg_365 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp75 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp80 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp75 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_b4_pw_address0 = zext_ln204_6_fu_270_p1;

assign buf_b4_pw_address1 = zext_ln204_5_fu_260_p1;

assign buf_b4_pw_address2 = zext_ln204_4_fu_250_p1;

assign buf_b4_pw_address3 = zext_ln204_3_fu_240_p1;

assign buf_b4_pw_address4 = zext_ln204_2_fu_230_p1;

assign buf_b4_pw_address5 = zext_ln204_1_fu_220_p1;

assign buf_b4_pw_address6 = zext_ln204_fu_205_p1;

assign buf_b4_pw_ce0 = buf_b4_pw_ce0_local;

assign buf_b4_pw_ce1 = buf_b4_pw_ce1_local;

assign buf_b4_pw_ce2 = buf_b4_pw_ce2_local;

assign buf_b4_pw_ce3 = buf_b4_pw_ce3_local;

assign buf_b4_pw_ce4 = buf_b4_pw_ce4_local;

assign buf_b4_pw_ce5 = buf_b4_pw_ce5_local;

assign buf_b4_pw_ce6 = buf_b4_pw_ce6_local;

assign buf_max_pool_address0 = zext_ln201_fu_345_p1;

assign buf_max_pool_ce0 = buf_max_pool_ce0_local;

assign buf_max_pool_d0 = ref_tmp_i_reg_474;

assign buf_max_pool_we0 = buf_max_pool_we0_local;

assign grp_requantize_fu_466_p_ce = grp_requantize_fu_154_ap_ce;

assign grp_requantize_fu_466_p_din1 = zext_ln209_fu_341_p1;

assign grp_requantize_fu_466_p_din2 = 31'd1073741824;

assign grp_requantize_fu_466_p_din3 = 2'd2;

assign icmp_ln201_fu_171_p2 = ((ap_sig_allocacmp_c_1 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln205_1_fu_287_p2 = ((val_16_reg_422 > max_val_1_reg_416) ? 1'b1 : 1'b0);

assign icmp_ln205_2_fu_297_p2 = ((val_17_reg_428 > max_val_2_fu_291_p3) ? 1'b1 : 1'b0);

assign icmp_ln205_3_fu_309_p2 = ((val_18_reg_434_pp0_iter3_reg > max_val_3_reg_452) ? 1'b1 : 1'b0);

assign icmp_ln205_4_fu_319_p2 = ((val_19_reg_440_pp0_iter3_reg > max_val_4_fu_313_p3) ? 1'b1 : 1'b0);

assign icmp_ln205_5_fu_331_p2 = ((val_20_reg_446_pp0_iter4_reg > max_val_5_reg_458) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_275_p2 = ((buf_b4_pw_q5 > val_21_reg_380) ? 1'b1 : 1'b0);

assign max_val_1_fu_280_p3 = ((icmp_ln205_fu_275_p2[0:0] == 1'b1) ? buf_b4_pw_q5 : val_21_reg_380);

assign max_val_2_fu_291_p3 = ((icmp_ln205_1_fu_287_p2[0:0] == 1'b1) ? val_16_reg_422 : max_val_1_reg_416);

assign max_val_3_fu_302_p3 = ((icmp_ln205_2_fu_297_p2[0:0] == 1'b1) ? val_17_reg_428 : max_val_2_fu_291_p3);

assign max_val_4_fu_313_p3 = ((icmp_ln205_3_fu_309_p2[0:0] == 1'b1) ? val_18_reg_434_pp0_iter3_reg : max_val_3_reg_452);

assign max_val_5_fu_324_p3 = ((icmp_ln205_4_fu_319_p2[0:0] == 1'b1) ? val_19_reg_440_pp0_iter3_reg : max_val_4_fu_313_p3);

assign max_val_6_fu_335_p3 = ((icmp_ln205_5_fu_331_p2[0:0] == 1'b1) ? val_20_reg_446_pp0_iter4_reg : max_val_5_reg_458);

assign p_shl_fu_191_p3 = {{trunc_ln204_fu_187_p1}, {3'd0}};

assign sub_ln204_fu_199_p2 = (p_shl_fu_191_p3 - zext_ln201_1_fu_183_p1);

assign trunc_ln204_fu_187_p1 = ap_sig_allocacmp_c_1[6:0];

assign zext_ln201_1_fu_183_p1 = ap_sig_allocacmp_c_1;

assign zext_ln201_fu_345_p1 = c_1_reg_356_pp0_iter11_reg;

assign zext_ln204_1_fu_220_p1 = add_ln204_fu_215_p2;

assign zext_ln204_2_fu_230_p1 = add_ln204_1_fu_225_p2;

assign zext_ln204_3_fu_240_p1 = add_ln204_2_fu_235_p2;

assign zext_ln204_4_fu_250_p1 = add_ln204_3_fu_245_p2;

assign zext_ln204_5_fu_260_p1 = add_ln204_4_fu_255_p2;

assign zext_ln204_6_fu_270_p1 = add_ln204_5_fu_265_p2;

assign zext_ln204_fu_205_p1 = sub_ln204_fu_199_p2;

assign zext_ln209_fu_341_p1 = max_val_6_reg_464;

endmodule //cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_201_1
