// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_requantize (
        ap_clk,
        ap_rst,
        acc,
        multiplier,
        shift,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [22:0] acc;
input  [30:0] multiplier;
input  [1:0] shift;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

reg  signed [1:0] shift_read_reg_164;
wire    ap_block_pp0_stage0_11001;
reg  signed [1:0] shift_read_reg_164_pp0_iter1_reg;
reg  signed [1:0] shift_read_reg_164_pp0_iter2_reg;
wire   [52:0] grp_fu_58_p2;
reg   [52:0] acc64_reg_180;
wire   [2:0] add_ln29_fu_75_p2;
reg   [2:0] add_ln29_reg_185;
wire   [52:0] acc64_1_fu_98_p2;
reg   [52:0] acc64_1_reg_190;
wire   [52:0] ashr_ln32_fu_110_p2;
reg   [52:0] ashr_ln32_reg_195;
reg   [45:0] tmp_reg_200;
wire   [0:0] icmp_ln37_fu_129_p2;
reg   [0:0] icmp_ln37_reg_205;
wire   [30:0] grp_fu_58_p0;
wire    ap_block_pp0_stage0;
wire  signed [2:0] sext_ln24_fu_72_p1;
wire  signed [4:0] sext_ln29_fu_81_p1;
wire   [30:0] zext_ln29_fu_84_p1;
wire   [30:0] rounding_offset_fu_88_p2;
wire   [52:0] zext_ln29_1_fu_94_p1;
wire  signed [4:0] sext_ln32_fu_103_p1;
wire   [52:0] zext_ln32_fu_106_p1;
wire   [22:0] trunc_ln36_fu_115_p1;
wire   [0:0] icmp_ln36_fu_135_p2;
wire   [0:0] or_ln39_fu_151_p2;
wire   [7:0] select_ln39_fu_143_p3;
wire   [7:0] trunc_ln39_fu_140_p1;
reg    grp_fu_58_ce;
wire   [7:0] select_ln39_1_fu_156_p3;
reg    ap_ce_reg;
reg  signed [22:0] acc_int_reg;
reg   [30:0] multiplier_int_reg;
reg   [1:0] shift_int_reg;
reg   [7:0] ap_return_int_reg;
wire   [52:0] grp_fu_58_p00;

cnn_forward_mul_31ns_23s_53_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 53 ))
mul_31ns_23s_53_2_0_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_58_p0),
    .din1(acc_int_reg),
    .ce(grp_fu_58_ce),
    .dout(grp_fu_58_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc64_1_reg_190 <= acc64_1_fu_98_p2;
        acc64_reg_180 <= grp_fu_58_p2;
        add_ln29_reg_185 <= add_ln29_fu_75_p2;
        ashr_ln32_reg_195 <= ashr_ln32_fu_110_p2;
        icmp_ln37_reg_205 <= icmp_ln37_fu_129_p2;
        shift_read_reg_164 <= shift_int_reg;
        shift_read_reg_164_pp0_iter1_reg <= shift_read_reg_164;
        shift_read_reg_164_pp0_iter2_reg <= shift_read_reg_164_pp0_iter1_reg;
        tmp_reg_200 <= {{ashr_ln32_fu_110_p2[52:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        acc_int_reg <= acc;
        multiplier_int_reg <= multiplier;
        shift_int_reg <= shift;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln39_1_fu_156_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln39_1_fu_156_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_58_ce = 1'b1;
    end else begin
        grp_fu_58_ce = 1'b0;
    end
end

assign acc64_1_fu_98_p2 = (zext_ln29_1_fu_94_p1 + acc64_reg_180);

assign add_ln29_fu_75_p2 = ($signed(sext_ln24_fu_72_p1) + $signed(3'd7));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ashr_ln32_fu_110_p2 = $signed(acc64_1_reg_190) >>> zext_ln32_fu_106_p1;

assign grp_fu_58_p0 = grp_fu_58_p00;

assign grp_fu_58_p00 = multiplier_int_reg;

assign icmp_ln36_fu_135_p2 = (($signed(tmp_reg_200) > $signed(46'd0)) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_129_p2 = (($signed(trunc_ln36_fu_115_p1) < $signed(23'd8388480)) ? 1'b1 : 1'b0);

assign or_ln39_fu_151_p2 = (icmp_ln37_reg_205 | icmp_ln36_fu_135_p2);

assign rounding_offset_fu_88_p2 = 31'd1 << zext_ln29_fu_84_p1;

assign select_ln39_1_fu_156_p3 = ((or_ln39_fu_151_p2[0:0] == 1'b1) ? select_ln39_fu_143_p3 : trunc_ln39_fu_140_p1);

assign select_ln39_fu_143_p3 = ((icmp_ln36_fu_135_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln24_fu_72_p1 = shift_read_reg_164;

assign sext_ln29_fu_81_p1 = $signed(add_ln29_reg_185);

assign sext_ln32_fu_103_p1 = shift_read_reg_164_pp0_iter2_reg;

assign trunc_ln36_fu_115_p1 = ashr_ln32_fu_110_p2[22:0];

assign trunc_ln39_fu_140_p1 = ashr_ln32_reg_195[7:0];

assign zext_ln29_1_fu_94_p1 = rounding_offset_fu_88_p2;

assign zext_ln29_fu_84_p1 = $unsigned(sext_ln29_fu_81_p1);

assign zext_ln32_fu_106_p1 = $unsigned(sext_ln32_fu_103_p1);

endmodule //cnn_forward_requantize
