// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_64_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_IN_0_AWVALID,
        m_axi_DATA_IN_0_AWREADY,
        m_axi_DATA_IN_0_AWADDR,
        m_axi_DATA_IN_0_AWID,
        m_axi_DATA_IN_0_AWLEN,
        m_axi_DATA_IN_0_AWSIZE,
        m_axi_DATA_IN_0_AWBURST,
        m_axi_DATA_IN_0_AWLOCK,
        m_axi_DATA_IN_0_AWCACHE,
        m_axi_DATA_IN_0_AWPROT,
        m_axi_DATA_IN_0_AWQOS,
        m_axi_DATA_IN_0_AWREGION,
        m_axi_DATA_IN_0_AWUSER,
        m_axi_DATA_IN_0_WVALID,
        m_axi_DATA_IN_0_WREADY,
        m_axi_DATA_IN_0_WDATA,
        m_axi_DATA_IN_0_WSTRB,
        m_axi_DATA_IN_0_WLAST,
        m_axi_DATA_IN_0_WID,
        m_axi_DATA_IN_0_WUSER,
        m_axi_DATA_IN_0_ARVALID,
        m_axi_DATA_IN_0_ARREADY,
        m_axi_DATA_IN_0_ARADDR,
        m_axi_DATA_IN_0_ARID,
        m_axi_DATA_IN_0_ARLEN,
        m_axi_DATA_IN_0_ARSIZE,
        m_axi_DATA_IN_0_ARBURST,
        m_axi_DATA_IN_0_ARLOCK,
        m_axi_DATA_IN_0_ARCACHE,
        m_axi_DATA_IN_0_ARPROT,
        m_axi_DATA_IN_0_ARQOS,
        m_axi_DATA_IN_0_ARREGION,
        m_axi_DATA_IN_0_ARUSER,
        m_axi_DATA_IN_0_RVALID,
        m_axi_DATA_IN_0_RREADY,
        m_axi_DATA_IN_0_RDATA,
        m_axi_DATA_IN_0_RLAST,
        m_axi_DATA_IN_0_RID,
        m_axi_DATA_IN_0_RFIFONUM,
        m_axi_DATA_IN_0_RUSER,
        m_axi_DATA_IN_0_RRESP,
        m_axi_DATA_IN_0_BVALID,
        m_axi_DATA_IN_0_BREADY,
        m_axi_DATA_IN_0_BRESP,
        m_axi_DATA_IN_0_BID,
        m_axi_DATA_IN_0_BUSER,
        buf_b1_dw_address0,
        buf_b1_dw_ce0,
        buf_b1_dw_we0,
        buf_b1_dw_d0,
        input_r,
        grp_requantize_fu_466_p_din1,
        grp_requantize_fu_466_p_din2,
        grp_requantize_fu_466_p_din3,
        grp_requantize_fu_466_p_dout0,
        grp_requantize_fu_466_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_IN_0_AWVALID;
input   m_axi_DATA_IN_0_AWREADY;
output  [63:0] m_axi_DATA_IN_0_AWADDR;
output  [0:0] m_axi_DATA_IN_0_AWID;
output  [31:0] m_axi_DATA_IN_0_AWLEN;
output  [2:0] m_axi_DATA_IN_0_AWSIZE;
output  [1:0] m_axi_DATA_IN_0_AWBURST;
output  [1:0] m_axi_DATA_IN_0_AWLOCK;
output  [3:0] m_axi_DATA_IN_0_AWCACHE;
output  [2:0] m_axi_DATA_IN_0_AWPROT;
output  [3:0] m_axi_DATA_IN_0_AWQOS;
output  [3:0] m_axi_DATA_IN_0_AWREGION;
output  [0:0] m_axi_DATA_IN_0_AWUSER;
output   m_axi_DATA_IN_0_WVALID;
input   m_axi_DATA_IN_0_WREADY;
output  [7:0] m_axi_DATA_IN_0_WDATA;
output  [0:0] m_axi_DATA_IN_0_WSTRB;
output   m_axi_DATA_IN_0_WLAST;
output  [0:0] m_axi_DATA_IN_0_WID;
output  [0:0] m_axi_DATA_IN_0_WUSER;
output   m_axi_DATA_IN_0_ARVALID;
input   m_axi_DATA_IN_0_ARREADY;
output  [63:0] m_axi_DATA_IN_0_ARADDR;
output  [0:0] m_axi_DATA_IN_0_ARID;
output  [31:0] m_axi_DATA_IN_0_ARLEN;
output  [2:0] m_axi_DATA_IN_0_ARSIZE;
output  [1:0] m_axi_DATA_IN_0_ARBURST;
output  [1:0] m_axi_DATA_IN_0_ARLOCK;
output  [3:0] m_axi_DATA_IN_0_ARCACHE;
output  [2:0] m_axi_DATA_IN_0_ARPROT;
output  [3:0] m_axi_DATA_IN_0_ARQOS;
output  [3:0] m_axi_DATA_IN_0_ARREGION;
output  [0:0] m_axi_DATA_IN_0_ARUSER;
input   m_axi_DATA_IN_0_RVALID;
output   m_axi_DATA_IN_0_RREADY;
input  [7:0] m_axi_DATA_IN_0_RDATA;
input   m_axi_DATA_IN_0_RLAST;
input  [0:0] m_axi_DATA_IN_0_RID;
input  [10:0] m_axi_DATA_IN_0_RFIFONUM;
input  [0:0] m_axi_DATA_IN_0_RUSER;
input  [1:0] m_axi_DATA_IN_0_RRESP;
input   m_axi_DATA_IN_0_BVALID;
output   m_axi_DATA_IN_0_BREADY;
input  [1:0] m_axi_DATA_IN_0_BRESP;
input  [0:0] m_axi_DATA_IN_0_BID;
input  [0:0] m_axi_DATA_IN_0_BUSER;
output  [10:0] buf_b1_dw_address0;
output   buf_b1_dw_ce0;
output   buf_b1_dw_we0;
output  [7:0] buf_b1_dw_d0;
input  [63:0] input_r;
output  [22:0] grp_requantize_fu_466_p_din1;
output  [30:0] grp_requantize_fu_466_p_din2;
output  [1:0] grp_requantize_fu_466_p_din3;
input  [7:0] grp_requantize_fu_466_p_dout0;
output   grp_requantize_fu_466_p_ce;

reg ap_idle;
reg m_axi_DATA_IN_0_ARVALID;
reg[63:0] m_axi_DATA_IN_0_ARADDR;
reg m_axi_DATA_IN_0_RREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] icmp_ln63_reg_517;
reg   [0:0] icmp_ln69_reg_542;
reg    ap_predicate_op77_readreq_state3;
reg    ap_block_state3_io_grp1;
reg    ap_block_pp0_stage2_subdone_grp1_done_reg;
reg    ap_block_pp0_stage2_subdone_grp1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln63_reg_517_pp0_iter3_reg;
reg    ap_block_state12_pp0_stage2_iter3_grp5;
reg    ap_block_pp0_stage2_subdone_grp5_done_reg;
reg    ap_block_pp0_stage2_subdone_grp5;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] b1_dw_weight_q0;
reg    DATA_IN_blk_n_AR;
wire    ap_block_pp0_stage0_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_pp0_stage0_subdone;
reg    DATA_IN_blk_n_R;
wire    ap_block_pp0_stage2_grp5;
wire    ap_block_pp0_stage2_grp1;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp3;
reg   [0:0] icmp_ln69_reg_542_pp0_iter2_reg;
reg   [0:0] icmp_ln63_reg_517_pp0_iter1_reg;
reg   [0:0] icmp_ln69_1_reg_558;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln69_1_reg_558_pp0_iter3_reg;
reg   [7:0] reg_191;
reg    ap_predicate_op82_readreq_state5;
reg    ap_block_state5_io_grp3;
reg    ap_predicate_op111_read_state11;
reg    ap_block_state11_pp0_stage1_iter3_grp3;
reg    ap_block_pp0_stage1_11001_grp3;
reg    ap_block_pp0_stage2_11001_grp5;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln63_fu_214_p2;
reg    ap_block_state4_io_grp2;
reg    ap_predicate_op125_read_state13;
reg    ap_block_state13_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln63_reg_517_pp0_iter2_reg;
reg   [0:0] icmp_ln63_reg_517_pp0_iter4_reg;
wire   [5:0] select_ln63_fu_238_p3;
reg   [5:0] select_ln63_reg_521;
wire   [6:0] sub_ln72_fu_272_p2;
reg   [6:0] sub_ln72_reg_529;
reg   [6:0] sub_ln72_reg_529_pp0_iter1_reg;
reg   [6:0] sub_ln72_reg_529_pp0_iter2_reg;
reg   [6:0] sub_ln72_reg_529_pp0_iter3_reg;
wire   [10:0] sub_ln70_fu_290_p2;
reg   [10:0] sub_ln70_reg_536;
wire   [0:0] icmp_ln69_fu_328_p2;
reg   [0:0] icmp_ln69_reg_542_pp0_iter1_reg;
reg   [0:0] icmp_ln69_reg_542_pp0_iter3_reg;
reg   [63:0] DATA_IN_addr_reg_546;
reg   [63:0] DATA_IN_addr_1_reg_552;
wire   [0:0] icmp_ln69_1_fu_377_p2;
reg   [0:0] icmp_ln69_1_reg_558_pp0_iter1_reg;
reg   [0:0] icmp_ln69_1_reg_558_pp0_iter2_reg;
reg   [63:0] DATA_IN_addr_2_reg_562;
wire   [10:0] add_ln74_fu_395_p2;
reg   [10:0] add_ln74_reg_568;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
reg   [10:0] add_ln74_reg_568_pp0_iter1_reg;
reg   [10:0] add_ln74_reg_568_pp0_iter2_reg;
reg   [10:0] add_ln74_reg_568_pp0_iter3_reg;
reg   [10:0] add_ln74_reg_568_pp0_iter4_reg;
reg   [10:0] add_ln74_reg_568_pp0_iter5_reg;
reg   [10:0] add_ln74_reg_568_pp0_iter6_reg;
reg   [10:0] add_ln74_reg_568_pp0_iter7_reg;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg  signed [7:0] b1_dw_weight_load_reg_578;
reg  signed [7:0] b1_dw_weight_load_1_reg_588;
reg  signed [7:0] b1_dw_weight_load_2_reg_598;
wire   [15:0] acc_fu_436_p2;
reg   [15:0] acc_reg_603;
reg  signed [15:0] acc_reg_603_pp0_iter4_reg;
wire   [15:0] mul_ln72_2_fu_449_p2;
reg   [15:0] mul_ln72_2_reg_608;
reg   [15:0] mul_ln72_2_reg_608_pp0_iter5_reg;
reg   [7:0] val_14_reg_613;
wire   [16:0] acc_4_fu_468_p2;
reg   [16:0] acc_4_reg_628;
wire  signed [22:0] sext_ln65_fu_474_p1;
reg   [7:0] ref_tmp19_i_reg_638;
wire    ap_block_pp0_stage1_11001_ignoreCallOp147_grp0;
reg    grp_requantize_fu_182_ap_ce;
reg    ap_block_state12_pp0_stage2_iter3_ignore_call7_grp5;
reg    ap_block_pp0_stage2_11001_ignoreCallOp142;
reg    ap_block_state11_pp0_stage1_iter3_ignore_call7_grp3;
reg    ap_block_pp0_stage1_11001_ignoreCallOp144;
wire    ap_block_pp0_stage2_11001_ignoreCallOp142_grp0;
wire    ap_block_pp0_stage0_11001_ignoreCallOp143_grp0;
wire    ap_block_pp0_stage1_11001_ignoreCallOp144_grp0;
reg  signed [7:0] ap_phi_mux_val_1_phi_fu_164_p4;
reg  signed [7:0] ap_phi_mux_val_15_phi_fu_175_p4;
wire    ap_block_pp0_stage2_ignoreCallOp142_grp0;
wire   [63:0] zext_ln70_fu_405_p1;
wire    ap_block_pp0_stage2_grp0;
wire   [63:0] zext_ln72_1_fu_414_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] zext_ln72_2_fu_424_p1;
wire    ap_block_pp0_stage1_grp0;
wire   [63:0] zext_ln74_fu_478_p1;
wire   [63:0] add_ln70_1_fu_339_p2;
wire   [63:0] add_ln70_3_fu_356_p2;
wire   [63:0] add_ln70_4_fu_383_p2;
reg    ap_block_pp0_stage2_11001_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [5:0] t_fu_88;
wire   [5:0] add_ln67_1_fu_368_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_t_load;
reg   [4:0] c_fu_92;
wire   [4:0] add_ln63_fu_254_p2;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [10:0] indvar_flatten_fu_96;
wire   [10:0] add_ln63_1_fu_220_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    b1_dw_weight_ce0_local;
reg   [6:0] b1_dw_weight_address0_local;
reg    buf_b1_dw_we0_local;
reg    buf_b1_dw_ce0_local;
wire   [0:0] icmp_ln64_fu_232_p2;
wire   [4:0] empty_fu_246_p3;
wire   [6:0] p_shl3_fu_264_p3;
wire   [6:0] zext_ln63_fu_260_p1;
wire   [10:0] p_shl_fu_278_p3;
wire   [10:0] zext_ln70_7_fu_286_p1;
wire   [6:0] zext_ln64_2_fu_315_p1;
wire  signed [6:0] add_ln67_fu_318_p2;
wire  signed [63:0] sext_ln69_fu_324_p1;
wire   [63:0] add_ln70_fu_334_p2;
wire   [63:0] zext_ln72_fu_306_p1;
wire   [63:0] add_ln70_2_fu_351_p2;
wire   [63:0] zext_ln64_fu_309_p1;
wire   [63:0] zext_ln69_fu_373_p1;
wire   [10:0] zext_ln64_1_fu_312_p1;
wire   [6:0] add_ln72_fu_409_p2;
wire   [6:0] add_ln72_1_fu_419_p2;
wire  signed [7:0] sext_ln72_3_fu_445_p0;
wire  signed [15:0] grp_fu_482_p3;
wire  signed [16:0] sext_ln72_5_fu_465_p1;
wire  signed [16:0] sext_ln67_fu_462_p1;
reg    grp_fu_482_ce;
reg    ap_block_pp0_stage1_11001;
reg    ap_block_pp0_stage2_11001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 t_fu_88 = 6'd0;
#0 c_fu_92 = 5'd0;
#0 indvar_flatten_fu_96 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_64_2_b1_dw_weight_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
b1_dw_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b1_dw_weight_address0_local),
    .ce0(b1_dw_weight_ce0_local),
    .q0(b1_dw_weight_q0)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U6(
    .din0(ap_phi_mux_val_1_phi_fu_164_p4),
    .din1(b1_dw_weight_load_reg_578),
    .dout(acc_fu_436_p2)
);

cnn_forward_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U7(
    .din0(sext_ln72_3_fu_445_p0),
    .din1(b1_dw_weight_load_1_reg_588),
    .dout(mul_ln72_2_fu_449_p2)
);

cnn_forward_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_val_15_phi_fu_175_p4),
    .din1(b1_dw_weight_load_2_reg_598),
    .din2(acc_reg_603_pp0_iter4_reg),
    .ce(grp_fu_482_ce),
    .dout(grp_fu_482_p3)
);

cnn_forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp1)) begin
                ap_block_pp0_stage2_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp5)) begin
                ap_block_pp0_stage2_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln63_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_92 <= add_ln63_fu_254_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_92 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln63_fu_214_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_96 <= add_ln63_1_fu_220_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_96 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_fu_88 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (icmp_ln63_reg_517 == 1'd0))) begin
        t_fu_88 <= add_ln67_1_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3))) begin
        DATA_IN_addr_1_reg_552 <= add_ln70_3_fu_356_p2;
        DATA_IN_addr_2_reg_562 <= add_ln70_4_fu_383_p2;
        DATA_IN_addr_reg_546 <= add_ln70_1_fu_339_p2;
        icmp_ln69_1_reg_558 <= icmp_ln69_1_fu_377_p2;
        icmp_ln69_1_reg_558_pp0_iter1_reg <= icmp_ln69_1_reg_558;
        icmp_ln69_1_reg_558_pp0_iter2_reg <= icmp_ln69_1_reg_558_pp0_iter1_reg;
        icmp_ln69_1_reg_558_pp0_iter3_reg <= icmp_ln69_1_reg_558_pp0_iter2_reg;
        icmp_ln69_reg_542 <= icmp_ln69_fu_328_p2;
        icmp_ln69_reg_542_pp0_iter1_reg <= icmp_ln69_reg_542;
        icmp_ln69_reg_542_pp0_iter2_reg <= icmp_ln69_reg_542_pp0_iter1_reg;
        icmp_ln69_reg_542_pp0_iter3_reg <= icmp_ln69_reg_542_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        acc_4_reg_628 <= acc_4_fu_468_p2;
        add_ln74_reg_568 <= add_ln74_fu_395_p2;
        add_ln74_reg_568_pp0_iter1_reg <= add_ln74_reg_568;
        add_ln74_reg_568_pp0_iter2_reg <= add_ln74_reg_568_pp0_iter1_reg;
        add_ln74_reg_568_pp0_iter3_reg <= add_ln74_reg_568_pp0_iter2_reg;
        add_ln74_reg_568_pp0_iter4_reg <= add_ln74_reg_568_pp0_iter3_reg;
        add_ln74_reg_568_pp0_iter5_reg <= add_ln74_reg_568_pp0_iter4_reg;
        add_ln74_reg_568_pp0_iter6_reg <= add_ln74_reg_568_pp0_iter5_reg;
        add_ln74_reg_568_pp0_iter7_reg <= add_ln74_reg_568_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        acc_reg_603 <= acc_fu_436_p2;
        acc_reg_603_pp0_iter4_reg <= acc_reg_603;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        b1_dw_weight_load_1_reg_588 <= b1_dw_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        b1_dw_weight_load_2_reg_598 <= b1_dw_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        b1_dw_weight_load_reg_578 <= b1_dw_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln63_reg_517 <= icmp_ln63_fu_214_p2;
        icmp_ln63_reg_517_pp0_iter1_reg <= icmp_ln63_reg_517;
        icmp_ln63_reg_517_pp0_iter2_reg <= icmp_ln63_reg_517_pp0_iter1_reg;
        icmp_ln63_reg_517_pp0_iter3_reg <= icmp_ln63_reg_517_pp0_iter2_reg;
        icmp_ln63_reg_517_pp0_iter4_reg <= icmp_ln63_reg_517_pp0_iter3_reg;
        select_ln63_reg_521 <= select_ln63_fu_238_p3;
        sub_ln70_reg_536[10 : 2] <= sub_ln70_fu_290_p2[10 : 2];
        sub_ln72_reg_529 <= sub_ln72_fu_272_p2;
        sub_ln72_reg_529_pp0_iter1_reg <= sub_ln72_reg_529;
        sub_ln72_reg_529_pp0_iter2_reg <= sub_ln72_reg_529_pp0_iter1_reg;
        sub_ln72_reg_529_pp0_iter3_reg <= sub_ln72_reg_529_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        mul_ln72_2_reg_608 <= mul_ln72_2_fu_449_p2;
        mul_ln72_2_reg_608_pp0_iter5_reg <= mul_ln72_2_reg_608;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp147_grp0) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg))) begin
        ref_tmp19_i_reg_638 <= grp_requantize_fu_466_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3)))) begin
        reg_191 <= m_axi_DATA_IN_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        val_14_reg_613 <= m_axi_DATA_IN_0_RDATA;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (ap_predicate_op77_readreq_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln69_1_reg_558 == 1'd1) & (icmp_ln63_reg_517_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (icmp_ln63_reg_517 == 1'd0)))) begin
        DATA_IN_blk_n_AR = m_axi_DATA_IN_0_ARREADY;
    end else begin
        DATA_IN_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln69_1_reg_558_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln69_reg_542_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp3)))) begin
        DATA_IN_blk_n_R = m_axi_DATA_IN_0_RVALID;
    end else begin
        DATA_IN_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (icmp_ln63_reg_517 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_reg_517_pp0_iter4_reg == 1'd0) & (icmp_ln69_1_reg_558_pp0_iter3_reg == 1'd1))) begin
        ap_phi_mux_val_15_phi_fu_175_p4 = val_14_reg_613;
    end else begin
        ap_phi_mux_val_15_phi_fu_175_p4 = 8'd0;
    end
end

always @ (*) begin
    if (((icmp_ln69_reg_542_pp0_iter3_reg == 1'd1) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0))) begin
        ap_phi_mux_val_1_phi_fu_164_p4 = reg_191;
    end else begin
        ap_phi_mux_val_1_phi_fu_164_p4 = 8'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_92;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_96;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 6'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_88;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        b1_dw_weight_address0_local = zext_ln72_2_fu_424_p1;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        b1_dw_weight_address0_local = zext_ln72_1_fu_414_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0))) begin
        b1_dw_weight_address0_local = zext_ln70_fu_405_p1;
    end else begin
        b1_dw_weight_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        b1_dw_weight_ce0_local = 1'b1;
    end else begin
        b1_dw_weight_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        buf_b1_dw_ce0_local = 1'b1;
    end else begin
        buf_b1_dw_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        buf_b1_dw_we0_local = 1'b1;
    end else begin
        buf_b1_dw_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_482_ce = 1'b1;
    end else begin
        grp_fu_482_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp142_grp0) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp144_grp0) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp143_grp0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg)))) begin
        grp_requantize_fu_182_ap_ce = 1'b1;
    end else begin
        grp_requantize_fu_182_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op82_readreq_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3))) begin
        m_axi_DATA_IN_0_ARADDR = DATA_IN_addr_2_reg_562;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (icmp_ln63_reg_517 == 1'd0))) begin
        m_axi_DATA_IN_0_ARADDR = DATA_IN_addr_1_reg_552;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (ap_predicate_op77_readreq_state3 == 1'b1))) begin
        m_axi_DATA_IN_0_ARADDR = DATA_IN_addr_reg_546;
    end else begin
        m_axi_DATA_IN_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg) & (ap_predicate_op77_readreq_state3 == 1'b1)) | ((ap_predicate_op82_readreq_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (icmp_ln63_reg_517 == 1'd0)))) begin
        m_axi_DATA_IN_0_ARVALID = 1'b1;
    end else begin
        m_axi_DATA_IN_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op125_read_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op111_read_state11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3)))) begin
        m_axi_DATA_IN_0_RREADY = 1'b1;
    end else begin
        m_axi_DATA_IN_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_4_fu_468_p2 = ($signed(sext_ln72_5_fu_465_p1) + $signed(sext_ln67_fu_462_p1));

assign add_ln63_1_fu_220_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln63_fu_254_p2 = (ap_sig_allocacmp_c_load + empty_fu_246_p3);

assign add_ln67_1_fu_368_p2 = (select_ln63_reg_521 + 6'd1);

assign add_ln67_fu_318_p2 = ($signed(zext_ln64_2_fu_315_p1) + $signed(7'd127));

assign add_ln70_1_fu_339_p2 = (add_ln70_fu_334_p2 + zext_ln72_fu_306_p1);

assign add_ln70_2_fu_351_p2 = (zext_ln72_fu_306_p1 + input_r);

assign add_ln70_3_fu_356_p2 = (add_ln70_2_fu_351_p2 + zext_ln64_fu_309_p1);

assign add_ln70_4_fu_383_p2 = (add_ln70_2_fu_351_p2 + zext_ln69_fu_373_p1);

assign add_ln70_fu_334_p2 = ($signed(sext_ln69_fu_324_p1) + $signed(input_r));

assign add_ln72_1_fu_419_p2 = (sub_ln72_reg_529_pp0_iter3_reg + 7'd2);

assign add_ln72_fu_409_p2 = (sub_ln72_reg_529_pp0_iter2_reg + 7'd1);

assign add_ln74_fu_395_p2 = (zext_ln64_1_fu_312_p1 + sub_ln70_reg_536);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

assign ap_block_pp0_stage0_11001_ignoreCallOp143_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter3_grp3)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp3 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter3_grp3)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp144 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter3_ignore_call7_grp3)));
end

assign ap_block_pp0_stage1_11001_ignoreCallOp144_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp147_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp3)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage1_iter3_grp3)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter3_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = ((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp5 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter3_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_ignoreCallOp142 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter3_ignore_call7_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage2_11001_ignoreCallOp142_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_ignoreCallOp142_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter3_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp1 = ((1'b1 == ap_block_state3_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp5 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage2_iter3_grp5) & (1'b0 == ap_block_pp0_stage2_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_state11_pp0_stage1_iter3_grp3 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (ap_predicate_op111_read_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage1_iter3_ignore_call7_grp3 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (ap_predicate_op111_read_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state12_pp0_stage2_iter3_grp5 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_block_state12_pp0_stage2_iter3_ignore_call7_grp5 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter4 = ((m_axi_DATA_IN_0_RVALID == 1'b0) & (ap_predicate_op125_read_state13 == 1'b1));
end

always @ (*) begin
    ap_block_state3_io_grp1 = ((m_axi_DATA_IN_0_ARREADY == 1'b0) & (ap_predicate_op77_readreq_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_io_grp2 = ((m_axi_DATA_IN_0_ARREADY == 1'b0) & (icmp_ln63_reg_517 == 1'd0));
end

always @ (*) begin
    ap_block_state5_io_grp3 = ((m_axi_DATA_IN_0_ARREADY == 1'b0) & (ap_predicate_op82_readreq_state5 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

always @ (*) begin
    ap_predicate_op111_read_state11 = ((icmp_ln69_reg_542_pp0_iter2_reg == 1'd1) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op125_read_state13 = ((icmp_ln69_1_reg_558_pp0_iter3_reg == 1'd1) & (icmp_ln63_reg_517_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op77_readreq_state3 = ((icmp_ln69_reg_542 == 1'd1) & (icmp_ln63_reg_517 == 1'd0));
end

always @ (*) begin
    ap_predicate_op82_readreq_state5 = ((icmp_ln69_1_reg_558 == 1'd1) & (icmp_ln63_reg_517_pp0_iter1_reg == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign buf_b1_dw_address0 = zext_ln74_fu_478_p1;

assign buf_b1_dw_ce0 = buf_b1_dw_ce0_local;

assign buf_b1_dw_d0 = ref_tmp19_i_reg_638;

assign buf_b1_dw_we0 = buf_b1_dw_we0_local;

assign empty_fu_246_p3 = ((icmp_ln64_fu_232_p2[0:0] == 1'b1) ? 5'd1 : 5'd0);

assign grp_requantize_fu_466_p_ce = grp_requantize_fu_182_ap_ce;

assign grp_requantize_fu_466_p_din1 = sext_ln65_fu_474_p1;

assign grp_requantize_fu_466_p_din2 = 31'd15182302;

assign grp_requantize_fu_466_p_din3 = 2'd3;

assign icmp_ln63_fu_214_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1440) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_232_p2 = ((ap_sig_allocacmp_t_load == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln69_1_fu_377_p2 = ((add_ln67_1_fu_368_p2 < 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_328_p2 = ((add_ln67_fu_318_p2 < 7'd60) ? 1'b1 : 1'b0);

assign m_axi_DATA_IN_0_ARBURST = 2'd0;

assign m_axi_DATA_IN_0_ARCACHE = 4'd0;

assign m_axi_DATA_IN_0_ARID = 1'd0;

assign m_axi_DATA_IN_0_ARLEN = 64'd1;

assign m_axi_DATA_IN_0_ARLOCK = 2'd0;

assign m_axi_DATA_IN_0_ARPROT = 3'd0;

assign m_axi_DATA_IN_0_ARQOS = 4'd0;

assign m_axi_DATA_IN_0_ARREGION = 4'd0;

assign m_axi_DATA_IN_0_ARSIZE = 3'd0;

assign m_axi_DATA_IN_0_ARUSER = 1'd0;

assign m_axi_DATA_IN_0_AWADDR = 64'd0;

assign m_axi_DATA_IN_0_AWBURST = 2'd0;

assign m_axi_DATA_IN_0_AWCACHE = 4'd0;

assign m_axi_DATA_IN_0_AWID = 1'd0;

assign m_axi_DATA_IN_0_AWLEN = 32'd0;

assign m_axi_DATA_IN_0_AWLOCK = 2'd0;

assign m_axi_DATA_IN_0_AWPROT = 3'd0;

assign m_axi_DATA_IN_0_AWQOS = 4'd0;

assign m_axi_DATA_IN_0_AWREGION = 4'd0;

assign m_axi_DATA_IN_0_AWSIZE = 3'd0;

assign m_axi_DATA_IN_0_AWUSER = 1'd0;

assign m_axi_DATA_IN_0_AWVALID = 1'b0;

assign m_axi_DATA_IN_0_BREADY = 1'b0;

assign m_axi_DATA_IN_0_WDATA = 8'd0;

assign m_axi_DATA_IN_0_WID = 1'd0;

assign m_axi_DATA_IN_0_WLAST = 1'b0;

assign m_axi_DATA_IN_0_WSTRB = 1'd0;

assign m_axi_DATA_IN_0_WUSER = 1'd0;

assign m_axi_DATA_IN_0_WVALID = 1'b0;

assign p_shl3_fu_264_p3 = {{add_ln63_fu_254_p2}, {2'd0}};

assign p_shl_fu_278_p3 = {{add_ln63_fu_254_p2}, {6'd0}};

assign select_ln63_fu_238_p3 = ((icmp_ln64_fu_232_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_t_load);

assign sext_ln65_fu_474_p1 = $signed(acc_4_reg_628);

assign sext_ln67_fu_462_p1 = $signed(mul_ln72_2_reg_608_pp0_iter5_reg);

assign sext_ln69_fu_324_p1 = add_ln67_fu_318_p2;

assign sext_ln72_3_fu_445_p0 = reg_191;

assign sext_ln72_5_fu_465_p1 = grp_fu_482_p3;

assign sub_ln70_fu_290_p2 = (p_shl_fu_278_p3 - zext_ln70_7_fu_286_p1);

assign sub_ln72_fu_272_p2 = (p_shl3_fu_264_p3 - zext_ln63_fu_260_p1);

assign zext_ln63_fu_260_p1 = add_ln63_fu_254_p2;

assign zext_ln64_1_fu_312_p1 = select_ln63_reg_521;

assign zext_ln64_2_fu_315_p1 = select_ln63_reg_521;

assign zext_ln64_fu_309_p1 = select_ln63_reg_521;

assign zext_ln69_fu_373_p1 = add_ln67_1_fu_368_p2;

assign zext_ln70_7_fu_286_p1 = p_shl3_fu_264_p3;

assign zext_ln70_fu_405_p1 = sub_ln72_reg_529_pp0_iter2_reg;

assign zext_ln72_1_fu_414_p1 = add_ln72_fu_409_p2;

assign zext_ln72_2_fu_424_p1 = add_ln72_1_fu_419_p2;

assign zext_ln72_fu_306_p1 = sub_ln70_reg_536;

assign zext_ln74_fu_478_p1 = add_ln74_reg_568_pp0_iter7_reg;

always @ (posedge ap_clk) begin
    sub_ln70_reg_536[1:0] <= 2'b00;
end

endmodule //cnn_forward_cnn_forward_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_64_2
